<a href="https://colab.research.google.com/github/MalakSalehh/Thesis-datasets/blob/main/ASAP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
from google.colab import files
uploaded = files.upload()

Saving training_set_rel3.tsv.zip to training_set_rel3.tsv.zip

In [5]:
!unzip training_set_rel3.tsv.zip

Archive:  training_set_rel3.tsv.zip
  inflating: training_set_rel3.tsv

# Dataset Metadata Description
The dataset used in this study is the **Hewlett Foundation Automated Essay Scoring (AES) dataset**, originally released for the Kaggle Automated Student Assessment Prize (ASAP) competition. The dataset contains **12,976 student essays** written by students in grades **7 to 10**.

The dataset includes **28 variables** describing essay identifiers, essay prompts, essay text, and scores assigned by multiple human raters.

---

## Dataset Structure

Each row in the dataset represents **one student essay**, while each column represents an attribute associated with the essay.

The dataset dimensions are:

- **Number of essays:** 12,976  
- **Number of variables:** 28  

---

## Identification Variables

These columns uniquely identify each essay and its associated prompt.

- **essay_id**: A unique identifier for each essay.
- **essay_set**: Identifies which prompt the essay belongs to. The dataset contains **eight essay sets**, each corresponding to a different writing prompt.

---

## Essay Text

- **essay**: Contains the full textual response written by the student.

This column represents the **primary input data** used for automated essay scoring.

---

## Human Rater Scores

Each essay was evaluated by multiple human raters. The dataset includes the individual scores assigned by these raters.

- **rater1_domain1**
- **rater2_domain1**
- **rater3_domain1**

These columns represent scores assigned independently by different graders.

---

## Final Resolved Score

- **domain1_score**

This column represents the **final resolved score** determined after combining the individual rater scores. This value serves as the **ground truth label** used for training and evaluating automated essay scoring systems.

---

## Secondary Scoring Domain

Some essays include an additional scoring dimension.

- **rater1_domain2**
- **rater2_domain2**
- **domain2_score**

These scores are primarily associated with **essay set 2**, which evaluates essays across two scoring domains.

---

## Trait-Level Scores

Some essay sets include detailed trait-level scoring that evaluates specific aspects of writing quality.

Examples include:

- **rater1_trait1 – rater1_trait6**
- **rater2_trait1 – rater2_trait6**
- **rater3_trait1 – rater3_trait6**

These traits evaluate writing characteristics such as organization, grammar, coherence, and language usage.

---

## Missing Values in the Dataset

Certain columns contain **NaN (Not a Number)** values. This occurs because not all essay sets use the same scoring criteria.

For example:

- Some essay sets only contain **domain1 scores**.
- Essay set 2 includes **two scoring domains**.
- Essay sets 7–8 include **trait-level scoring**.

As a result, variables that are not applicable to certain essay sets appear as missing values.

---

## Key Variables Used in the Study

For the initial analysis and experimentation, the following variables are primarily used:

- **essay** → input text
- **domain1_score** → target score
- **essay_set** → prompt identifier

These variables provide the essential information required for automated essay scoring experiments.

In [6]:
import pandas as pd

df = pd.read_csv('training_set_rel3.tsv', sep='\t', encoding='latin1')

In [7]:
print("Shape:", df.shape)
print("\nColumns:")
print(df.columns.tolist())

Shape: (12976, 28)

Columns:
['essay_id', 'essay_set', 'essay', 'rater1_domain1', 'rater2_domain1', 'rater3_domain1', 'domain1_score', 'rater1_domain2', 'rater2_domain2', 'domain2_score', 'rater1_trait1', 'rater1_trait2', 'rater1_trait3', 'rater1_trait4', 'rater1_trait5', 'rater1_trait6', 'rater2_trait1', 'rater2_trait2', 'rater2_trait3', 'rater2_trait4', 'rater2_trait5', 'rater2_trait6', 'rater3_trait1', 'rater3_trait2', 'rater3_trait3', 'rater3_trait4', 'rater3_trait5', 'rater3_trait6']

The dataset contains 12,976 student essays and 28 associated variables describing essay identifiers, prompt identifiers, essay text, and scores assigned by human raters.
* Each essay is uniquely identified by an essay identifier and is associated with an essay set that corresponds to a specific writing prompt.
* Each essay was evaluated by multiple human raters. The dataset includes the individual scores assigned by these raters.
* The **domain1_score** column represents the resolved score derived from the individual rater evaluations and serves as the ground truth label for automated essay scoring experiments.
* Some essay sets include a secondary scoring dimension represented by domain2_score.

In [8]:
import pandas as pd

df = pd.read_csv('training_set_rel3.tsv', sep='\t', encoding='latin1')
df.head()

,essay_id,essay_set,essay,rater1_domain1,rater2_domain1,rater3_domain1,domain1_score,rater1_domain2,rater2_domain2,domain2_score,...,rater2_trait3,rater2_trait4,rater2_trait5,rater2_trait6,rater3_trait1,rater3_trait2,rater3_trait3,rater3_trait4,rater3_trait5,rater3_trait6
0,1,1,"Dear local newspaper, I think effects computer...",4,4,NaN,8,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,1,"Dear @CAPS1 @CAPS2, I believe that using compu...",5,4,NaN,9,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,1,"Dear, @CAPS1 @CAPS2 @CAPS3 More and more peopl...",4,3,NaN,7,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,1,"Dear Local Newspaper, @CAPS1 I have found that...",5,5,NaN,10,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,1,"Dear @LOCATION1, I know having computers has a...",4,4,NaN,8,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
df['essay_set'].value_counts().sort_index() #Number of Essays in each essay set

essay_set
1    1783
2    1800
3    1726
4    1770
5    1805
6    1800
7    1569
8     723
Name: count, dtype: int64

In [9]:
df.groupby('essay_set')['domain1_score'].agg(['min','max']) #score range for each essay set.

           min  max
essay_set
1            2   12
2            1    6
3            0    3
4            0    3
5            0    4
6            0    4
7            2   24
8           10   60

In [10]:
df['essay_word_count'] = df['essay'].apply(lambda x: len(str(x).split()))
df['essay_word_count'].describe() #shortest essay, longest essay, average essay length in WORDS

count    12976.000000
mean       222.708154
std        175.919826
min          2.000000
25%         98.000000
50%        163.000000
75%        307.000000
max       1064.000000
Name: essay_word_count, dtype: float64

**ESSAY SET** **1**

In [10]:
# Filter only essay set 1
set1 = df[df['essay_set'] == 1]

# check shape
set1.shape

(1783, 28)

In [11]:
set1 = set1[['essay_id','essay','domain1_score']]

set1.head()

   essay_id                                              essay  domain1_score
0         1  Dear local newspaper, I think effects computer...              8
1         2  Dear @CAPS1 @CAPS2, I believe that using compu...              9
2         3  Dear, @CAPS1 @CAPS2 @CAPS3 More and more peopl...              7
3         4  Dear Local Newspaper, @CAPS1 I have found that...             10
4         5  Dear @LOCATION1, I know having computers has a...              8

In [13]:
set1['essay'] = set1['essay'].str.replace('\n',' ')
set1['essay'] = set1['essay'].str.strip()
set1.head() ##removes line breaks inside each essay.

   essay_id                                              essay  domain1_score
0         1  Dear local newspaper, I think effects computer...              8
1         2  Dear @CAPS1 @CAPS2, I believe that using compu...              9
2         3  Dear, @CAPS1 @CAPS2 @CAPS3 More and more peopl...              7
3         4  Dear Local Newspaper, @CAPS1 I have found that...             10
4         5  Dear @LOCATION1, I know having computers has a...              8

In [14]:
set1['domain1_score'].value_counts().sort_index()

domain1_score
2      10
3       1
4      17
5      17
6     110
7     135
8     687
9     334
10    316
11    109
12     47
Name: count, dtype: int64

In [12]:
def categorize(score):
    if score <= 5:
        return "Low"
    elif score <= 8:
        return "Medium"
    else:
        return "High"

set1['score_category'] = set1['domain1_score'].apply(categorize)
set1[['domain1_score','score_category']].head()

   domain1_score score_category
0              8         Medium
1              9           High
2              7         Medium
3             10           High
4              8         Medium

In [13]:
cal_low = set1[set1['score_category'] == 'Low'].sample(2, random_state=42)
cal_med = set1[set1['score_category'] == 'Medium'].sample(2, random_state=42)
cal_high = set1[set1['score_category'] == 'High'].sample(2, random_state=42)

calibration = pd.concat([cal_low, cal_med, cal_high]).sample(frac=1, random_state=42).reset_index(drop=True)
calibration

,essay_id,essay,domain1_score,score_category
0,1592,The computers are cool. Do you now I werpsite ...,2,Low
1,995,"I think computers are good, because some peopl...",4,Low
2,686,"Dear local newspaper, I would like to speak up...",9,High
3,1572,"Dear to @CAPS1 this @MONTH1 concern, Computers...",8,Medium
4,1567,"Dear @ORGANIZATION1, @DATE1, everywhere you lo...",11,High
5,146,Dear local newspaper I think that usieng compu...,6,Medium

In [14]:
demo = set1.drop(calibration.index, errors='ignore').sample(5, random_state=42).reset_index(drop=True)

demo

,essay_id,essay,domain1_score,score_category
0,72,"Hello, I decided to write in to the paper on t...",10,High
1,950,Each year the world becomes more and more adva...,10,High
2,841,"Dear local Newspaper, Computers don't take exe...",7,Medium
3,1710,Wouldn't you agree that computers have a great...,9,High
4,808,"Hello @CAPS1 @CAPS2, @CAPS3 you think computer...",7,Medium

# **TRIAL ONE (Calibration+ essays for each essay)**

In [15]:
def format_calibration_examples(calibration_df):
    examples = ""
    for i, row in calibration_df.iterrows():
        examples += f"""
Calibration Example {i+1}

Essay:
{row['essay']}

Human Score: {row['domain1_score']}
Category: {row['score_category']}
"""
    return examples

calibration_text = format_calibration_examples(calibration)
print(calibration_text)

Calibration Example 1

Essay:
The computers are cool. Do you now I werpsite is @NUM1.com. We nede to time the lemt lo-menteno it. I love the compueters. We nede @NUM2 make a computers are grene compurers.

Human Score: 2
Category: Low

Calibration Example 2

Essay:
I think computers are good, because some people dont have phones so @CAPS1 a good way to conect with people you know, also meet new people. Second some people are going to collage when there done with high school so you could just look on the computers and find one you like and pricess, also find ways there. Third reason is ahopping if a holiday is coming up you could check online and find stuff for cheap and nice to you. You could also order it to your house online if you dont got alot of time to go shopping. @CAPS1 some reasons why I think online is good you could chat, find places and pricess, collages and also shop online @CAPS1 why online is good.

Human Score: 4
Category: Low

Calibration Example 3

Essay:
Dear local newspaper, I would like to speak upon the topic of the effects that computers have on people. My opion on this topic is that computers do have an effect on people. Most people while surfing the internet don't keep track of time. What I mean when I say most people lose track of time is that, they try to keep track of the time but while on the web something @MONTH1 pop that catches their intrest and at that same time there focus is on something else. Some of the other effects computers can have on people is keeping them in the house. When many people are on the web they tend not to excersise as much. When in the house on the web most people that excersise stop excersising. The reason why this occurs is because while people are on the computer chair you feel so relaxed and calm that you don't want to get up. This leads into eating unhealthy foods. Some such as chips, donuts, twinkies and etc. Some @CAPS1 do not believe that is an opinion. The reason I say this is because while watching television the other day I saw a commercial that said quote "@CAPS2 that are more active are healthier than @CAPS2 that stay on the computer all day. Most @CAPS1 do gain weight on the computer because they are not physically active. Not being physically active can lead to A) obesity @CAPS4) cloged arteries or @CAPS5) lazyness. It can lead to all three because those are the effects of being on a computer every of the day. Most @CAPS1 should be enjoying nature instead of staying on the computer. There is a lot more to life than being on the web. Some such as playing sports. Not only is playing sports fun but at the same tim it is also healthy. Would you rather live to @NUM1 or live to @NUM2. And so local newspaper that is why I am writing you this letter today. I mean would you rather have friends @CAPS2 or be lonely. There are weight surgerys but those can rack up to thousands of dollars. And yes weight loss surgery does have effects such as death. So come on @LOCATION1 its your decison and remember the most important part of this letter which is between liveing healthy and young or dieing unhealthy and suffer. Its your choice @LOCATION1 decide.

Human Score: 9
Category: High

Calibration Example 4

Essay:
Dear to @CAPS1 this @MONTH1 concern, Computers do a whole lot now of days. You can play games, do homework, socialize but don't you think there are better things than that. Such as exercising, enjoying the beauty of nature, and most importantly interacting with family and friends. These are all the things that computers take away from people. Once you get onto a computer you never want to get off. If you look at it, it doesn't take much work and energy to use a computer. So if you eat and use the computer all day your not really burning any calories therefore you will gain weight. Computers make people feel lazy sometimes therefore they spend less time exercising. That is not good for your health at all. Exercising gives you energy and is good for you. Have you ever looked out the window and saw how beautiful nature is? When your on the computer chit-chatting with people and playing online friends do you think about what your missing. Everytime I use the computer I wish I could be outside playing and enjoying nature. Trees, flowers, plants, grass and lots of other things are what make up the earth, but some people don't apreciate those things. So next time your on the computer think about that. While your on the computer wasting time there is another homeless child wandering maybe looking for their family. Would you like to be that child who doesnt have a family or any type of friends? Lots of people think of their life without a family but it can happen anyday. So I believe instead of wasting time on the computer we should go and interact with family and friends. Even if its just having a conversation do it, maybe it can show them that you really care. In conclusion, I think that computers are a waste of time. I understand how people say it is used to comunicate with people but back then they didnt have computers and they communicated so we can to. Computes make you spend less time exercising, keeps you from enjoying nature and lastly interacting with family and friends. You won't go wrong if you listen to someone who uses a computer everyday.

Human Score: 8
Category: Medium

Calibration Example 5

Essay:
Dear @ORGANIZATION1, @DATE1, everywhere you look technology is being exercised and it is beneficial to many aspects in our lives @DATE1. Many engineers strive to improve on technologic devices popularity, while others use it in communicate or relax. study conducted by @ORGANIZATION2 university, the computer is the most largely operated machine. The computer positively contributes to our education, economy, and entertainment. As i mentioned before the computer is beneficial to our education. An example of this is the school i attend, middle school. Here at we have over @NUM1 computers in use throughout the school day. These computers help the students complete research papers, typed assignments and other teacher requirement papers. By using the computer to complete research papers students save hours of scanning through books in the library and money on reading books. In addition, computers teachers in organizing files and entering grades online so students can check their. This is beneficial considering the amount of and assignments graded each week. Moreover, a computer called the "parent portal" allows the students to stay connected with school events that would not be mentioned otherwise in all, computer are way of. Besides education computers touch upon our economy as well. Now, due to the wide variety of computer selection, a computer is affordable, starting at prices as low as sixty dollars! This is a positive aspect of the computer because currently the has been enduring the economy since the depression in the. Consequently, the reason has made families start to cut many useful technologe devices out of the. However, since the price of computers decreased purchase have stimulating. Also, the computer has mainly improved methods of. Instead of listening to a cd player you can download listen to while chatting online with friends. This is very helpful for last-minute plan changes, because for those who do not own a telephone, communication @MONTH1 be, negatively affecting your time of entertainment. In addition, children can use internet in order to play games to take that mind off of a hard day at school, or an adult's rough work computersin producing the you watch at home on the couch and the videogame you ordered off of ebay. From facebook and myspace, to and "gone with the wind." Computers create a relaxing entertainment opportunity.

Human Score: 11
Category: High

Calibration Example 6

Essay:
Dear local newspaper I think that usieng computers help people becuse if we did not have computers we would not now ehey thing about eneyone or eneything like all of the @CAPS1 I would not now eneything about them but with computers I know alot about them and there lives like @CAPS2 @CAPS3 @CAPS4 got shot in the back of the head and. @CAPS4 got shot to and I know alot about the @ORGANIZATION1 there white people that to fear in to black people and the same with the wars like world @NUM1 and world @NUM2 and the @CAPS5 and @PERSON1 and the @CAPS6 war there was like plain spy palin flying across @LOCATION1 and they shot him down becuse we were trying to see if thay had eney nuculer bombs offer there. And the same with google and yahoo with google you can type in eneything and you will get a answer and most liked a corect answer yahoo and google is great for some worke and products end studying becuse you then you do to and that I think that computer are good.

Human Score: 6
Category: Medium

In [16]:
demo_essay = demo.iloc[0]['essay']
print(demo_essay)

Hello, I decided to write in to the paper on the topic of computers, and how they benefit society. Comuters are powerful machines, and can be used completing otherwise menial and boring tasks. They benefit people in many ways, like they are very useful in buissness, helpful in education, and connect friends and family together. Computers are uselful in buissness and are an extremely important tool in a common workplace today, and make work get done much more efficiently than if they didn't have computers. One reason Computers are so useful in the workplace is because computers can storee far more data that can be put on paper. Also, they can do jobs and processes very quickly, which is important in the workplace. They can also be used for sending important information quickly and without much trouble. These are all valid reasons comuters are beneficial in buissness, and help things get done. Computers are important today's schools and educational programs becasue they can help students work in a more efficient fashion. "@PERCENT1 of all surveyed students said they would rather type a paper for school than write on by hand, and shows that they value them in their education." said @PERSON2, a professor at @ORGANIZATION1. This shows that Computers are important to students, and are used their benefit. In addition to students writing papers, computers are being used by teachers and school systems for grading, attendance records, and more. The teachers at my school are using @CAPS1 @CAPS2, pieces of hardware that are directly connected to computers, and can be used instead of white @CAPS2, and I see that students are getting more involved in class, and focused, because this computer technology is being used. All of these @CAPS3 are reasons computers are helpful in educational proceeses, and should continue to be used. Many people want to be able talk to there friends and family when they are bored, and because of computers and social networking websites, and instant messaging programs, this is made much easier. "@PERCENT2 of teens have at least one sacial networking site they visit on a regular basis." said @PERSON1, a phycologist, who speciaizes in teens, This shows that people use these sites, and that they like them. Families that are separated because one @MONTH1 have moved out of the house recently might want to communicate with one another, and because of computers, they can. There are multiple ways that they could use their computers to keep in touch, like instant messaging systems mentioned before. Being able to communicate with one another makes theses people happy, and benefits society. Overall, being able to communicate through computers is an enjoyable thing for many people, and is important to society today. To conclude, computers contribute to society in ways that make it much better for everyone. Whether it's through helping buissnesses being more efficient, giving students the ability to work faster, and in a way they prefer, or if it's helping people stay in touch, computers are always benefiting society. These machines hardly ever slow people more thant manually doing the work would, and the positive influence they have far outweighs the bad they do.

In [17]:
rubric_text = """
Essay Prompt:
Write a letter to your local newspaper stating your opinion on the effects computers have on people and persuade readers to agree with your position.

Rubric:
1 – Undeveloped response with minimal support.
2 – Underdeveloped response with weak reasoning.
3 – Minimally developed argument with limited support.
4 – Adequate argument with some supporting details.
5 – Developed argument with clear reasoning and organization.
6 – Strong persuasive response with well-developed ideas.

Scoring rule:
Two raters assign scores from 1–6.
Final score = sum of both scores.
Final score range: 2–12.
"""

In [18]:
full_prompt = f"""
You are an expert essay grader evaluating student essays.

{rubric_text}

Calibration Examples:
{calibration_text}

Now evaluate the following essay.

Essay:
{demo_essay}

Instructions:
1. Predict the final score between 2 and 12.
2. Predict the category: Low, Medium, or High.
3. Explain your reasoning.

Return your answer in this format:

Final Score:
Category:
Reasoning:
"""

print(full_prompt)

You are an expert essay grader evaluating student essays.


Essay Prompt:
Write a letter to your local newspaper stating your opinion on the effects computers have on people and persuade readers to agree with your position.

Rubric:
1 – Undeveloped response with minimal support.
2 – Underdeveloped response with weak reasoning.
3 – Minimally developed argument with limited support.
4 – Adequate argument with some supporting details.
5 – Developed argument with clear reasoning and organization.
6 – Strong persuasive response with well-developed ideas.

Scoring rule:
Two raters assign scores from 1–6.
Final score = sum of both scores.
Final score range: 2–12.


Calibration Examples:

Calibration Example 1

Essay:
The computers are cool. Do you now I werpsite is @NUM1.com. We nede to time the lemt lo-menteno it. I love the compueters. We nede @NUM2 make a computers are grene compurers.

Human Score: 2
Category: Low

Calibration Example 2

Essay:
I think computers are good, because some people dont have phones so @CAPS1 a good way to conect with people you know, also meet new people. Second some people are going to collage when there done with high school so you could just look on the computers and find one you like and pricess, also find ways there. Third reason is ahopping if a holiday is coming up you could check online and find stuff for cheap and nice to you. You could also order it to your house online if you dont got alot of time to go shopping. @CAPS1 some reasons why I think online is good you could chat, find places and pricess, collages and also shop online @CAPS1 why online is good.

Human Score: 4
Category: Low

Calibration Example 3

Essay:
Dear local newspaper, I would like to speak upon the topic of the effects that computers have on people. My opion on this topic is that computers do have an effect on people. Most people while surfing the internet don't keep track of time. What I mean when I say most people lose track of time is that, they try to keep track of the time but while on the web something @MONTH1 pop that catches their intrest and at that same time there focus is on something else. Some of the other effects computers can have on people is keeping them in the house. When many people are on the web they tend not to excersise as much. When in the house on the web most people that excersise stop excersising. The reason why this occurs is because while people are on the computer chair you feel so relaxed and calm that you don't want to get up. This leads into eating unhealthy foods. Some such as chips, donuts, twinkies and etc. Some @CAPS1 do not believe that is an opinion. The reason I say this is because while watching television the other day I saw a commercial that said quote "@CAPS2 that are more active are healthier than @CAPS2 that stay on the computer all day. Most @CAPS1 do gain weight on the computer because they are not physically active. Not being physically active can lead to A) obesity @CAPS4) cloged arteries or @CAPS5) lazyness. It can lead to all three because those are the effects of being on a computer every of the day. Most @CAPS1 should be enjoying nature instead of staying on the computer. There is a lot more to life than being on the web. Some such as playing sports. Not only is playing sports fun but at the same tim it is also healthy. Would you rather live to @NUM1 or live to @NUM2. And so local newspaper that is why I am writing you this letter today. I mean would you rather have friends @CAPS2 or be lonely. There are weight surgerys but those can rack up to thousands of dollars. And yes weight loss surgery does have effects such as death. So come on @LOCATION1 its your decison and remember the most important part of this letter which is between liveing healthy and young or dieing unhealthy and suffer. Its your choice @LOCATION1 decide.

Human Score: 9
Category: High

Calibration Example 4

Essay:
Dear to @CAPS1 this @MONTH1 concern, Computers do a whole lot now of days. You can play games, do homework, socialize but don't you think there are better things than that. Such as exercising, enjoying the beauty of nature, and most importantly interacting with family and friends. These are all the things that computers take away from people. Once you get onto a computer you never want to get off. If you look at it, it doesn't take much work and energy to use a computer. So if you eat and use the computer all day your not really burning any calories therefore you will gain weight. Computers make people feel lazy sometimes therefore they spend less time exercising. That is not good for your health at all. Exercising gives you energy and is good for you. Have you ever looked out the window and saw how beautiful nature is? When your on the computer chit-chatting with people and playing online friends do you think about what your missing. Everytime I use the computer I wish I could be outside playing and enjoying nature. Trees, flowers, plants, grass and lots of other things are what make up the earth, but some people don't apreciate those things. So next time your on the computer think about that. While your on the computer wasting time there is another homeless child wandering maybe looking for their family. Would you like to be that child who doesnt have a family or any type of friends? Lots of people think of their life without a family but it can happen anyday. So I believe instead of wasting time on the computer we should go and interact with family and friends. Even if its just having a conversation do it, maybe it can show them that you really care. In conclusion, I think that computers are a waste of time. I understand how people say it is used to comunicate with people but back then they didnt have computers and they communicated so we can to. Computes make you spend less time exercising, keeps you from enjoying nature and lastly interacting with family and friends. You won't go wrong if you listen to someone who uses a computer everyday.

Human Score: 8
Category: Medium

Calibration Example 5

Essay:
Dear @ORGANIZATION1, @DATE1, everywhere you look technology is being exercised and it is beneficial to many aspects in our lives @DATE1. Many engineers strive to improve on technologic devices popularity, while others use it in communicate or relax. study conducted by @ORGANIZATION2 university, the computer is the most largely operated machine. The computer positively contributes to our education, economy, and entertainment. As i mentioned before the computer is beneficial to our education. An example of this is the school i attend, middle school. Here at we have over @NUM1 computers in use throughout the school day. These computers help the students complete research papers, typed assignments and other teacher requirement papers. By using the computer to complete research papers students save hours of scanning through books in the library and money on reading books. In addition, computers teachers in organizing files and entering grades online so students can check their. This is beneficial considering the amount of and assignments graded each week. Moreover, a computer called the "parent portal" allows the students to stay connected with school events that would not be mentioned otherwise in all, computer are way of. Besides education computers touch upon our economy as well. Now, due to the wide variety of computer selection, a computer is affordable, starting at prices as low as sixty dollars! This is a positive aspect of the computer because currently the has been enduring the economy since the depression in the. Consequently, the reason has made families start to cut many useful technologe devices out of the. However, since the price of computers decreased purchase have stimulating. Also, the computer has mainly improved methods of. Instead of listening to a cd player you can download listen to while chatting online with friends. This is very helpful for last-minute plan changes, because for those who do not own a telephone, communication @MONTH1 be, negatively affecting your time of entertainment. In addition, children can use internet in order to play games to take that mind off of a hard day at school, or an adult's rough work computersin producing the you watch at home on the couch and the videogame you ordered off of ebay. From facebook and myspace, to and "gone with the wind." Computers create a relaxing entertainment opportunity.

Human Score: 11
Category: High

Calibration Example 6

Essay:
Dear local newspaper I think that usieng computers help people becuse if we did not have computers we would not now ehey thing about eneyone or eneything like all of the @CAPS1 I would not now eneything about them but with computers I know alot about them and there lives like @CAPS2 @CAPS3 @CAPS4 got shot in the back of the head and. @CAPS4 got shot to and I know alot about the @ORGANIZATION1 there white people that to fear in to black people and the same with the wars like world @NUM1 and world @NUM2 and the @CAPS5 and @PERSON1 and the @CAPS6 war there was like plain spy palin flying across @LOCATION1 and they shot him down becuse we were trying to see if thay had eney nuculer bombs offer there. And the same with google and yahoo with google you can type in eneything and you will get a answer and most liked a corect answer yahoo and google is great for some worke and products end studying becuse you then you do to and that I think that computer are good.

Human Score: 6
Category: Medium


Now evaluate the following essay.

Essay:
Hello, I decided to write in to the paper on the topic of computers, and how they benefit society. Comuters are powerful machines, and can be used completing otherwise menial and boring tasks. They benefit people in many ways, like they are very useful in buissness, helpful in education, and connect friends and family together. Computers are uselful in buissness and are an extremely important tool in a common workplace today, and make work get done much more efficiently than if they didn't have computers. One reason Computers are so useful in the workplace is because computers can storee far more data that can be put on paper. Also, they can do jobs and processes very quickly, which is important in the workplace. They can also be used for sending important information quickly and without much trouble. These are all valid reasons comuters are beneficial in buissness, and help things get done. Computers are important today's schools and educational programs becasue they can help students work in a more efficient fashion. "@PERCENT1 of all surveyed students said they would rather type a paper for school than write on by hand, and shows that they value them in their education." said @PERSON2, a professor at @ORGANIZATION1. This shows that Computers are important to students, and are used their benefit. In addition to students writing papers, computers are being used by teachers and school systems for grading, attendance records, and more. The teachers at my school are using @CAPS1 @CAPS2, pieces of hardware that are directly connected to computers, and can be used instead of white @CAPS2, and I see that students are getting more involved in class, and focused, because this computer technology is being used. All of these @CAPS3 are reasons computers are helpful in educational proceeses, and should continue to be used. Many people want to be able talk to there friends and family when they are bored, and because of computers and social networking websites, and instant messaging programs, this is made much easier. "@PERCENT2 of teens have at least one sacial networking site they visit on a regular basis." said @PERSON1, a phycologist, who speciaizes in teens, This shows that people use these sites, and that they like them. Families that are separated because one @MONTH1 have moved out of the house recently might want to communicate with one another, and because of computers, they can. There are multiple ways that they could use their computers to keep in touch, like instant messaging systems mentioned before. Being able to communicate with one another makes theses people happy, and benefits society. Overall, being able to communicate through computers is an enjoyable thing for many people, and is important to society today. To conclude, computers contribute to society in ways that make it much better for everyone. Whether it's through helping buissnesses being more efficient, giving students the ability to work faster, and in a way they prefer, or if it's helping people stay in touch, computers are always benefiting society. These machines hardly ever slow people more thant manually doing the work would, and the positive influence they have far outweighs the bad they do.

Instructions:
1. Predict the final score between 2 and 12.
2. Predict the category: Low, Medium, or High.
3. Explain your reasoning.

Return your answer in this format:

Final Score:
Category:
Reasoning:

In [19]:
def build_prompt(essay_text):
    return f"""
You are an expert essay grader evaluating student essays.

{rubric_text}

Calibration Examples:
{calibration_text}

Now evaluate the following essay.

Essay:
{essay_text}

Instructions:
1. Predict the final score between 2 and 12.
2. Predict the category: Low, Medium, or High.
3. Explain your reasoning.
4. Base your explanation only on details actually present in the essay.

Return your answer in this format:

Final Score:
Category:
Reasoning:
"""

In [20]:
demo['full_prompt'] = demo['essay'].apply(build_prompt)

In [21]:
print(demo.loc[0, 'full_prompt'])

You are an expert essay grader evaluating student essays.


Essay Prompt:
Write a letter to your local newspaper stating your opinion on the effects computers have on people and persuade readers to agree with your position.

Rubric:
1 – Undeveloped response with minimal support.
2 – Underdeveloped response with weak reasoning.
3 – Minimally developed argument with limited support.
4 – Adequate argument with some supporting details.
5 – Developed argument with clear reasoning and organization.
6 – Strong persuasive response with well-developed ideas.

Scoring rule:
Two raters assign scores from 1–6.
Final score = sum of both scores.
Final score range: 2–12.


Calibration Examples:

Calibration Example 1

Essay:
The computers are cool. Do you now I werpsite is @NUM1.com. We nede to time the lemt lo-menteno it. I love the compueters. We nede @NUM2 make a computers are grene compurers.

Human Score: 2
Category: Low

Calibration Example 2

Essay:
I think computers are good, because some people dont have phones so @CAPS1 a good way to conect with people you know, also meet new people. Second some people are going to collage when there done with high school so you could just look on the computers and find one you like and pricess, also find ways there. Third reason is ahopping if a holiday is coming up you could check online and find stuff for cheap and nice to you. You could also order it to your house online if you dont got alot of time to go shopping. @CAPS1 some reasons why I think online is good you could chat, find places and pricess, collages and also shop online @CAPS1 why online is good.

Human Score: 4
Category: Low

Calibration Example 3

Essay:
Dear local newspaper, I would like to speak upon the topic of the effects that computers have on people. My opion on this topic is that computers do have an effect on people. Most people while surfing the internet don't keep track of time. What I mean when I say most people lose track of time is that, they try to keep track of the time but while on the web something @MONTH1 pop that catches their intrest and at that same time there focus is on something else. Some of the other effects computers can have on people is keeping them in the house. When many people are on the web they tend not to excersise as much. When in the house on the web most people that excersise stop excersising. The reason why this occurs is because while people are on the computer chair you feel so relaxed and calm that you don't want to get up. This leads into eating unhealthy foods. Some such as chips, donuts, twinkies and etc. Some @CAPS1 do not believe that is an opinion. The reason I say this is because while watching television the other day I saw a commercial that said quote "@CAPS2 that are more active are healthier than @CAPS2 that stay on the computer all day. Most @CAPS1 do gain weight on the computer because they are not physically active. Not being physically active can lead to A) obesity @CAPS4) cloged arteries or @CAPS5) lazyness. It can lead to all three because those are the effects of being on a computer every of the day. Most @CAPS1 should be enjoying nature instead of staying on the computer. There is a lot more to life than being on the web. Some such as playing sports. Not only is playing sports fun but at the same tim it is also healthy. Would you rather live to @NUM1 or live to @NUM2. And so local newspaper that is why I am writing you this letter today. I mean would you rather have friends @CAPS2 or be lonely. There are weight surgerys but those can rack up to thousands of dollars. And yes weight loss surgery does have effects such as death. So come on @LOCATION1 its your decison and remember the most important part of this letter which is between liveing healthy and young or dieing unhealthy and suffer. Its your choice @LOCATION1 decide.

Human Score: 9
Category: High

Calibration Example 4

Essay:
Dear to @CAPS1 this @MONTH1 concern, Computers do a whole lot now of days. You can play games, do homework, socialize but don't you think there are better things than that. Such as exercising, enjoying the beauty of nature, and most importantly interacting with family and friends. These are all the things that computers take away from people. Once you get onto a computer you never want to get off. If you look at it, it doesn't take much work and energy to use a computer. So if you eat and use the computer all day your not really burning any calories therefore you will gain weight. Computers make people feel lazy sometimes therefore they spend less time exercising. That is not good for your health at all. Exercising gives you energy and is good for you. Have you ever looked out the window and saw how beautiful nature is? When your on the computer chit-chatting with people and playing online friends do you think about what your missing. Everytime I use the computer I wish I could be outside playing and enjoying nature. Trees, flowers, plants, grass and lots of other things are what make up the earth, but some people don't apreciate those things. So next time your on the computer think about that. While your on the computer wasting time there is another homeless child wandering maybe looking for their family. Would you like to be that child who doesnt have a family or any type of friends? Lots of people think of their life without a family but it can happen anyday. So I believe instead of wasting time on the computer we should go and interact with family and friends. Even if its just having a conversation do it, maybe it can show them that you really care. In conclusion, I think that computers are a waste of time. I understand how people say it is used to comunicate with people but back then they didnt have computers and they communicated so we can to. Computes make you spend less time exercising, keeps you from enjoying nature and lastly interacting with family and friends. You won't go wrong if you listen to someone who uses a computer everyday.

Human Score: 8
Category: Medium

Calibration Example 5

Essay:
Dear @ORGANIZATION1, @DATE1, everywhere you look technology is being exercised and it is beneficial to many aspects in our lives @DATE1. Many engineers strive to improve on technologic devices popularity, while others use it in communicate or relax. study conducted by @ORGANIZATION2 university, the computer is the most largely operated machine. The computer positively contributes to our education, economy, and entertainment. As i mentioned before the computer is beneficial to our education. An example of this is the school i attend, middle school. Here at we have over @NUM1 computers in use throughout the school day. These computers help the students complete research papers, typed assignments and other teacher requirement papers. By using the computer to complete research papers students save hours of scanning through books in the library and money on reading books. In addition, computers teachers in organizing files and entering grades online so students can check their. This is beneficial considering the amount of and assignments graded each week. Moreover, a computer called the "parent portal" allows the students to stay connected with school events that would not be mentioned otherwise in all, computer are way of. Besides education computers touch upon our economy as well. Now, due to the wide variety of computer selection, a computer is affordable, starting at prices as low as sixty dollars! This is a positive aspect of the computer because currently the has been enduring the economy since the depression in the. Consequently, the reason has made families start to cut many useful technologe devices out of the. However, since the price of computers decreased purchase have stimulating. Also, the computer has mainly improved methods of. Instead of listening to a cd player you can download listen to while chatting online with friends. This is very helpful for last-minute plan changes, because for those who do not own a telephone, communication @MONTH1 be, negatively affecting your time of entertainment. In addition, children can use internet in order to play games to take that mind off of a hard day at school, or an adult's rough work computersin producing the you watch at home on the couch and the videogame you ordered off of ebay. From facebook and myspace, to and "gone with the wind." Computers create a relaxing entertainment opportunity.

Human Score: 11
Category: High

Calibration Example 6

Essay:
Dear local newspaper I think that usieng computers help people becuse if we did not have computers we would not now ehey thing about eneyone or eneything like all of the @CAPS1 I would not now eneything about them but with computers I know alot about them and there lives like @CAPS2 @CAPS3 @CAPS4 got shot in the back of the head and. @CAPS4 got shot to and I know alot about the @ORGANIZATION1 there white people that to fear in to black people and the same with the wars like world @NUM1 and world @NUM2 and the @CAPS5 and @PERSON1 and the @CAPS6 war there was like plain spy palin flying across @LOCATION1 and they shot him down becuse we were trying to see if thay had eney nuculer bombs offer there. And the same with google and yahoo with google you can type in eneything and you will get a answer and most liked a corect answer yahoo and google is great for some worke and products end studying becuse you then you do to and that I think that computer are good.

Human Score: 6
Category: Medium


Now evaluate the following essay.

Essay:
Hello, I decided to write in to the paper on the topic of computers, and how they benefit society. Comuters are powerful machines, and can be used completing otherwise menial and boring tasks. They benefit people in many ways, like they are very useful in buissness, helpful in education, and connect friends and family together. Computers are uselful in buissness and are an extremely important tool in a common workplace today, and make work get done much more efficiently than if they didn't have computers. One reason Computers are so useful in the workplace is because computers can storee far more data that can be put on paper. Also, they can do jobs and processes very quickly, which is important in the workplace. They can also be used for sending important information quickly and without much trouble. These are all valid reasons comuters are beneficial in buissness, and help things get done. Computers are important today's schools and educational programs becasue they can help students work in a more efficient fashion. "@PERCENT1 of all surveyed students said they would rather type a paper for school than write on by hand, and shows that they value them in their education." said @PERSON2, a professor at @ORGANIZATION1. This shows that Computers are important to students, and are used their benefit. In addition to students writing papers, computers are being used by teachers and school systems for grading, attendance records, and more. The teachers at my school are using @CAPS1 @CAPS2, pieces of hardware that are directly connected to computers, and can be used instead of white @CAPS2, and I see that students are getting more involved in class, and focused, because this computer technology is being used. All of these @CAPS3 are reasons computers are helpful in educational proceeses, and should continue to be used. Many people want to be able talk to there friends and family when they are bored, and because of computers and social networking websites, and instant messaging programs, this is made much easier. "@PERCENT2 of teens have at least one sacial networking site they visit on a regular basis." said @PERSON1, a phycologist, who speciaizes in teens, This shows that people use these sites, and that they like them. Families that are separated because one @MONTH1 have moved out of the house recently might want to communicate with one another, and because of computers, they can. There are multiple ways that they could use their computers to keep in touch, like instant messaging systems mentioned before. Being able to communicate with one another makes theses people happy, and benefits society. Overall, being able to communicate through computers is an enjoyable thing for many people, and is important to society today. To conclude, computers contribute to society in ways that make it much better for everyone. Whether it's through helping buissnesses being more efficient, giving students the ability to work faster, and in a way they prefer, or if it's helping people stay in touch, computers are always benefiting society. These machines hardly ever slow people more thant manually doing the work would, and the positive influence they have far outweighs the bad they do.

Instructions:
1. Predict the final score between 2 and 12.
2. Predict the category: Low, Medium, or High.
3. Explain your reasoning.
4. Base your explanation only on details actually present in the essay.

Return your answer in this format:

Final Score:
Category:
Reasoning:

In [22]:
print(demo.loc[1, 'full_prompt'])

You are an expert essay grader evaluating student essays.


Essay Prompt:
Write a letter to your local newspaper stating your opinion on the effects computers have on people and persuade readers to agree with your position.

Rubric:
1 – Undeveloped response with minimal support.
2 – Underdeveloped response with weak reasoning.
3 – Minimally developed argument with limited support.
4 – Adequate argument with some supporting details.
5 – Developed argument with clear reasoning and organization.
6 – Strong persuasive response with well-developed ideas.

Scoring rule:
Two raters assign scores from 1–6.
Final score = sum of both scores.
Final score range: 2–12.


Calibration Examples:

Calibration Example 1

Essay:
The computers are cool. Do you now I werpsite is @NUM1.com. We nede to time the lemt lo-menteno it. I love the compueters. We nede @NUM2 make a computers are grene compurers.

Human Score: 2
Category: Low

Calibration Example 2

Essay:
I think computers are good, because some people dont have phones so @CAPS1 a good way to conect with people you know, also meet new people. Second some people are going to collage when there done with high school so you could just look on the computers and find one you like and pricess, also find ways there. Third reason is ahopping if a holiday is coming up you could check online and find stuff for cheap and nice to you. You could also order it to your house online if you dont got alot of time to go shopping. @CAPS1 some reasons why I think online is good you could chat, find places and pricess, collages and also shop online @CAPS1 why online is good.

Human Score: 4
Category: Low

Calibration Example 3

Essay:
Dear local newspaper, I would like to speak upon the topic of the effects that computers have on people. My opion on this topic is that computers do have an effect on people. Most people while surfing the internet don't keep track of time. What I mean when I say most people lose track of time is that, they try to keep track of the time but while on the web something @MONTH1 pop that catches their intrest and at that same time there focus is on something else. Some of the other effects computers can have on people is keeping them in the house. When many people are on the web they tend not to excersise as much. When in the house on the web most people that excersise stop excersising. The reason why this occurs is because while people are on the computer chair you feel so relaxed and calm that you don't want to get up. This leads into eating unhealthy foods. Some such as chips, donuts, twinkies and etc. Some @CAPS1 do not believe that is an opinion. The reason I say this is because while watching television the other day I saw a commercial that said quote "@CAPS2 that are more active are healthier than @CAPS2 that stay on the computer all day. Most @CAPS1 do gain weight on the computer because they are not physically active. Not being physically active can lead to A) obesity @CAPS4) cloged arteries or @CAPS5) lazyness. It can lead to all three because those are the effects of being on a computer every of the day. Most @CAPS1 should be enjoying nature instead of staying on the computer. There is a lot more to life than being on the web. Some such as playing sports. Not only is playing sports fun but at the same tim it is also healthy. Would you rather live to @NUM1 or live to @NUM2. And so local newspaper that is why I am writing you this letter today. I mean would you rather have friends @CAPS2 or be lonely. There are weight surgerys but those can rack up to thousands of dollars. And yes weight loss surgery does have effects such as death. So come on @LOCATION1 its your decison and remember the most important part of this letter which is between liveing healthy and young or dieing unhealthy and suffer. Its your choice @LOCATION1 decide.

Human Score: 9
Category: High

Calibration Example 4

Essay:
Dear to @CAPS1 this @MONTH1 concern, Computers do a whole lot now of days. You can play games, do homework, socialize but don't you think there are better things than that. Such as exercising, enjoying the beauty of nature, and most importantly interacting with family and friends. These are all the things that computers take away from people. Once you get onto a computer you never want to get off. If you look at it, it doesn't take much work and energy to use a computer. So if you eat and use the computer all day your not really burning any calories therefore you will gain weight. Computers make people feel lazy sometimes therefore they spend less time exercising. That is not good for your health at all. Exercising gives you energy and is good for you. Have you ever looked out the window and saw how beautiful nature is? When your on the computer chit-chatting with people and playing online friends do you think about what your missing. Everytime I use the computer I wish I could be outside playing and enjoying nature. Trees, flowers, plants, grass and lots of other things are what make up the earth, but some people don't apreciate those things. So next time your on the computer think about that. While your on the computer wasting time there is another homeless child wandering maybe looking for their family. Would you like to be that child who doesnt have a family or any type of friends? Lots of people think of their life without a family but it can happen anyday. So I believe instead of wasting time on the computer we should go and interact with family and friends. Even if its just having a conversation do it, maybe it can show them that you really care. In conclusion, I think that computers are a waste of time. I understand how people say it is used to comunicate with people but back then they didnt have computers and they communicated so we can to. Computes make you spend less time exercising, keeps you from enjoying nature and lastly interacting with family and friends. You won't go wrong if you listen to someone who uses a computer everyday.

Human Score: 8
Category: Medium

Calibration Example 5

Essay:
Dear @ORGANIZATION1, @DATE1, everywhere you look technology is being exercised and it is beneficial to many aspects in our lives @DATE1. Many engineers strive to improve on technologic devices popularity, while others use it in communicate or relax. study conducted by @ORGANIZATION2 university, the computer is the most largely operated machine. The computer positively contributes to our education, economy, and entertainment. As i mentioned before the computer is beneficial to our education. An example of this is the school i attend, middle school. Here at we have over @NUM1 computers in use throughout the school day. These computers help the students complete research papers, typed assignments and other teacher requirement papers. By using the computer to complete research papers students save hours of scanning through books in the library and money on reading books. In addition, computers teachers in organizing files and entering grades online so students can check their. This is beneficial considering the amount of and assignments graded each week. Moreover, a computer called the "parent portal" allows the students to stay connected with school events that would not be mentioned otherwise in all, computer are way of. Besides education computers touch upon our economy as well. Now, due to the wide variety of computer selection, a computer is affordable, starting at prices as low as sixty dollars! This is a positive aspect of the computer because currently the has been enduring the economy since the depression in the. Consequently, the reason has made families start to cut many useful technologe devices out of the. However, since the price of computers decreased purchase have stimulating. Also, the computer has mainly improved methods of. Instead of listening to a cd player you can download listen to while chatting online with friends. This is very helpful for last-minute plan changes, because for those who do not own a telephone, communication @MONTH1 be, negatively affecting your time of entertainment. In addition, children can use internet in order to play games to take that mind off of a hard day at school, or an adult's rough work computersin producing the you watch at home on the couch and the videogame you ordered off of ebay. From facebook and myspace, to and "gone with the wind." Computers create a relaxing entertainment opportunity.

Human Score: 11
Category: High

Calibration Example 6

Essay:
Dear local newspaper I think that usieng computers help people becuse if we did not have computers we would not now ehey thing about eneyone or eneything like all of the @CAPS1 I would not now eneything about them but with computers I know alot about them and there lives like @CAPS2 @CAPS3 @CAPS4 got shot in the back of the head and. @CAPS4 got shot to and I know alot about the @ORGANIZATION1 there white people that to fear in to black people and the same with the wars like world @NUM1 and world @NUM2 and the @CAPS5 and @PERSON1 and the @CAPS6 war there was like plain spy palin flying across @LOCATION1 and they shot him down becuse we were trying to see if thay had eney nuculer bombs offer there. And the same with google and yahoo with google you can type in eneything and you will get a answer and most liked a corect answer yahoo and google is great for some worke and products end studying becuse you then you do to and that I think that computer are good.

Human Score: 6
Category: Medium


Now evaluate the following essay.

Essay:
Each year the world becomes more and more advance in technology. Technology helps and benefits us all in a good positive way. Computers are apart of this positive technology and definetely benefits society. Computers help us look up places and things we never seen before and teaches us about them, too. In addition, computers have a positive impact on families and benefits them greatly. Also, they help people from adults years out of college to teenagers in high school communicate with their friends. Therefore, computers help us all in some little way and makes life easier and more fun. To begin with computers helps us expand our knowledge. It us helps us look up facts or recent news quickly. For example, just recently the @DATE1 @CAPS1 occured and they usualy go late into the night so I didn't get to see the whole competition. I could just easily go look it up on the computer to see who won which medals. computers helped me by looking up the medals quick so I woudn't have to wonder who won a medals not. Computers help us expand our knowledge all the time. They help us look up facts for report, places we want to travel to, learn about the benefits of a certain pet and the posibilities can be endless. to continue with, computers help families by bringing them closer in a way. A family member could be watching a funny on youtube or @ORGANIZATION1 and could think its so funny that they want their whole family to see it you. In addition, stores sell clothes online now so mother and daugther can sit down together and shop without leaving the house. Computers bring my family together by we rent movies from @LOCATION1 on the computer. It brings us together when choose and pick which movie to rent. Also, it brings us together to have a family movie night. As a result, these things the computer gives brings out discussion in the family and gives a good topic that everyone can relate to and talk about. Another way computers are beneficial is they bring everyone together. There are many ways communicate on the computer these days. There is facebook, twitter, email, aim, and many more. They are all different, but they have one thing in common is to bring old friends and new friends together. For instance my mom just sign on to be in facebook so she can talk to all her old friends from highschool and she found one really good friends who she hasn't seen in ages it made her really happy. Therefore, it shows that computers aren't just for bringing new people together, old ones, too.

Instructions:
1. Predict the final score between 2 and 12.
2. Predict the category: Low, Medium, or High.
3. Explain your reasoning.
4. Base your explanation only on details actually present in the essay.

Return your answer in this format:

Final Score:
Category:
Reasoning:

In [23]:
print(demo.loc[2, 'full_prompt'])

You are an expert essay grader evaluating student essays.


Essay Prompt:
Write a letter to your local newspaper stating your opinion on the effects computers have on people and persuade readers to agree with your position.

Rubric:
1 – Undeveloped response with minimal support.
2 – Underdeveloped response with weak reasoning.
3 – Minimally developed argument with limited support.
4 – Adequate argument with some supporting details.
5 – Developed argument with clear reasoning and organization.
6 – Strong persuasive response with well-developed ideas.

Scoring rule:
Two raters assign scores from 1–6.
Final score = sum of both scores.
Final score range: 2–12.


Calibration Examples:

Calibration Example 1

Essay:
The computers are cool. Do you now I werpsite is @NUM1.com. We nede to time the lemt lo-menteno it. I love the compueters. We nede @NUM2 make a computers are grene compurers.

Human Score: 2
Category: Low

Calibration Example 2

Essay:
I think computers are good, because some people dont have phones so @CAPS1 a good way to conect with people you know, also meet new people. Second some people are going to collage when there done with high school so you could just look on the computers and find one you like and pricess, also find ways there. Third reason is ahopping if a holiday is coming up you could check online and find stuff for cheap and nice to you. You could also order it to your house online if you dont got alot of time to go shopping. @CAPS1 some reasons why I think online is good you could chat, find places and pricess, collages and also shop online @CAPS1 why online is good.

Human Score: 4
Category: Low

Calibration Example 3

Essay:
Dear local newspaper, I would like to speak upon the topic of the effects that computers have on people. My opion on this topic is that computers do have an effect on people. Most people while surfing the internet don't keep track of time. What I mean when I say most people lose track of time is that, they try to keep track of the time but while on the web something @MONTH1 pop that catches their intrest and at that same time there focus is on something else. Some of the other effects computers can have on people is keeping them in the house. When many people are on the web they tend not to excersise as much. When in the house on the web most people that excersise stop excersising. The reason why this occurs is because while people are on the computer chair you feel so relaxed and calm that you don't want to get up. This leads into eating unhealthy foods. Some such as chips, donuts, twinkies and etc. Some @CAPS1 do not believe that is an opinion. The reason I say this is because while watching television the other day I saw a commercial that said quote "@CAPS2 that are more active are healthier than @CAPS2 that stay on the computer all day. Most @CAPS1 do gain weight on the computer because they are not physically active. Not being physically active can lead to A) obesity @CAPS4) cloged arteries or @CAPS5) lazyness. It can lead to all three because those are the effects of being on a computer every of the day. Most @CAPS1 should be enjoying nature instead of staying on the computer. There is a lot more to life than being on the web. Some such as playing sports. Not only is playing sports fun but at the same tim it is also healthy. Would you rather live to @NUM1 or live to @NUM2. And so local newspaper that is why I am writing you this letter today. I mean would you rather have friends @CAPS2 or be lonely. There are weight surgerys but those can rack up to thousands of dollars. And yes weight loss surgery does have effects such as death. So come on @LOCATION1 its your decison and remember the most important part of this letter which is between liveing healthy and young or dieing unhealthy and suffer. Its your choice @LOCATION1 decide.

Human Score: 9
Category: High

Calibration Example 4

Essay:
Dear to @CAPS1 this @MONTH1 concern, Computers do a whole lot now of days. You can play games, do homework, socialize but don't you think there are better things than that. Such as exercising, enjoying the beauty of nature, and most importantly interacting with family and friends. These are all the things that computers take away from people. Once you get onto a computer you never want to get off. If you look at it, it doesn't take much work and energy to use a computer. So if you eat and use the computer all day your not really burning any calories therefore you will gain weight. Computers make people feel lazy sometimes therefore they spend less time exercising. That is not good for your health at all. Exercising gives you energy and is good for you. Have you ever looked out the window and saw how beautiful nature is? When your on the computer chit-chatting with people and playing online friends do you think about what your missing. Everytime I use the computer I wish I could be outside playing and enjoying nature. Trees, flowers, plants, grass and lots of other things are what make up the earth, but some people don't apreciate those things. So next time your on the computer think about that. While your on the computer wasting time there is another homeless child wandering maybe looking for their family. Would you like to be that child who doesnt have a family or any type of friends? Lots of people think of their life without a family but it can happen anyday. So I believe instead of wasting time on the computer we should go and interact with family and friends. Even if its just having a conversation do it, maybe it can show them that you really care. In conclusion, I think that computers are a waste of time. I understand how people say it is used to comunicate with people but back then they didnt have computers and they communicated so we can to. Computes make you spend less time exercising, keeps you from enjoying nature and lastly interacting with family and friends. You won't go wrong if you listen to someone who uses a computer everyday.

Human Score: 8
Category: Medium

Calibration Example 5

Essay:
Dear @ORGANIZATION1, @DATE1, everywhere you look technology is being exercised and it is beneficial to many aspects in our lives @DATE1. Many engineers strive to improve on technologic devices popularity, while others use it in communicate or relax. study conducted by @ORGANIZATION2 university, the computer is the most largely operated machine. The computer positively contributes to our education, economy, and entertainment. As i mentioned before the computer is beneficial to our education. An example of this is the school i attend, middle school. Here at we have over @NUM1 computers in use throughout the school day. These computers help the students complete research papers, typed assignments and other teacher requirement papers. By using the computer to complete research papers students save hours of scanning through books in the library and money on reading books. In addition, computers teachers in organizing files and entering grades online so students can check their. This is beneficial considering the amount of and assignments graded each week. Moreover, a computer called the "parent portal" allows the students to stay connected with school events that would not be mentioned otherwise in all, computer are way of. Besides education computers touch upon our economy as well. Now, due to the wide variety of computer selection, a computer is affordable, starting at prices as low as sixty dollars! This is a positive aspect of the computer because currently the has been enduring the economy since the depression in the. Consequently, the reason has made families start to cut many useful technologe devices out of the. However, since the price of computers decreased purchase have stimulating. Also, the computer has mainly improved methods of. Instead of listening to a cd player you can download listen to while chatting online with friends. This is very helpful for last-minute plan changes, because for those who do not own a telephone, communication @MONTH1 be, negatively affecting your time of entertainment. In addition, children can use internet in order to play games to take that mind off of a hard day at school, or an adult's rough work computersin producing the you watch at home on the couch and the videogame you ordered off of ebay. From facebook and myspace, to and "gone with the wind." Computers create a relaxing entertainment opportunity.

Human Score: 11
Category: High

Calibration Example 6

Essay:
Dear local newspaper I think that usieng computers help people becuse if we did not have computers we would not now ehey thing about eneyone or eneything like all of the @CAPS1 I would not now eneything about them but with computers I know alot about them and there lives like @CAPS2 @CAPS3 @CAPS4 got shot in the back of the head and. @CAPS4 got shot to and I know alot about the @ORGANIZATION1 there white people that to fear in to black people and the same with the wars like world @NUM1 and world @NUM2 and the @CAPS5 and @PERSON1 and the @CAPS6 war there was like plain spy palin flying across @LOCATION1 and they shot him down becuse we were trying to see if thay had eney nuculer bombs offer there. And the same with google and yahoo with google you can type in eneything and you will get a answer and most liked a corect answer yahoo and google is great for some worke and products end studying becuse you then you do to and that I think that computer are good.

Human Score: 6
Category: Medium


Now evaluate the following essay.

Essay:
Dear local Newspaper, Computers don't take exercising, enjoying nature, and no interacting with friends and family away from you. Your family can sey time limits on the computer if they think your. Spending to much time on it. If you have time limits then people will have a certin time they go on and off of the computer. For example a child is on the computer @NUM1 and you can't get them off, time limits will stop that. The child is on a game and if the time limits are on, when your time is done the computer logs off automaticaly. That way your child can't get back on till thier next time. The computer can do many things you can play online games and chat with friends. Chating will let you talk to friends over the computer and you won't need to call them. Online games will still let you talk to your friends but you can have an avatar you can dress up and be creative with. For example an online game can let you chat make friends,

Instructions:
1. Predict the final score between 2 and 12.
2. Predict the category: Low, Medium, or High.
3. Explain your reasoning.
4. Base your explanation only on details actually present in the essay.

Return your answer in this format:

Final Score:
Category:
Reasoning:

In [24]:
print(demo.loc[3, 'full_prompt'])

You are an expert essay grader evaluating student essays.


Essay Prompt:
Write a letter to your local newspaper stating your opinion on the effects computers have on people and persuade readers to agree with your position.

Rubric:
1 – Undeveloped response with minimal support.
2 – Underdeveloped response with weak reasoning.
3 – Minimally developed argument with limited support.
4 – Adequate argument with some supporting details.
5 – Developed argument with clear reasoning and organization.
6 – Strong persuasive response with well-developed ideas.

Scoring rule:
Two raters assign scores from 1–6.
Final score = sum of both scores.
Final score range: 2–12.


Calibration Examples:

Calibration Example 1

Essay:
The computers are cool. Do you now I werpsite is @NUM1.com. We nede to time the lemt lo-menteno it. I love the compueters. We nede @NUM2 make a computers are grene compurers.

Human Score: 2
Category: Low

Calibration Example 2

Essay:
I think computers are good, because some people dont have phones so @CAPS1 a good way to conect with people you know, also meet new people. Second some people are going to collage when there done with high school so you could just look on the computers and find one you like and pricess, also find ways there. Third reason is ahopping if a holiday is coming up you could check online and find stuff for cheap and nice to you. You could also order it to your house online if you dont got alot of time to go shopping. @CAPS1 some reasons why I think online is good you could chat, find places and pricess, collages and also shop online @CAPS1 why online is good.

Human Score: 4
Category: Low

Calibration Example 3

Essay:
Dear local newspaper, I would like to speak upon the topic of the effects that computers have on people. My opion on this topic is that computers do have an effect on people. Most people while surfing the internet don't keep track of time. What I mean when I say most people lose track of time is that, they try to keep track of the time but while on the web something @MONTH1 pop that catches their intrest and at that same time there focus is on something else. Some of the other effects computers can have on people is keeping them in the house. When many people are on the web they tend not to excersise as much. When in the house on the web most people that excersise stop excersising. The reason why this occurs is because while people are on the computer chair you feel so relaxed and calm that you don't want to get up. This leads into eating unhealthy foods. Some such as chips, donuts, twinkies and etc. Some @CAPS1 do not believe that is an opinion. The reason I say this is because while watching television the other day I saw a commercial that said quote "@CAPS2 that are more active are healthier than @CAPS2 that stay on the computer all day. Most @CAPS1 do gain weight on the computer because they are not physically active. Not being physically active can lead to A) obesity @CAPS4) cloged arteries or @CAPS5) lazyness. It can lead to all three because those are the effects of being on a computer every of the day. Most @CAPS1 should be enjoying nature instead of staying on the computer. There is a lot more to life than being on the web. Some such as playing sports. Not only is playing sports fun but at the same tim it is also healthy. Would you rather live to @NUM1 or live to @NUM2. And so local newspaper that is why I am writing you this letter today. I mean would you rather have friends @CAPS2 or be lonely. There are weight surgerys but those can rack up to thousands of dollars. And yes weight loss surgery does have effects such as death. So come on @LOCATION1 its your decison and remember the most important part of this letter which is between liveing healthy and young or dieing unhealthy and suffer. Its your choice @LOCATION1 decide.

Human Score: 9
Category: High

Calibration Example 4

Essay:
Dear to @CAPS1 this @MONTH1 concern, Computers do a whole lot now of days. You can play games, do homework, socialize but don't you think there are better things than that. Such as exercising, enjoying the beauty of nature, and most importantly interacting with family and friends. These are all the things that computers take away from people. Once you get onto a computer you never want to get off. If you look at it, it doesn't take much work and energy to use a computer. So if you eat and use the computer all day your not really burning any calories therefore you will gain weight. Computers make people feel lazy sometimes therefore they spend less time exercising. That is not good for your health at all. Exercising gives you energy and is good for you. Have you ever looked out the window and saw how beautiful nature is? When your on the computer chit-chatting with people and playing online friends do you think about what your missing. Everytime I use the computer I wish I could be outside playing and enjoying nature. Trees, flowers, plants, grass and lots of other things are what make up the earth, but some people don't apreciate those things. So next time your on the computer think about that. While your on the computer wasting time there is another homeless child wandering maybe looking for their family. Would you like to be that child who doesnt have a family or any type of friends? Lots of people think of their life without a family but it can happen anyday. So I believe instead of wasting time on the computer we should go and interact with family and friends. Even if its just having a conversation do it, maybe it can show them that you really care. In conclusion, I think that computers are a waste of time. I understand how people say it is used to comunicate with people but back then they didnt have computers and they communicated so we can to. Computes make you spend less time exercising, keeps you from enjoying nature and lastly interacting with family and friends. You won't go wrong if you listen to someone who uses a computer everyday.

Human Score: 8
Category: Medium

Calibration Example 5

Essay:
Dear @ORGANIZATION1, @DATE1, everywhere you look technology is being exercised and it is beneficial to many aspects in our lives @DATE1. Many engineers strive to improve on technologic devices popularity, while others use it in communicate or relax. study conducted by @ORGANIZATION2 university, the computer is the most largely operated machine. The computer positively contributes to our education, economy, and entertainment. As i mentioned before the computer is beneficial to our education. An example of this is the school i attend, middle school. Here at we have over @NUM1 computers in use throughout the school day. These computers help the students complete research papers, typed assignments and other teacher requirement papers. By using the computer to complete research papers students save hours of scanning through books in the library and money on reading books. In addition, computers teachers in organizing files and entering grades online so students can check their. This is beneficial considering the amount of and assignments graded each week. Moreover, a computer called the "parent portal" allows the students to stay connected with school events that would not be mentioned otherwise in all, computer are way of. Besides education computers touch upon our economy as well. Now, due to the wide variety of computer selection, a computer is affordable, starting at prices as low as sixty dollars! This is a positive aspect of the computer because currently the has been enduring the economy since the depression in the. Consequently, the reason has made families start to cut many useful technologe devices out of the. However, since the price of computers decreased purchase have stimulating. Also, the computer has mainly improved methods of. Instead of listening to a cd player you can download listen to while chatting online with friends. This is very helpful for last-minute plan changes, because for those who do not own a telephone, communication @MONTH1 be, negatively affecting your time of entertainment. In addition, children can use internet in order to play games to take that mind off of a hard day at school, or an adult's rough work computersin producing the you watch at home on the couch and the videogame you ordered off of ebay. From facebook and myspace, to and "gone with the wind." Computers create a relaxing entertainment opportunity.

Human Score: 11
Category: High

Calibration Example 6

Essay:
Dear local newspaper I think that usieng computers help people becuse if we did not have computers we would not now ehey thing about eneyone or eneything like all of the @CAPS1 I would not now eneything about them but with computers I know alot about them and there lives like @CAPS2 @CAPS3 @CAPS4 got shot in the back of the head and. @CAPS4 got shot to and I know alot about the @ORGANIZATION1 there white people that to fear in to black people and the same with the wars like world @NUM1 and world @NUM2 and the @CAPS5 and @PERSON1 and the @CAPS6 war there was like plain spy palin flying across @LOCATION1 and they shot him down becuse we were trying to see if thay had eney nuculer bombs offer there. And the same with google and yahoo with google you can type in eneything and you will get a answer and most liked a corect answer yahoo and google is great for some worke and products end studying becuse you then you do to and that I think that computer are good.

Human Score: 6
Category: Medium


Now evaluate the following essay.

Essay:
Wouldn't you agree that computers have a great affect on people. The three reason why they have a good affect on people is because, it gives you good typing skills, its educational, and it helps you out with alot of things. The first reason why computers have a good affect on people is because computers help your typing skills. If you have a computer you will soon learn that your typing skills get very good. Each time you use the computer your hands ajust to the keys on the computer. Say if there is someone that wants to work with computers when they get older, well if they practice their typing on their computers at home they will be eligible for the job working with computers. Also computers could be good for the hearing impared. If the hearing impared use to the computers then they can get a @CAPS1 or @CAPS2 and chat with people online. This would be useful to them because since they could not hear what people say they can read what people say through the internet. Another reason why computers have a good affect on people is because they are very educational. In my opinion, computers are very educational because there are alot of websites that teach you facts about different places. For example, what food people eat in different countrys, or where that country is. A website that is the best for finding out accurate facts is www.Ask.com. Ask.com is the best website because it tells you what ever you want to know in a matter of seconds. Computers are also educational when it comes to school projects because of these amazing websites. The last reason why computers have a affect on people is because they help you with alot of things. They help you with alot of things because if you want to know how far @LOCATION2 is from @LOCATION1 then you can go on your pc and find out, or say that you lost the directions to your friends house and your on your way to their house if you brought your labtop you can go on the labtap and find where her house is from your labtop. I know your probably thinking there is such thing as a gps, well if you think about it gps's can be confusing, but your computer reads it out to you. Know your probably saying in your heads why don't you text/call @CAPS3/@CAPS4 if you think about it what if your friend does not talk clearly. In conclusion, wouldn't you agree that computers do have good effects on people. My three arguments are, they help your typing skill educational. They help you with things. please take my ideas into consideration.

Instructions:
1. Predict the final score between 2 and 12.
2. Predict the category: Low, Medium, or High.
3. Explain your reasoning.
4. Base your explanation only on details actually present in the essay.

Return your answer in this format:

Final Score:
Category:
Reasoning:

In [25]:
print(demo.loc[4, 'full_prompt'])

You are an expert essay grader evaluating student essays.


Essay Prompt:
Write a letter to your local newspaper stating your opinion on the effects computers have on people and persuade readers to agree with your position.

Rubric:
1 – Undeveloped response with minimal support.
2 – Underdeveloped response with weak reasoning.
3 – Minimally developed argument with limited support.
4 – Adequate argument with some supporting details.
5 – Developed argument with clear reasoning and organization.
6 – Strong persuasive response with well-developed ideas.

Scoring rule:
Two raters assign scores from 1–6.
Final score = sum of both scores.
Final score range: 2–12.


Calibration Examples:

Calibration Example 1

Essay:
The computers are cool. Do you now I werpsite is @NUM1.com. We nede to time the lemt lo-menteno it. I love the compueters. We nede @NUM2 make a computers are grene compurers.

Human Score: 2
Category: Low

Calibration Example 2

Essay:
I think computers are good, because some people dont have phones so @CAPS1 a good way to conect with people you know, also meet new people. Second some people are going to collage when there done with high school so you could just look on the computers and find one you like and pricess, also find ways there. Third reason is ahopping if a holiday is coming up you could check online and find stuff for cheap and nice to you. You could also order it to your house online if you dont got alot of time to go shopping. @CAPS1 some reasons why I think online is good you could chat, find places and pricess, collages and also shop online @CAPS1 why online is good.

Human Score: 4
Category: Low

Calibration Example 3

Essay:
Dear local newspaper, I would like to speak upon the topic of the effects that computers have on people. My opion on this topic is that computers do have an effect on people. Most people while surfing the internet don't keep track of time. What I mean when I say most people lose track of time is that, they try to keep track of the time but while on the web something @MONTH1 pop that catches their intrest and at that same time there focus is on something else. Some of the other effects computers can have on people is keeping them in the house. When many people are on the web they tend not to excersise as much. When in the house on the web most people that excersise stop excersising. The reason why this occurs is because while people are on the computer chair you feel so relaxed and calm that you don't want to get up. This leads into eating unhealthy foods. Some such as chips, donuts, twinkies and etc. Some @CAPS1 do not believe that is an opinion. The reason I say this is because while watching television the other day I saw a commercial that said quote "@CAPS2 that are more active are healthier than @CAPS2 that stay on the computer all day. Most @CAPS1 do gain weight on the computer because they are not physically active. Not being physically active can lead to A) obesity @CAPS4) cloged arteries or @CAPS5) lazyness. It can lead to all three because those are the effects of being on a computer every of the day. Most @CAPS1 should be enjoying nature instead of staying on the computer. There is a lot more to life than being on the web. Some such as playing sports. Not only is playing sports fun but at the same tim it is also healthy. Would you rather live to @NUM1 or live to @NUM2. And so local newspaper that is why I am writing you this letter today. I mean would you rather have friends @CAPS2 or be lonely. There are weight surgerys but those can rack up to thousands of dollars. And yes weight loss surgery does have effects such as death. So come on @LOCATION1 its your decison and remember the most important part of this letter which is between liveing healthy and young or dieing unhealthy and suffer. Its your choice @LOCATION1 decide.

Human Score: 9
Category: High

Calibration Example 4

Essay:
Dear to @CAPS1 this @MONTH1 concern, Computers do a whole lot now of days. You can play games, do homework, socialize but don't you think there are better things than that. Such as exercising, enjoying the beauty of nature, and most importantly interacting with family and friends. These are all the things that computers take away from people. Once you get onto a computer you never want to get off. If you look at it, it doesn't take much work and energy to use a computer. So if you eat and use the computer all day your not really burning any calories therefore you will gain weight. Computers make people feel lazy sometimes therefore they spend less time exercising. That is not good for your health at all. Exercising gives you energy and is good for you. Have you ever looked out the window and saw how beautiful nature is? When your on the computer chit-chatting with people and playing online friends do you think about what your missing. Everytime I use the computer I wish I could be outside playing and enjoying nature. Trees, flowers, plants, grass and lots of other things are what make up the earth, but some people don't apreciate those things. So next time your on the computer think about that. While your on the computer wasting time there is another homeless child wandering maybe looking for their family. Would you like to be that child who doesnt have a family or any type of friends? Lots of people think of their life without a family but it can happen anyday. So I believe instead of wasting time on the computer we should go and interact with family and friends. Even if its just having a conversation do it, maybe it can show them that you really care. In conclusion, I think that computers are a waste of time. I understand how people say it is used to comunicate with people but back then they didnt have computers and they communicated so we can to. Computes make you spend less time exercising, keeps you from enjoying nature and lastly interacting with family and friends. You won't go wrong if you listen to someone who uses a computer everyday.

Human Score: 8
Category: Medium

Calibration Example 5

Essay:
Dear @ORGANIZATION1, @DATE1, everywhere you look technology is being exercised and it is beneficial to many aspects in our lives @DATE1. Many engineers strive to improve on technologic devices popularity, while others use it in communicate or relax. study conducted by @ORGANIZATION2 university, the computer is the most largely operated machine. The computer positively contributes to our education, economy, and entertainment. As i mentioned before the computer is beneficial to our education. An example of this is the school i attend, middle school. Here at we have over @NUM1 computers in use throughout the school day. These computers help the students complete research papers, typed assignments and other teacher requirement papers. By using the computer to complete research papers students save hours of scanning through books in the library and money on reading books. In addition, computers teachers in organizing files and entering grades online so students can check their. This is beneficial considering the amount of and assignments graded each week. Moreover, a computer called the "parent portal" allows the students to stay connected with school events that would not be mentioned otherwise in all, computer are way of. Besides education computers touch upon our economy as well. Now, due to the wide variety of computer selection, a computer is affordable, starting at prices as low as sixty dollars! This is a positive aspect of the computer because currently the has been enduring the economy since the depression in the. Consequently, the reason has made families start to cut many useful technologe devices out of the. However, since the price of computers decreased purchase have stimulating. Also, the computer has mainly improved methods of. Instead of listening to a cd player you can download listen to while chatting online with friends. This is very helpful for last-minute plan changes, because for those who do not own a telephone, communication @MONTH1 be, negatively affecting your time of entertainment. In addition, children can use internet in order to play games to take that mind off of a hard day at school, or an adult's rough work computersin producing the you watch at home on the couch and the videogame you ordered off of ebay. From facebook and myspace, to and "gone with the wind." Computers create a relaxing entertainment opportunity.

Human Score: 11
Category: High

Calibration Example 6

Essay:
Dear local newspaper I think that usieng computers help people becuse if we did not have computers we would not now ehey thing about eneyone or eneything like all of the @CAPS1 I would not now eneything about them but with computers I know alot about them and there lives like @CAPS2 @CAPS3 @CAPS4 got shot in the back of the head and. @CAPS4 got shot to and I know alot about the @ORGANIZATION1 there white people that to fear in to black people and the same with the wars like world @NUM1 and world @NUM2 and the @CAPS5 and @PERSON1 and the @CAPS6 war there was like plain spy palin flying across @LOCATION1 and they shot him down becuse we were trying to see if thay had eney nuculer bombs offer there. And the same with google and yahoo with google you can type in eneything and you will get a answer and most liked a corect answer yahoo and google is great for some worke and products end studying becuse you then you do to and that I think that computer are good.

Human Score: 6
Category: Medium


Now evaluate the following essay.

Essay:
Hello @CAPS1 @CAPS2, @CAPS3 you think computers are having a great effect on people? Well, I sure @CAPS3 think using a computer has a great effect on people. I say this because, people are probably waisting a full day on those facebook, myspace gol websites, looking up diffenitions for words, directions to places etc. If you think about it, this effect on people can ruin their eye-site, and social skills. These people are spending like @NUM1 hours tops on the computer. Staring at that @NUM2 inch little screen can damage your eye-site. This can lead you to getting glasses or possibly going blind. How would your life be without not talking to a girl/guy or even your own family? If you waist your time on those websites for example: facebook all you @CAPS3 is instant message the person. Maybe you should go out and @CAPS3 something fun with that person. What's this I hear about map it.com? Don't be lazy and waist @NUM3 minutes at your day just getting directions. Use a a real map! Also, free @LOCATION1? Come on! Use a real dictionary. So, I come to my conclusion by saying that these computers @CAPS3 have a "great effect"on people. It gives them short cuts through life.

Instructions:
1. Predict the final score between 2 and 12.
2. Predict the category: Low, Medium, or High.
3. Explain your reasoning.
4. Base your explanation only on details actually present in the essay.

Return your answer in this format:

Final Score:
Category:
Reasoning:

In [26]:
import pandas as pd
import re
from sklearn.metrics import cohen_kappa_score
from scipy.stats import pearsonr

# paste the FULL Ollama outputs here, in the same order as demo
ai_outputs = ["""Final Score: 10 Category: High Reasoning:

The essay presents a clear thesis statement that argues computers contribute to society in various ways. The writer supports their argument with specific examples from business, education, and social networking. The essay is well-organized, with each paragraph focusing on a particular aspect of computer benefits.

The writing style is clear and concise, making it easy for the reader to follow the author's train of thought. The use of statistics and quotes from experts adds credibility to the argument. The tone is persuasive, and the author effectively uses transitional phrases to connect ideas between paragraphs.

While there may be minor errors in grammar or punctuation, they do not significantly detract from the overall quality of the essay. The writer demonstrates a strong understanding of the topic and presents their ideas in a logical and coherent manner.

In comparison to the calibration examples, I would place this essay in the High category (Category: 9-12). It exhibits strong persuasive writing skills, clear organization, and effective use of supporting details.
"""
,

    """Final Score: 8 Category: Medium

Here's why I think so:

The essay presents a clear and positive argument about the benefits of computers. The writer discusses how computers help people learn new things, bring families together, and facilitate communication.
The essay is well-organized, with three main points that are clearly developed and supported by examples.
The writing is straightforward and easy to understand, with no major grammatical or spelling errors.
However, the essay may benefit from a few additional supporting details or specific examples to further illustrate its points. Additionally, some of the sentences could be more concise and varied in structure.
Overall, I think this is a solid essay that effectively presents the benefits of computers and their impact on society. With some minor revisions, it could be even stronger!
"""
,
              """Final Score: 6 Category: Medium Reasoning:

The essay presents a moderate argument about computers not taking exercising, enjoying nature, and interacting with friends and family away from people. The writer suggests that setting time limits on computer use can prevent excessive usage and encourage other activities. They also mention the benefits of computers, such as playing online games and chatting with friends.

The essay is well-organized, with a clear structure and concise sentences. However, it lacks depth and supporting details to develop its points further. The writer relies mainly on general statements and examples that are not particularly specific or compelling.

Overall, I think this is a solid but unremarkable essay that could be strengthened by adding more substance and evidence to support its arguments."""
,
"""Final Score: 8 Category: Medium Reasoning:

The essay presents a moderate argument about computers having a positive impact on people. The writer suggests that computers improve typing skills, are educational, and help with various tasks. They provide some specific examples to support their claims, such as using the internet for school projects or finding directions.

While the essay has some strengths, it also lacks depth and supporting details to develop its points further. The writer relies heavily on general statements and lacks concrete evidence to back up their arguments. Additionally, the transitions between paragraphs are not smooth, which disrupts the flow of the essay.

Overall, I think this is a solid but unremarkable essay that could be strengthened by adding more substance and evidence to support its arguments."""
  , """Final Score: 8 Category: Medium Reasoning:

The essay presents a moderate argument about computers having a negative impact on people. The writer suggests that excessive computer use can lead to poor eye health, social isolation, and laziness. They provide some specific examples, such as using map it.com or relying on instant messaging instead of face-to-face interactions.

While the essay has some strengths, such as its clear structure and concise language, it also lacks depth and supporting details to develop its points further. The writer relies heavily on general statements and lacks concrete evidence to back up their arguments. Additionally, the transitions between paragraphs are not smooth, which disrupts the flow of the essay.

Overall, I think this is a solid but unremarkable essay that could be strengthened by adding more substance and evidence to support its arguments."""
    # add the rest of your Ollama outputs here for demo.loc[2], demo.loc[3], demo.loc[4]
]

def extract_score(text):
    match = re.search(r"Final Score:\s*(\d+)", text)
    return int(match.group(1)) if match else None

def extract_category(text):
    match = re.search(r"Category:\s*([A-Za-z]+)", text)
    return match.group(1) if match else None

results_df = demo[['essay_id', 'domain1_score']].copy().reset_index(drop=True)
results_df = results_df.iloc[:len(ai_outputs)].copy()

results_df['raw_output'] = ai_outputs
results_df['predicted_score'] = results_df['raw_output'].apply(extract_score)
results_df['predicted_category'] = results_df['raw_output'].apply(extract_category)

results_df = results_df.rename(columns={'domain1_score': 'human_score'})

print(results_df[['essay_id', 'human_score', 'predicted_score', 'predicted_category']])

   essay_id  human_score  predicted_score predicted_category
0        72           10               10               High
1       950           10                8             Medium
2       841            7                6             Medium
3      1710            9                8             Medium
4       808            7                8             Medium

In [27]:
clean_df = results_df.dropna(subset=['predicted_score']).copy()

qwk = cohen_kappa_score(
    clean_df['human_score'],
    clean_df['predicted_score'],
    weights='quadratic'
)

pcc, _ = pearsonr(
    clean_df['human_score'],
    clean_df['predicted_score']
)

print("QWK:", qwk)
print("PCC:", pcc)

QWK: 0.631578947368421
PCC: 0.6993786061802352

In [28]:
comparison_table = results_df[['essay_id', 'human_score', 'predicted_score', 'predicted_category', 'raw_output']]
comparison_table

,essay_id,human_score,predicted_score,predicted_category,raw_output
0,72,10,10,High,Final Score: 10 Category: High Reasoning:\n\nT...
1,950,10,8,Medium,Final Score: 8 Category: Medium\n\nHere's why ...
2,841,7,6,Medium,Final Score: 6 Category: Medium Reasoning:\n\n...
3,1710,9,8,Medium,Final Score: 8 Category: Medium Reasoning:\n\n...
4,808,7,8,Medium,Final Score: 8 Category: Medium Reasoning:\n\n...


---
## TRIAL TWO (Calibration once in the beginning)

In [29]:
rubric_text = """
Essay Prompt:
Write a letter to your local newspaper stating your opinion on the effects computers have on people and persuade readers to agree with your position.

Rubric:
1 – Undeveloped response with minimal support.
2 – Underdeveloped response with weak reasoning.
3 – Minimally developed argument with limited support.
4 – Adequate argument with some supporting details.
5 – Developed argument with clear reasoning and organization.
6 – Strong persuasive response with well-developed ideas.

Scoring rule:
Two raters assign scores from 1–6.
Final score = sum of both scores.
Final score range: 2–12.
"""

def format_calibration_examples(calibration_df):
    examples = []
    for i, row in enumerate(calibration_df.itertuples(index=False), start=1):
        examples.append(f"""
Calibration Example {i}

Essay ID: {row.essay_id}

Essay:
{row.essay}

Human Score: {row.domain1_score}
Category: {row.score_category}
""")
    return "\n".join(examples)

calibration_text = format_calibration_examples(calibration)

calibration_prompt = f"""
You are an expert essay grader evaluating student essays.

{rubric_text}

Use the following calibration examples to learn the expected scoring standard.

{calibration_text}

Important instructions:
- Use the rubric and calibration examples as the scoring standard for future essays.
- When grading future essays, predict one final score from 2 to 12.
- Also assign a category:
  Low = score 2–5
  Medium = score 6–8
  High = score 9–12
- Base your reasoning only on what is actually written in the essay.

Reply only with:
Calibration received.
"""

print(calibration_prompt)

You are an expert essay grader evaluating student essays.


Essay Prompt:
Write a letter to your local newspaper stating your opinion on the effects computers have on people and persuade readers to agree with your position.

Rubric:
1 – Undeveloped response with minimal support.
2 – Underdeveloped response with weak reasoning.
3 – Minimally developed argument with limited support.
4 – Adequate argument with some supporting details.
5 – Developed argument with clear reasoning and organization.
6 – Strong persuasive response with well-developed ideas.

Scoring rule:
Two raters assign scores from 1–6.
Final score = sum of both scores.
Final score range: 2–12.


Use the following calibration examples to learn the expected scoring standard.


Calibration Example 1

Essay ID: 1592

Essay:
The computers are cool. Do you now I werpsite is @NUM1.com. We nede to time the lemt lo-menteno it. I love the compueters. We nede @NUM2 make a computers are grene compurers.

Human Score: 2
Category: Low


Calibration Example 2

Essay ID: 995

Essay:
I think computers are good, because some people dont have phones so @CAPS1 a good way to conect with people you know, also meet new people. Second some people are going to collage when there done with high school so you could just look on the computers and find one you like and pricess, also find ways there. Third reason is ahopping if a holiday is coming up you could check online and find stuff for cheap and nice to you. You could also order it to your house online if you dont got alot of time to go shopping. @CAPS1 some reasons why I think online is good you could chat, find places and pricess, collages and also shop online @CAPS1 why online is good.

Human Score: 4
Category: Low


Calibration Example 3

Essay ID: 686

Essay:
Dear local newspaper, I would like to speak upon the topic of the effects that computers have on people. My opion on this topic is that computers do have an effect on people. Most people while surfing the internet don't keep track of time. What I mean when I say most people lose track of time is that, they try to keep track of the time but while on the web something @MONTH1 pop that catches their intrest and at that same time there focus is on something else. Some of the other effects computers can have on people is keeping them in the house. When many people are on the web they tend not to excersise as much. When in the house on the web most people that excersise stop excersising. The reason why this occurs is because while people are on the computer chair you feel so relaxed and calm that you don't want to get up. This leads into eating unhealthy foods. Some such as chips, donuts, twinkies and etc. Some @CAPS1 do not believe that is an opinion. The reason I say this is because while watching television the other day I saw a commercial that said quote "@CAPS2 that are more active are healthier than @CAPS2 that stay on the computer all day. Most @CAPS1 do gain weight on the computer because they are not physically active. Not being physically active can lead to A) obesity @CAPS4) cloged arteries or @CAPS5) lazyness. It can lead to all three because those are the effects of being on a computer every of the day. Most @CAPS1 should be enjoying nature instead of staying on the computer. There is a lot more to life than being on the web. Some such as playing sports. Not only is playing sports fun but at the same tim it is also healthy. Would you rather live to @NUM1 or live to @NUM2. And so local newspaper that is why I am writing you this letter today. I mean would you rather have friends @CAPS2 or be lonely. There are weight surgerys but those can rack up to thousands of dollars. And yes weight loss surgery does have effects such as death. So come on @LOCATION1 its your decison and remember the most important part of this letter which is between liveing healthy and young or dieing unhealthy and suffer. Its your choice @LOCATION1 decide.

Human Score: 9
Category: High


Calibration Example 4

Essay ID: 1572

Essay:
Dear to @CAPS1 this @MONTH1 concern, Computers do a whole lot now of days. You can play games, do homework, socialize but don't you think there are better things than that. Such as exercising, enjoying the beauty of nature, and most importantly interacting with family and friends. These are all the things that computers take away from people. Once you get onto a computer you never want to get off. If you look at it, it doesn't take much work and energy to use a computer. So if you eat and use the computer all day your not really burning any calories therefore you will gain weight. Computers make people feel lazy sometimes therefore they spend less time exercising. That is not good for your health at all. Exercising gives you energy and is good for you. Have you ever looked out the window and saw how beautiful nature is? When your on the computer chit-chatting with people and playing online friends do you think about what your missing. Everytime I use the computer I wish I could be outside playing and enjoying nature. Trees, flowers, plants, grass and lots of other things are what make up the earth, but some people don't apreciate those things. So next time your on the computer think about that. While your on the computer wasting time there is another homeless child wandering maybe looking for their family. Would you like to be that child who doesnt have a family or any type of friends? Lots of people think of their life without a family but it can happen anyday. So I believe instead of wasting time on the computer we should go and interact with family and friends. Even if its just having a conversation do it, maybe it can show them that you really care. In conclusion, I think that computers are a waste of time. I understand how people say it is used to comunicate with people but back then they didnt have computers and they communicated so we can to. Computes make you spend less time exercising, keeps you from enjoying nature and lastly interacting with family and friends. You won't go wrong if you listen to someone who uses a computer everyday.

Human Score: 8
Category: Medium


Calibration Example 5

Essay ID: 1567

Essay:
Dear @ORGANIZATION1, @DATE1, everywhere you look technology is being exercised and it is beneficial to many aspects in our lives @DATE1. Many engineers strive to improve on technologic devices popularity, while others use it in communicate or relax. study conducted by @ORGANIZATION2 university, the computer is the most largely operated machine. The computer positively contributes to our education, economy, and entertainment. As i mentioned before the computer is beneficial to our education. An example of this is the school i attend, middle school. Here at we have over @NUM1 computers in use throughout the school day. These computers help the students complete research papers, typed assignments and other teacher requirement papers. By using the computer to complete research papers students save hours of scanning through books in the library and money on reading books. In addition, computers teachers in organizing files and entering grades online so students can check their. This is beneficial considering the amount of and assignments graded each week. Moreover, a computer called the "parent portal" allows the students to stay connected with school events that would not be mentioned otherwise in all, computer are way of. Besides education computers touch upon our economy as well. Now, due to the wide variety of computer selection, a computer is affordable, starting at prices as low as sixty dollars! This is a positive aspect of the computer because currently the has been enduring the economy since the depression in the. Consequently, the reason has made families start to cut many useful technologe devices out of the. However, since the price of computers decreased purchase have stimulating. Also, the computer has mainly improved methods of. Instead of listening to a cd player you can download listen to while chatting online with friends. This is very helpful for last-minute plan changes, because for those who do not own a telephone, communication @MONTH1 be, negatively affecting your time of entertainment. In addition, children can use internet in order to play games to take that mind off of a hard day at school, or an adult's rough work computersin producing the you watch at home on the couch and the videogame you ordered off of ebay. From facebook and myspace, to and "gone with the wind." Computers create a relaxing entertainment opportunity.

Human Score: 11
Category: High


Calibration Example 6

Essay ID: 146

Essay:
Dear local newspaper I think that usieng computers help people becuse if we did not have computers we would not now ehey thing about eneyone or eneything like all of the @CAPS1 I would not now eneything about them but with computers I know alot about them and there lives like @CAPS2 @CAPS3 @CAPS4 got shot in the back of the head and. @CAPS4 got shot to and I know alot about the @ORGANIZATION1 there white people that to fear in to black people and the same with the wars like world @NUM1 and world @NUM2 and the @CAPS5 and @PERSON1 and the @CAPS6 war there was like plain spy palin flying across @LOCATION1 and they shot him down becuse we were trying to see if thay had eney nuculer bombs offer there. And the same with google and yahoo with google you can type in eneything and you will get a answer and most liked a corect answer yahoo and google is great for some worke and products end studying becuse you then you do to and that I think that computer are good.

Human Score: 6
Category: Medium


Important instructions:
- Use the rubric and calibration examples as the scoring standard for future essays.
- When grading future essays, predict one final score from 2 to 12.
- Also assign a category:
  Low = score 2–5
  Medium = score 6–8
  High = score 9–12
- Base your reasoning only on what is actually written in the essay.

Reply only with:
Calibration received.

In [30]:
def build_test_prompt(essay_id, essay_text):
    return f"""
Now evaluate the following essay.

Essay ID: {essay_id}

Essay:
{essay_text}

Instructions:
1. Predict the final score between 2 and 12.
2. Predict the category: Low, Medium, or High.
3. Explain your reasoning briefly.
4. Base your explanation only on details actually present in the essay.

Return your answer exactly in this format:

Essay ID: {essay_id}
Final Score: <number>
Category: <Low/Medium/High>
Reasoning: <your explanation>
"""

**table with essays and scores to compare them later to ai:**

In [33]:
test_df = test_pool.sample(30, random_state=42).reset_index(drop=True).copy()
test_df = test_df.reset_index(drop=True).copy()

test_df["test_prompt"] = test_df.apply(
    lambda row: build_test_prompt(row["essay_id"], row["essay"]),
    axis=1
)

test_df[["essay_id", "domain1_score", "score_category"]]

NameError: name 'test_pool' is not defined

In [ ]:
print(test_df.loc[0, "test_prompt"])

In [ ]:
print(test_df.loc[1, "test_prompt"])

In [ ]:
print(test_df.loc[2, "test_prompt"])

In [ ]:
print(test_df.loc[3, "test_prompt"])

In [ ]:
print(test_df.loc[4, "test_prompt"])

# **FINAL**

In [ ]:
import pandas as pd

# Load dataset
df = pd.read_csv("training_set_rel3.tsv", sep="\t", encoding="latin1")

# Keep essay set 1
set1 = df[df["essay_set"] == 1].copy()
set1 = set1[["essay_id", "essay", "domain1_score"]].copy()

# Clean essay text
set1["essay"] = set1["essay"].astype(str).str.replace("\n", " ", regex=False).str.strip()

# Create score category
def categorize(score):
    if score <= 5:
        return "Low"
    elif score <= 8:
        return "Medium"
    else:
        return "High"

set1["score_category"] = set1["domain1_score"].apply(categorize)

# Calibration set
cal_low = set1[set1["score_category"] == "Low"].sample(2, random_state=42)
cal_med = set1[set1["score_category"] == "Medium"].sample(2, random_state=42)
cal_high = set1[set1["score_category"] == "High"].sample(2, random_state=42)

calibration = pd.concat([cal_low, cal_med, cal_high]).sample(frac=1, random_state=42).copy()

# Remove calibration essays from testing pool
test_pool = set1[~set1["essay_id"].isin(calibration["essay_id"])].copy()

# Test essays
test_df = test_pool.sample(5, random_state=42).reset_index(drop=True).copy()

print("Calibration IDs:", calibration["essay_id"].tolist())
print("Test IDs:", test_df["essay_id"].tolist())

# Safety check
overlap = set(calibration["essay_id"]).intersection(set(test_df["essay_id"]))
print("Overlap:", overlap)

In [ ]:
rubric_text = """
Essay Prompt:
Write a letter to your local newspaper stating your opinion on the effects computers have on people and persuade readers to agree with your position.

Rubric:
1 – Undeveloped response with minimal support.
2 – Underdeveloped response with weak reasoning.
3 – Minimally developed argument with limited support.
4 – Adequate argument with some supporting details.
5 – Developed argument with clear reasoning and organization.
6 – Strong persuasive response with well-developed ideas.

Scoring rule:
Two raters assign scores from 1–6.
Final score = sum of both scores.
Final score range: 2–12.
"""

def format_calibration_examples(calibration_df):
    examples = []
    for i, row in enumerate(calibration_df.itertuples(index=False), start=1):
        examples.append(f"""
Calibration Example {i}

Essay ID: {row.essay_id}

Essay:
{row.essay}

Human Score: {row.domain1_score}
Category: {row.score_category}
""")
    return "\n".join(examples)

calibration_text = format_calibration_examples(calibration)

calibration_prompt = f"""
You are an expert essay grader evaluating student essays.

{rubric_text}

Use the following calibration examples to learn the expected scoring standard.

{calibration_text}

Important instructions:
- Use the rubric and calibration examples as the scoring standard for future essays.
- When grading future essays, predict one final score from 2 to 12.
- Also assign a category:
  Low = score 2–5
  Medium = score 6–8
  High = score 9–12
- Base your reasoning only on what is actually written in the essay.

Reply only with:
Calibration received.
"""

print(calibration_prompt)

In [ ]:
def build_test_prompt(essay_id, essay_text):
    return f"""
Now evaluate the following essay.

Essay ID: {essay_id}

Essay:
{essay_text}

Instructions:
1. Predict the final score between 2 and 12.
2. Predict the category: Low, Medium, or High.
3. Explain your reasoning briefly.
4. Base your explanation only on details actually present in the essay.

Return your answer exactly in this format:

Essay ID: {essay_id}
Final Score: <number>
Category: <Low/Medium/High>
Reasoning: <your explanation>
"""

tracking table

In [ ]:
tracking_df = test_df[[
    "essay_id",
    "essay",
    "domain1_score",
    "score_category"
]].copy()

tracking_df = tracking_df.rename(columns={
    "domain1_score": "human_score",
    "score_category": "human_category"
})

tracking_df["prompt"] = tracking_df.apply(
    lambda row: build_test_prompt(row["essay_id"], row["essay"]),
    axis=1
)

tracking_df["ai_raw_response"] = ""
tracking_df["ai_score"] = None
tracking_df["ai_category"] = ""

tracking_df[["essay_id", "human_score", "human_category"]]

    essay_id  human_score human_category
0        982            8         Medium
1        277            9           High
2        415            7         Medium
3        970           11           High
4        523           10           High
5       1467           10           High
6       1094            8         Medium
7        348            8         Medium
8       1059            8         Medium
9       1197            8         Medium
10      1288           10           High
11       634            5            Low
12      1183            8         Medium
13      1578            9           High
14      1303            7         Medium

In [ ]:
print(tracking_df.loc[0, "prompt"])
print(tracking_df.loc[1, "prompt"])
print(tracking_df.loc[2, "prompt"])
print(tracking_df.loc[3, "prompt"])
print(tracking_df.loc[4, "prompt"])

In [ ]:
# ============================
# 6) CREATE MASTER TRACKING DF
# ============================

tracking_df = test_df[[
    "essay_id",
    "essay",
    "domain1_score",
    "score_category"
]].copy()

tracking_df = tracking_df.rename(columns={
    "domain1_score": "human_score",
    "score_category": "human_category"
})

tracking_df["prompt"] = tracking_df.apply(
    lambda row: build_test_prompt(row["essay_id"], row["essay"]),
    axis=1
)

# Columns to paste Ollama outputs into later
tracking_df["ai_raw_response"] = ""
tracking_df["ai_score"] = pd.NA
tracking_df["ai_category"] = pd.NA
tracking_df["score_diff"] = pd.NA
tracking_df["abs_error"] = pd.NA

print("\n===== TRACKING TABLE =====")
print(tracking_df[["essay_id", "human_score", "human_category"]])


# ========================================
# 7) DISPLAY THE TEST PROMPTS ONE BY ONE
# ========================================

print("\n===== TEST PROMPT 0 =====")
print(tracking_df.loc[0, "prompt"])

print("\n===== TEST PROMPT 1 =====")
print(tracking_df.loc[1, "prompt"])

print("\n===== TEST PROMPT 2 =====")
print(tracking_df.loc[2, "prompt"])

print("\n===== TEST PROMPT 3 =====")
print(tracking_df.loc[3, "prompt"])

print("\n===== TEST PROMPT 4 =====")
print(tracking_df.loc[4, "prompt"])


# ======================================================
# 8) AFTER TESTING IN OLLAMA, PASTE RAW RESPONSES BELOW
# ======================================================
# Replace the text inside the triple quotes with the actual Ollama outputs.
# Keep the same row numbers aligned with the prompt you tested.

tracking_df.loc[0, "ai_raw_response"] = "Essay ID: 66 Final Score: 8 Category: Medium Reasoning: The essay presents a clear and coherent argument on the benefits of using computers in everyday life. The writer provides specific examples, such as communicating with people across distances, conducting research, and completing homework tasks more efficiently. The essay also acknowledges the emotional impact of technology, citing an example of reconnection between two family members. While the writing is not exceptionally polished or sophisticated, the ideas are well-organized and easy to follow. Overall, the essay demonstrates a solid understanding of the topic and presents a persuasive case for the advantages of computer use."

tracking_df.loc[1, "ai_raw_response"] = "Essay ID: 946 Final Score: 10 Category: High Reasoning: The essay presents a well-structured and persuasive argument against the excessive use of computers. The writer uses personal anecdotes to illustrate the negative consequences of computer addiction, including decreased physical activity, neglect of family relationships, and a lack of enjoyment in life. The examples provided are specific, relatable, and effectively convey the writer's point. The essay also demonstrates an understanding of the psychological impact of computer use, highlighting the importance of human connection and experiences over screen time. Overall, the writing is clear, concise, and well-organized, making it a strong persuasive piece that effectively argues against the misuse of computers."

tracking_df.loc[2, "ai_raw_response"] = """
Essay ID: 837
Final Score: 6
Category: Low
Reasoning: The essay lacks a clear and cohesive structure, with the writer jumping abruptly between different topics and ideas. While the writer attempts to highlight the benefits of computers, such as language learning and video chatting, these points are not fully developed or supported by evidence. Additionally, the writing is informal and lacks polish, with frequent use of colloquialisms ("Dear @ORGANIZATION1") and poor sentence structure ("And now you are probably asking..."). The essay also includes unnecessary details, such as the cost of Skype calls, which do not contribute to the overall argument. Overall, the essay requires significant improvement in terms of organization, clarity, and writing quality.
"""


tracking_df.loc[3, "ai_raw_response"] = "Essay ID: 1710 Final Score: 8 Category: Medium Reasoning: The essay presents a clear and organized argument on the positive effects of computers on people. The writer provides three main reasons why computers have a good affect on people, including improved typing skills, educational value, and assistance with various tasks. While the writing is not exceptional in terms of grammar, syntax, or vocabulary, it is generally easy to follow and understand. The essay also demonstrates some thoughtfulness, such as highlighting the potential benefits for individuals with hearing impairments. However, the writing could benefit from more development and support of ideas, as well as more attention to sentence structure and clarity. Overall, the essay shows promise but requires refinement in certain areas."


tracking_df.loc[4, "ai_raw_response"] = "Essay ID: 804 Final Score: 9 Category: High Reasoning: The essay presents a strong and persuasive argument against the negative effects of computers on people. The writer provides three main points highlighting the problems caused by excessive computer use, including health risks, social isolation, and online safety concerns. The writing is clear, concise, and easy to follow, with specific examples and anecdotes that support the author's claims. Additionally, the essay demonstrates a good understanding of the topic and presents a logical argument against the misuse of computers. While there may be some minor errors in grammar or syntax, they do not detract from the overall impact of the essay. Overall, this is a well-written and effective persuasive piece that presents a compelling case against the negative effects of computer addiction."


# ============================================
# 9) EXTRACT AI SCORE AND CATEGORY AUTOMATICALLY
# ============================================
import re
def extract_score(text):
    match = re.search(r"Final Score:\s*(\d+)", str(text), re.IGNORECASE)
    return int(match.group(1)) if match else pd.NA

def extract_category(text):
    match = re.search(r"Category:\s*(Low|Medium|High)", str(text), re.IGNORECASE)
    return match.group(1).capitalize() if match else pd.NA

tracking_df["ai_score"] = tracking_df["ai_raw_response"].apply(extract_score)
tracking_df["ai_category"] = tracking_df["ai_raw_response"].apply(extract_category)

# Convert scores to numeric safely
tracking_df["human_score"] = pd.to_numeric(tracking_df["human_score"], errors="coerce")
tracking_df["ai_score"] = pd.to_numeric(tracking_df["ai_score"], errors="coerce")

tracking_df["score_diff"] = tracking_df["ai_score"] - tracking_df["human_score"]
tracking_df["abs_error"] = tracking_df["score_diff"].abs()

print("\n===== COMPARISON TABLE =====")
print(tracking_df[[
    "essay_id",
    "human_score",
    "ai_score",
    "human_category",
    "ai_category",
    "score_diff",
    "abs_error"
]])


# ============================
# 10) COMPUTE QWK AND PCC
# ============================
from sklearn.metrics import cohen_kappa_score
from scipy.stats import pearsonr
valid_df = tracking_df.dropna(subset=["human_score", "ai_score"]).copy()

if len(valid_df) >= 2:
    qwk = cohen_kappa_score(
        valid_df["human_score"],
        valid_df["ai_score"],
        weights="quadratic"
    )

    pcc, _ = pearsonr(
        valid_df["human_score"],
        valid_df["ai_score"]
    )

    print("\n===== METRICS =====")
    print("QWK:", qwk)
    print("PCC:", pcc)
else:
    print("\nNot enough valid AI scores yet to compute QWK and PCC.")


# ==========================================
# 11) OPTIONAL: SAVE RESULTS TO CSV
# ==========================================

tracking_df.to_csv("essay_scoring_results.csv", index=False)
print("\nResults saved to essay_scoring_results.csv")

# **bigger calibration and test set**
(with enhanced rubric prompt)

5 Low, 5 Medium, 5 High = 15 essays ✅

In [ ]:
# Recreate calibration with larger size
cal_low = set1[set1["score_category"] == "Low"].sample(5, random_state=42)
cal_med = set1[set1["score_category"] == "Medium"].sample(5, random_state=42)
cal_high = set1[set1["score_category"] == "High"].sample(5, random_state=42)

calibration = pd.concat([cal_low, cal_med, cal_high]).sample(frac=1, random_state=42).copy()

# Recreate test pool
test_pool = set1[~set1["essay_id"].isin(calibration["essay_id"])].copy()

# Pick test size
n_test = 15   # start with 10 or 15 since you're doing Ollama manually
test_df = test_pool.sample(n_test, random_state=42).reset_index(drop=True).copy()

print("Calibration size:", len(calibration))
print("Test size:", len(test_df))
print("Calibration IDs:", calibration["essay_id"].tolist()[:10], "...")
print("Test IDs:", test_df["essay_id"].tolist()[:10], "...")
print("Overlap:", set(calibration["essay_id"]).intersection(set(test_df["essay_id"])))
test_df.head(10)

Calibration size: 15
Test size: 15
Calibration IDs: [1339, 686, 1592, 772, 1572, 951, 1096, 995, 1212, 1536] ...
Test IDs: [982, 277, 415, 970, 523, 1467, 1094, 348, 1059, 1197] ...
Overlap: set()

,essay_id,essay,domain1_score,score_category
0,982,"In my opinion, I do believe that computers are...",8,Medium
1,277,"Dear @LOCATION2 press, I wonder if you know th...",9,High
2,415,"Dear @CAPS1 @CAPS2, Computers are all around u...",7,Medium
3,970,"Dear @CAPS1 @CAPS2 @CAPS3, @DATE1's society is...",11,High
4,523,"Dear @CAPS1, I - like many other people my age...",10,High
5,1467,Almost everyone in the @LOCATION1 uses a compu...,10,High
6,1094,"Dear Newspaper, @CAPS1 you know, the majority ...",8,Medium
7,348,"Dear newspaper, @CAPS1 people think that compu...",8,Medium
8,1059,I think that computers do have a positive effe...,8,Medium
9,1197,"Dear, Local Newspaper I think that it would be...",8,Medium

In [ ]:
def format_calibration_examples(calibration_df):
    examples = []
    for i, row in enumerate(calibration_df.itertuples(index=False), start=1):
        examples.append(f"""
Calibration Example {i}

Essay ID: {row.essay_id}

Essay:
{row.essay}

Human Score: {row.domain1_score}
Category: {row.score_category}
""")
    return "\n".join(examples)

calibration_text = format_calibration_examples(calibration)

calibration_prompt = f"""
You are an expert essay grader evaluating Grade 8 student essays.

========================
STUDENT TASK (FULL PROMPT)
========================

More and more people use computers, but not everyone agrees that this benefits society.
Those who support advances in technology believe that computers have a positive effect on people.
They teach hand-eye coordination, give people the ability to learn about faraway places and people,
and even allow people to talk online with other people.

Others have different ideas. Some experts are concerned that people are spending too much time
on their computers and less time exercising, enjoying nature, and interacting with family and friends.

Write a letter to your local newspaper in which you state your opinion on the effects computers have on people.
Persuade the readers to agree with you.

========================
SCORING SYSTEM
========================

- Each essay is scored by TWO human raters.
- Each rater assigns a score from 1 to 6.
- The final score is the SUM of both scores → range: 2 to 12.

ADJUDICATION RULE:
- If the two scores are adjacent → final score = sum
- If the two scores are NOT adjacent → the final score is determined by an expert scorer

Your task is to predict the FINAL resolved score (2–12).

========================
IMPORTANT DATA CHARACTERISTICS
========================

- Essays are written by students and may contain spelling, grammar, and punctuation errors.
- These errors should be preserved and should NOT overly influence scoring unless they affect clarity.
- Focus primarily on argument quality, reasoning, and structure.

========================
RUBRIC DIMENSIONS
========================

Evaluate essays based on:

1. Development of ideas (depth, clarity, elaboration)
2. Organization (logical structure and flow)
3. Clarity and fluency (readability and coherence)
4. Use of supporting details (specific vs general)
5. Awareness of audience (persuasive tone and purpose)

========================
RUBRIC LEVELS (1–6)
========================

Score Point 1:
- Undeveloped response
- Very minimal support
- Few or vague details
- Awkward and fragmented
- No awareness of audience
- Difficult to understand

Score Point 2:
- Underdeveloped response
- General or list-like ideas
- Weak reasoning
- Little or no organization
- Simplistic or unclear
- Limited awareness of audience

Score Point 3:
- Minimally developed response
- Some reasoning but limited elaboration
- More general than specific details
- Basic organization
- Weak transitions
- Some awareness of audience

Score Point 4:
- Somewhat developed response
- Adequate argument
- Mix of general and specific details
- Satisfactory organization
- Some transitions
- Adequate awareness of audience

Score Point 5:
- Developed response
- Clear position and persuasive support
- Mostly specific and relevant details
- Strong organization
- Good use of transitions
- Consistent awareness of audience

Score Point 6:
- Well-developed response
- Clear, thoughtful, and persuasive argument
- Fully elaborated ideas with specific details
- Strong and logical organization
- Fluent writing with effective transitions
- Strong awareness of audience

Use these levels internally to simulate how two human raters would score.

========================
CALIBRATION EXAMPLES
========================

{calibration_text}

========================
CRITICAL SCORING BEHAVIOR
========================

- Use calibration examples as strict reference points.
- Do NOT over-score essays with weak development.
- Do NOT inflate scores based only on essay length.
- Be strict when support is vague or repetitive.
- Allow minor grammar/spelling errors if ideas are strong.
- Ensure scores remain consistent with calibration patterns.

========================
GOAL
========================

Your goal is to simulate human grading behavior as closely as possible.

========================
OUTPUT
========================

Reply only with:
Calibration received.
"""
print(calibration_prompt)

You are an expert essay grader evaluating Grade 8 student essays.

========================
STUDENT TASK (FULL PROMPT)
========================

More and more people use computers, but not everyone agrees that this benefits society.
Those who support advances in technology believe that computers have a positive effect on people.
They teach hand-eye coordination, give people the ability to learn about faraway places and people,
and even allow people to talk online with other people.

Others have different ideas. Some experts are concerned that people are spending too much time
on their computers and less time exercising, enjoying nature, and interacting with family and friends.

Write a letter to your local newspaper in which you state your opinion on the effects computers have on people.
Persuade the readers to agree with you.

========================
SCORING SYSTEM
========================

- Each essay is scored by TWO human raters.
- Each rater assigns a score from 1 to 6.
- The final score is the SUM of both scores → range: 2 to 12.

ADJUDICATION RULE:
- If the two scores are adjacent → final score = sum
- If the two scores are NOT adjacent → the final score is determined by an expert scorer

Your task is to predict the FINAL resolved score (2–12).

========================
IMPORTANT DATA CHARACTERISTICS
========================

- Essays are written by students and may contain spelling, grammar, and punctuation errors.
- These errors should be preserved and should NOT overly influence scoring unless they affect clarity.
- Focus primarily on argument quality, reasoning, and structure.

========================
RUBRIC DIMENSIONS
========================

Evaluate essays based on:

1. Development of ideas (depth, clarity, elaboration)
2. Organization (logical structure and flow)
3. Clarity and fluency (readability and coherence)
4. Use of supporting details (specific vs general)
5. Awareness of audience (persuasive tone and purpose)

========================
RUBRIC LEVELS (1–6)
========================

Score Point 1:
- Undeveloped response
- Very minimal support
- Few or vague details
- Awkward and fragmented
- No awareness of audience
- Difficult to understand

Score Point 2:
- Underdeveloped response
- General or list-like ideas
- Weak reasoning
- Little or no organization
- Simplistic or unclear
- Limited awareness of audience

Score Point 3:
- Minimally developed response
- Some reasoning but limited elaboration
- More general than specific details
- Basic organization
- Weak transitions
- Some awareness of audience

Score Point 4:
- Somewhat developed response
- Adequate argument
- Mix of general and specific details
- Satisfactory organization
- Some transitions
- Adequate awareness of audience

Score Point 5:
- Developed response
- Clear position and persuasive support
- Mostly specific and relevant details
- Strong organization
- Good use of transitions
- Consistent awareness of audience

Score Point 6:
- Well-developed response
- Clear, thoughtful, and persuasive argument
- Fully elaborated ideas with specific details
- Strong and logical organization
- Fluent writing with effective transitions
- Strong awareness of audience

Use these levels internally to simulate how two human raters would score.

========================
CALIBRATION EXAMPLES
========================


Calibration Example 1

Essay ID: 1339

Essay:
would you rather read six books to get that one recipie, or would you rather look it up in less than ten minutes? I think computers have an positive effect on people you can learn about places you want you need in minutes and you can talk to your friends inline Computers have a good effect on people because, you can learn about places you want to wish this @DATE1. For example, @PERSON5 wanted to wish @LOCATION2 this @DATE1 but when he looked online he saw how @LOCATION2 just had an earthquake so he changed his plans this @DATE1. @CAPS1, @PERSON2 said "I wanted to go to @LOCATION3 this @DATE1 but I know about it, so I searched on google and figure thatb this @DATE1 I will go to @LOCATION3" that is one positive thing computers effect on people because you can learn about places you want to visit in the @DATE1. Computers have a positive effect on people because you can @CAPS1 find what you need in minutes. For example. @PERSON3 was looking for a cake recipie, he was looking many cook books but find it, so he took thru his labtop and found it in under five minutes, @CAPS1, computer experts @PERSON1 said "@CAPS2 of rooming thru books and books for information you nead why not go to the and the truxt me its much" @CAPS3, computers have a good effect on people because you can talk to your friends online, for example, @PERSON6 said "I moved from @CAPS4 to @LOCATION1 and I was sad to leave my bestfriend but knod how I can talk to her on @CAPS5." @CAPS1, @PERSON4 was in bed sick and coudnt go ourside to visit his friends so he kelf intouch with them on @CAPS7. Computers have a positive effect on people because you can learn about places you want to visit this @DATE1. You can find what you need in minutes, and you can talk to your friends online just remember even computer report @PERSON1 said " me its much easier"

Human Score: 8
Category: Medium


Calibration Example 2

Essay ID: 686

Essay:
Dear local newspaper, I would like to speak upon the topic of the effects that computers have on people. My opion on this topic is that computers do have an effect on people. Most people while surfing the internet don't keep track of time. What I mean when I say most people lose track of time is that, they try to keep track of the time but while on the web something @MONTH1 pop that catches their intrest and at that same time there focus is on something else. Some of the other effects computers can have on people is keeping them in the house. When many people are on the web they tend not to excersise as much. When in the house on the web most people that excersise stop excersising. The reason why this occurs is because while people are on the computer chair you feel so relaxed and calm that you don't want to get up. This leads into eating unhealthy foods. Some such as chips, donuts, twinkies and etc. Some @CAPS1 do not believe that is an opinion. The reason I say this is because while watching television the other day I saw a commercial that said quote "@CAPS2 that are more active are healthier than @CAPS2 that stay on the computer all day. Most @CAPS1 do gain weight on the computer because they are not physically active. Not being physically active can lead to A) obesity @CAPS4) cloged arteries or @CAPS5) lazyness. It can lead to all three because those are the effects of being on a computer every of the day. Most @CAPS1 should be enjoying nature instead of staying on the computer. There is a lot more to life than being on the web. Some such as playing sports. Not only is playing sports fun but at the same tim it is also healthy. Would you rather live to @NUM1 or live to @NUM2. And so local newspaper that is why I am writing you this letter today. I mean would you rather have friends @CAPS2 or be lonely. There are weight surgerys but those can rack up to thousands of dollars. And yes weight loss surgery does have effects such as death. So come on @LOCATION1 its your decison and remember the most important part of this letter which is between liveing healthy and young or dieing unhealthy and suffer. Its your choice @LOCATION1 decide.

Human Score: 9
Category: High


Calibration Example 3

Essay ID: 1592

Essay:
The computers are cool. Do you now I werpsite is @NUM1.com. We nede to time the lemt lo-menteno it. I love the compueters. We nede @NUM2 make a computers are grene compurers.

Human Score: 2
Category: Low


Calibration Example 4

Essay ID: 772

Essay:
Dear @CAPS1 @CAPS2, @CAPS3 computers hold exclusive inofrmation, I do not believe the have a good effect on people. The majority of students today crowd around a computer while they can be taking care of their body. Such as excersising or just going outside. People need to enjoy the wonders of nature instead of sitting on a computer. Not only will computers impact people, but it @MONTH1 also impact family in friends. There will be less interacting time a risk by going on a computer. Different websites can expose the wrong thing and get you into trouble. I firmly believe that computers have hamble affects on people. In @LOCATION1 today, we are already loaded with obese poeple. @NUM1 outof @NUM2 people are not physically healthy and a majority of obese people today state that they do own a computer. Computers attract people and same @MONTH1 sit at the computer for hours at a time what about excersising or enjoying the outdoors? Computers damage our bodies in a way by luering ourselves in while we can go out and enjoy nature. I definatly will argue this fact that computers have a bad effect on humans. Computer change not only the body, but mind. My sister has a computer in her bedroom and I barely see her at all. She stays up there all the time, and when my mom calls for dinner, it takes more than five @CAPS2 to get her away from her computer. Computers affect people because they keep humans away from civilization. Friends and family are impacted by the lack of interaction from one person. It's disrespectful to take time away from your friends to play on computers. This ruins many peoples social health, because the more they ignore their family or friends, these people will stop trying to interact with them. When these computer finatics came around, there want be anyone there for them. Computers definatly have an unhealthy affect on people who use them. How would you feel if tons of your personal info got out into the public. Nowadays, computers have a major chance to do that to you. Websites like @CAPS4, mysapce, or twitter have your information, and with a click of a button, it can be exposed to the world. Computers have a background of doing this kind of effect on people. Some dont understand what they are doing and if bad info or a picture sends out, it can fully negatively impact your career or edecation. Computers help people to make wrong choices and there is no doubt people should let up on the time they spend on the internet. Many agree, computers disadvantage many people in their own way. Whether it is by taking their health away because it keeps many indoors, or if it costs you your friends and family, computers are not good for your physical and social health. Computers can send out information and they are risky. They will majority impact your future and impact all people in a bad way.

Human Score: 10
Category: High


Calibration Example 5

Essay ID: 1572

Essay:
Dear to @CAPS1 this @MONTH1 concern, Computers do a whole lot now of days. You can play games, do homework, socialize but don't you think there are better things than that. Such as exercising, enjoying the beauty of nature, and most importantly interacting with family and friends. These are all the things that computers take away from people. Once you get onto a computer you never want to get off. If you look at it, it doesn't take much work and energy to use a computer. So if you eat and use the computer all day your not really burning any calories therefore you will gain weight. Computers make people feel lazy sometimes therefore they spend less time exercising. That is not good for your health at all. Exercising gives you energy and is good for you. Have you ever looked out the window and saw how beautiful nature is? When your on the computer chit-chatting with people and playing online friends do you think about what your missing. Everytime I use the computer I wish I could be outside playing and enjoying nature. Trees, flowers, plants, grass and lots of other things are what make up the earth, but some people don't apreciate those things. So next time your on the computer think about that. While your on the computer wasting time there is another homeless child wandering maybe looking for their family. Would you like to be that child who doesnt have a family or any type of friends? Lots of people think of their life without a family but it can happen anyday. So I believe instead of wasting time on the computer we should go and interact with family and friends. Even if its just having a conversation do it, maybe it can show them that you really care. In conclusion, I think that computers are a waste of time. I understand how people say it is used to comunicate with people but back then they didnt have computers and they communicated so we can to. Computes make you spend less time exercising, keeps you from enjoying nature and lastly interacting with family and friends. You won't go wrong if you listen to someone who uses a computer everyday.

Human Score: 8
Category: Medium


Calibration Example 6

Essay ID: 951

Essay:
Dear Local Newspaper, I agree with the experts when they say people are spending too much time on the computers. The reason for this is that one, people don't get enough exercise. Two, new websites have been made and people want to see how @CAPS1 works. Three, more and more teenage kids have the new technology. Their on @CAPS1 all the time, and don't realize their not spending any time with their family. Now that you know that lets move on to my first reason. First of all, people are spending a lot of time on the computer they don't have time to go outside and exercise, More people probably figure they don't need to go outside. Really they do, @CAPS1's important that they get their body moving and blood flowing through their body. Another thing is that we don't always need to get the answers off the computer. @CAPS1's east to find friend and play a game with them. Find something to do other than play games on the computer. Now that you know let's move on the second reason. Second of all, the computer network came up with new ideas for the computer. They now have facebook. More and more people use facebook now. This right here shows us they won't get out and play, this also means most kids won't do their homework. Another thing is that either parents set a time on the computer or they take @CAPS1 a way. Their is just so much amount of time you can be on the computer for and not get bored. Now that you know that lets move on to the last reason. Third of all, I would like to say people are spending more time on the computer than with their own family. The reason I say this is because @CAPS1 is important to spend as much time with family and friends instead of being on the computer @NUM1. We need to know also what's going on in our daily life. Another thing is that our family is way better than some game on the computer go outside with you family and play a game of wiffle ball. Now that you know that lets moves on to the conclusion. In conclusion, You have read an essay talking about how people spend more time on the computer rather than go outside to exersice, new website to keep them on longer, and not spending enough time with their family and friends. @CAPS1 is important to have a time limite on the computer and get up and moving. Don't be a lazy couch potato and sit on the computer all day get out and spend time with you family and friends, I hope you agree with me.

Human Score: 7
Category: Medium


Calibration Example 7

Essay ID: 1096

Essay:
I think that we should have computers. Because it help us find pleopl and it help us talk to peopl and it help you srech thing too I can have a brother that I never knew before then you can find that brother. Then I can talk to my firend online if I go to myspace or @CAPS1 because you can in @MONTH1 be have firend on myspace, and by srech this you can find new thins and you can look up this like weather in a different country or state I can find out how cold it is in taxes and you can srech an up to see how old it can be. Or how old it can get.

Human Score: 4
Category: Low


Calibration Example 8

Essay ID: 995

Essay:
I think computers are good, because some people dont have phones so @CAPS1 a good way to conect with people you know, also meet new people. Second some people are going to collage when there done with high school so you could just look on the computers and find one you like and pricess, also find ways there. Third reason is ahopping if a holiday is coming up you could check online and find stuff for cheap and nice to you. You could also order it to your house online if you dont got alot of time to go shopping. @CAPS1 some reasons why I think online is good you could chat, find places and pricess, collages and also shop online @CAPS1 why online is good.

Human Score: 4
Category: Low


Calibration Example 9

Essay ID: 1212

Essay:
Dear Local Newspaper, @CAPS1 home computers is a good thing for many reasons. One reason is because people can use computers to learn about other countries and people. People can also use computers to type and save paper. Also, people can use computers to talk to people living close or far away from you. Finally, computers can save paper by replacing books. One @MONEY1 the most important reasons why people need computers is because computers can help you learn about and research other things going on in the world. If a student needs to research a country and write a paper about it for school, it is much easier and faster to use a computer than to look through a textbook.Computers are also better and faster than a textbook if you want to know more about a person or a culture. Using computers to type are also faster than writing a paper. Using a computer can save time and money when it comes to typing a paper. When you are typing a paper, you don't have to worry about @CAPS1 handwriting or breaking your pencil. You also don't have to worry abut spelling something wrong because computers can check you spelling and grammar. What you are writting a paper you have in about all @MONEY1 these problems and more. You also have to spend money on pencils and other writting suppplies. Computers also saved people @MONEY1 becase they didn't need to buy paper to make textbooks. Computers also evolved how people can communicate with each other. Before computers were invented, you couldn't talk to people in other countries unless you paid to use a phone or sent them mail. Now, you can send instant mail which saves days @MONEY1 time and paper. You can also use webcams to talk to family members and people you don't know. That can save you a lot @MONEY1 money because you don't have to pay money for postage stamps, phone calls, or plane rides to visit them. Those are some @MONEY1 the best reasons why @CAPS1 a home computer is better than not @CAPS1 one. A home computer can save you time when you want to research a country, person, or culture. They can save you money because you don't have to buy postage stamps, pay for phone calls, or pay for plane rides to visit someone from a different state or country. Computers also help save paper because you no longer need to make large textbooks or use a different price @MONEY1 paper when you make a writting mistake.

Human Score: 9
Category: High


Calibration Example 10

Essay ID: 1536

Essay:
Some people dont like computers because of instant reason, and other people like computers little too much. I like computers but @CAPS1 not obsess with computers give good efforts on people, even me you can learn things off the computer and you start to get good hand eye coordination one of the things I like about the is that you can 'talk" to other people. Lots of people uses the computer a little too much that they dont exercise, or watch nature as much some normal (other) people should, and they dont spend them with their familys. I rather spend time on the computer for only (#@NUM1) three hours so then I can do other things with my time and you or anybody should do the same.

Human Score: 4
Category: Low


Calibration Example 11

Essay ID: 1196

Essay:

In [ ]:
def build_test_prompt(essay_id, essay_text):
    return f"""
You are an expert essay grader evaluating Grade 8 student essays.

========================
REMINDER OF SCORING SYSTEM
========================
- Final score range: 2 to 12
- Based on TWO human raters (1–6 each)

========================
IMPORTANT
========================
- Do NOT over-penalize grammar or spelling errors
- Focus on:
  • idea development
  • organization
  • support
  • clarity

========================
CALIBRATION EXAMPLES (REFERENCE)
========================

Low (Score ~2–4):
- Very short or unclear essays
- Weak or missing argument
- Little to no organization
- Mostly general or repetitive ideas

Medium (Score ~6–8):
- Clear opinion is present
- Some organization and structure
- Some supporting details but not deeply developed
- Ideas are understandable but not very strong or detailed

High (Score ~9–12):
- Clear and well-developed argument
- Strong organization and logical flow
- Specific and relevant supporting details
- Persuasive and coherent writing
========================
NOW GRADE THIS ESSAY
========================

Essay ID: {essay_id}

Essay:
{essay_text}

========================
OUTPUT FORMAT
========================

Essay ID: {essay_id}
Final Score: <number from 2–12>
Category: <Low / Medium / High>
Reasoning: <brief explanation>
"""

In [ ]:
tracking_df["prompt"] = tracking_df.apply(
    lambda row: build_test_prompt(row["essay_id"], row["essay"]),
    axis=1
)
print(tracking_df.loc[0, "prompt"])

You are an expert essay grader evaluating Grade 8 student essays.

========================
REMINDER OF SCORING SYSTEM
========================
- Final score range: 2 to 12
- Based on TWO human raters (1–6 each)

========================
IMPORTANT
========================
- Do NOT over-penalize grammar or spelling errors
- Focus on:
  • idea development
  • organization
  • support
  • clarity

========================
CALIBRATION EXAMPLES (REFERENCE)
========================

Low (Score ~2–4):
- Very short or unclear essays
- Weak or missing argument
- Little to no organization
- Mostly general or repetitive ideas

Medium (Score ~6–8):
- Clear opinion is present
- Some organization and structure
- Some supporting details but not deeply developed
- Ideas are understandable but not very strong or detailed

High (Score ~9–12):
- Clear and well-developed argument
- Strong organization and logical flow
- Specific and relevant supporting details
- Persuasive and coherent writing
========================
NOW GRADE THIS ESSAY
========================

Essay ID: 982

Essay:
In my opinion, I do believe that computers are good for you. I agree so because one, it can help you to communicate with other family members around the world. Two, it can teach you new languages you really desired to learn, and three, it can keep you updated on whats happening around the world. First, i believe that computers are good for you because it can let you communicate with your long-lost relatives you hardly see anymore. For example, if you miss any of your family members, you can simply go to your computer and search them up so you can type to them or talk to them through via chat mode, then you won't ever have that missing feeling anymore since you have a computer. In addition, computers can teach you how to learn new languages you alway's wanted to know, like, @CAPS1, or @CAPS2, or even @CAPS3 if you wanted! You can just simply go to your computer and type in "language of @CAPS2", and listen what it tells you of @CAPS2! Moreover, computers can keep you updated on whats happening around the world! It is way better to see it on computers than on tv's bevause computers give you more information about the situation of the event! Likewise, you could click, "locate area", on the computer and see in which area the incident took place in. You could also see the video's, behold the images, and seek the location of it on the computer. Sadly, my lecture has come to an . Those were my three main reasons why computers are good for people: You can communicate with long-lost relatives of yours, you can learn new languages, and therefore be updated on the qhats happening around the world. Would'nt you wan't to uphold those amazing events also?

========================
OUTPUT FORMAT
========================

Essay ID: 982
Final Score: <number from 2–12>
Category: <Low / Medium / High>
Reasoning: <brief explanation>

In [ ]:
tracking_df["prompt"] = tracking_df.apply(
    lambda row: build_test_prompt(row["essay_id"], row["essay"]),
    axis=1
)
print(tracking_df.loc[1, "prompt"])

You are an expert essay grader evaluating Grade 8 student essays.

========================
REMINDER OF SCORING SYSTEM
========================
- Final score range: 2 to 12
- Based on TWO human raters (1–6 each)

========================
IMPORTANT
========================
- Do NOT over-penalize grammar or spelling errors
- Focus on:
  • idea development
  • organization
  • support
  • clarity

========================
CALIBRATION EXAMPLES (REFERENCE)
========================

Low (Score ~2–4):
- Very short or unclear essays
- Weak or missing argument
- Little to no organization
- Mostly general or repetitive ideas

Medium (Score ~6–8):
- Clear opinion is present
- Some organization and structure
- Some supporting details but not deeply developed
- Ideas are understandable but not very strong or detailed

High (Score ~9–12):
- Clear and well-developed argument
- Strong organization and logical flow
- Specific and relevant supporting details
- Persuasive and coherent writing
========================
NOW GRADE THIS ESSAY
========================

Essay ID: 277

Essay:
Dear @LOCATION2 press, I wonder if you know that @PERCENT1 of people out of @NUM1 surveyed by the university out @LOCATION1 agreed that using lap tops and computers had a very good benefit on their life? I agree that computers benefit society and every day lifes. With a computer, you can interact with people all around the world, they can help with school work, and make every day life eaiser. Five years ago I had to move from @LOCATION4 to @LOCATION3. We had to leave all of our family and friends behind. However, with this great tecnology, we could e-mail them. Instant message them, and video chat with them, instead on having to face out money to make long distance calls. Theres many people out their like me. Who have friends and family far away, weather its family in different countries, old school mates and camp friends using a computer is a great way to keep in touch with one another. Using a computer can also more life easier. Moms taking care of their kids might not be able to go to @CAPS1 & @CAPS2 with one kid not wanting to get off his video games, the other watching their favorite @CAPS3 show. Thankfully that man and go online, pick the food that she and the quantity and she can get someone to deliver it. That mother also might not be able to get out and go shopping. So with her computer she can go to her favorite stores website and pick the clothes she wants. And then when @CAPS4 comes, a computer can be great not to worry about not having enough time to go and. A computers just have life that much simpiler!. Statistics how or people help online instant or going in. "Computers are great, I can homework and know that if they to write planner than they we to and out. If, they can and more of information on the computer from @CAPS5.com, then they could find in their local library. You can find almost anything with search engins on your computer! Some people do disagree with the use of computers, or some also believe that some people abuse the benefit of computers and spend to much time on it and not exercising and enjoying nature enough. This is true, not as long as you stay reasonable with usage or your computer, it benefits you in many ways. Like I said, its great for keeping connections between people, simpling everyday life, and research for school.

========================
OUTPUT FORMAT
========================

Essay ID: 277
Final Score: <number from 2–12>
Category: <Low / Medium / High>
Reasoning: <brief explanation>

In [ ]:
tracking_df["prompt"] = tracking_df.apply(
    lambda row: build_test_prompt(row["essay_id"], row["essay"]),
    axis=1
)
print(tracking_df.loc[2, "prompt"])

You are an expert essay grader evaluating Grade 8 student essays.

========================
REMINDER OF SCORING SYSTEM
========================
- Final score range: 2 to 12
- Based on TWO human raters (1–6 each)

========================
IMPORTANT
========================
- Do NOT over-penalize grammar or spelling errors
- Focus on:
  • idea development
  • organization
  • support
  • clarity

========================
CALIBRATION EXAMPLES (REFERENCE)
========================

Low (Score ~2–4):
- Very short or unclear essays
- Weak or missing argument
- Little to no organization
- Mostly general or repetitive ideas

Medium (Score ~6–8):
- Clear opinion is present
- Some organization and structure
- Some supporting details but not deeply developed
- Ideas are understandable but not very strong or detailed

High (Score ~9–12):
- Clear and well-developed argument
- Strong organization and logical flow
- Specific and relevant supporting details
- Persuasive and coherent writing
========================
NOW GRADE THIS ESSAY
========================

Essay ID: 415

Essay:
Dear @CAPS1 @CAPS2, Computers are all around us where ever you go. You can learn things on them or play games. Although computers are all around us they do not have a possitive effect on people because, harmful people could findout where you live and they are too addicting. Where ever you look you can find a computer. At home, in school, in your car, at work, and hotels. Being exposed to these computers are helpful. Everything we see now a days is run by or has a computer. In the future we are going to see more and more computers. Buisnesses practically run off of computers, soon they will run them by thereself. Also with so many computers it creates jobs. You can make computers, program them, fix them, and even supervise them doing work. Even though everyone says they are safe on the computer, they are not. While on a chatting website you could meet someone and they might be a child melestor or a. They can find out where you live and when no one is home or when you are home alone. With your address they can even look at your house on a website or possibly get your houses blueprints. Then they can come and leave you mentally scared for life. There are tons of things you can do on a computer. For example you can play games. There are games with virtual worlds or games that are fun and have no meaning. Either way games on the computer are too addicting. You say you are going to play for @NUM1 minutes but they are so addicting you play for @NUM2 hours. The games just suck you in and your stuck. Although computers are all around us they do not have a possitive effect on people because harmful people can find out where you live and they are too addicting. Computers are good and bad at the same time. People need to know when to stop using it or it can drasticly change your life.

========================
OUTPUT FORMAT
========================

Essay ID: 415
Final Score: <number from 2–12>
Category: <Low / Medium / High>
Reasoning: <brief explanation>

In [ ]:
tracking_df["prompt"] = tracking_df.apply(
    lambda row: build_test_prompt(row["essay_id"], row["essay"]),
    axis=1
)
print(tracking_df.loc[3, "prompt"])

You are an expert essay grader evaluating Grade 8 student essays.

========================
REMINDER OF SCORING SYSTEM
========================
- Final score range: 2 to 12
- Based on TWO human raters (1–6 each)

========================
IMPORTANT
========================
- Do NOT over-penalize grammar or spelling errors
- Focus on:
  • idea development
  • organization
  • support
  • clarity

========================
CALIBRATION EXAMPLES (REFERENCE)
========================

Low (Score ~2–4):
- Very short or unclear essays
- Weak or missing argument
- Little to no organization
- Mostly general or repetitive ideas

Medium (Score ~6–8):
- Clear opinion is present
- Some organization and structure
- Some supporting details but not deeply developed
- Ideas are understandable but not very strong or detailed

High (Score ~9–12):
- Clear and well-developed argument
- Strong organization and logical flow
- Specific and relevant supporting details
- Persuasive and coherent writing
========================
NOW GRADE THIS ESSAY
========================

Essay ID: 970

Essay:
Dear @CAPS1 @CAPS2 @CAPS3, @DATE1's society is much more different from what it was like twenty years ago. We have phones that can easily allow us to browse the web as we please just like a computer. Our access to such a large network beings us together, can broaden mental horisons and keep many @CAPS5 hard workers on key point so that when time for work comes around, they are ready. Not everyone agrees that technology is benefit to our growing well, but I believe it keeps us moving forward and away from ignorance in all of its forms. Our construction workers work hard during their busy seasons. They vigorously build sley scraping towers, educational fucilities, additions to our health center, and even the very places we call home. However, when weather is not on their side and building anything can be hazzardous in the long run, they must still ramain at the ready when duty calls. Lately, there has been an advancement in technology to help chane opperators maintain their skills during their of season vistually. It @MONTH1 appear easy to the untrained spectation. To one it @MONTH1 seem like all they do is seat themselves in a pull a few levers, and push a few buttons. However, there is in fact a persition to such a task. Pull the lever to quickly and the crane can go sharply in the wrong direction causing it to tip over. One of feild reponters tried the @CAPS1 virtual trainer and found a @CAPS1 appreciation for the jobs at our builders. That just goes to show that @CAPS5 one does not keep such skill in check, they could in fact cause a serious malfunction on a construction site. I, personally, find it very entertaining and at the same time educational to learn a language different from my own. In fact, I teach myself @CAPS4 at home. However, @CAPS5 I did not have a computer at home, my studies would be near impossible. With @DATE1's economy going to a class outside & school, or even hiring a personal tutor, can be enough to effect anyones budget emensly. The internet provides an efficient low casting, or even free, way to help any language learner. One can even find study tips from native speakers at those who have already learned vast bit about the language. In @DATE1's society not everyone has the time to go to he library and pick up a book on a country they are interested in. Some @MONTH1 say that asking a neighbor about their home canbe just as afective, but that can awkward for those that don't particulary do well in face to face setting. However, havbing a complete at hand can make learning an enjoyabl experience. Once can find blog posts about someone's visti to there country of interest & even videos of their time there. Websites made entirely for those interesting a particular culture can also prove helpful. On the other hand, @CAPS5 someone were to be looking for and acception vacation spot recommended by locals, that information can be found as well. Some people do not love in an area where they can connect with family by a simple call or a drive. One @MONTH1 have to take a plane or pay to take with relatives. Social networks on the web makes connecting with lvoe ones easier and more affordable. The speed of instant messaging can make it seem like they are in the same room instead across the ocean. I hope that everything I have fare travel can serve a purpose to someone who has not been able to find way benefits to technological advances. Please do remember that technology can serve as a skill maintenance tool, educational, and as a connection for our foreign born citizens. Thank you for

========================
OUTPUT FORMAT
========================

Essay ID: 970
Final Score: <number from 2–12>
Category: <Low / Medium / High>
Reasoning: <brief explanation>

In [ ]:
tracking_df["prompt"] = tracking_df.apply(
    lambda row: build_test_prompt(row["essay_id"], row["essay"]),
    axis=1
)
print(tracking_df.loc[4, "prompt"])

You are an expert essay grader evaluating Grade 8 student essays.

========================
REMINDER OF SCORING SYSTEM
========================
- Final score range: 2 to 12
- Based on TWO human raters (1–6 each)

========================
IMPORTANT
========================
- Do NOT over-penalize grammar or spelling errors
- Focus on:
  • idea development
  • organization
  • support
  • clarity

========================
CALIBRATION EXAMPLES (REFERENCE)
========================

Low (Score ~2–4):
- Very short or unclear essays
- Weak or missing argument
- Little to no organization
- Mostly general or repetitive ideas

Medium (Score ~6–8):
- Clear opinion is present
- Some organization and structure
- Some supporting details but not deeply developed
- Ideas are understandable but not very strong or detailed

High (Score ~9–12):
- Clear and well-developed argument
- Strong organization and logical flow
- Specific and relevant supporting details
- Persuasive and coherent writing
========================
NOW GRADE THIS ESSAY
========================

Essay ID: 523

Essay:
Dear @CAPS1, I - like many other people my age - love to sit in front of a computer and explore it's wonders. But that does not mean that I spend my whole life on it like others. So I can see what too much computer time can do. It has made kids my age more aggressive, have health problems, and care even less about the environment. More and more kids are falling into those traps. Too much computer time can make even the nicest person extremely aggressive. I know from past experience that when you bother people when they are on their obsession, they will snap at you, yell, or even start swearing at you, or maybe get violent. If someone stays up to late on the computer, the next day could mean that they're cranky from the lack of sleep. This aggression @MONTH1 cause others to get aggressive in response, which @MONTH1 lead to a verbal or physical fight, which (hopefully) nobody wants. Another issue too much computer time can cause, @CAPS1, are even more health issues. Staying inside all day will keep people from getting the neccessary amount of vitamin @CAPS3 they need which is a vital nutricious vitamin that comes from the sun itself. Not getting enough vitamin @CAPS3 throughout a person's childhood can result in getting an illness called @CAPS5 later in life, which never truly goes away and hinders people from doing the things they love. Too much computer time also means people aren't getting enough exercise, and with the way we eat now, those two things can add up to making a person obeie. Others who do not want to get the proper amount of exercise or eat right and at the same time do not want to become obeisce, @MONTH1 to anorexia. Neither or these weight problems are very good for you, proving my point about the health issues of too much computer time. The issue I will have you read @CAPS1, is how people will become even less caring of the environment. Some of the big technology companies side-step around environmental protection laws to find cheaper ways to make their products and the thing is, no one cares! No one cares so long as they get their newer and better piece of technology. Everyone will just keep protecting these companies to get what they want to satisfy the craving for more computers. Now, I'm not saying that having any computer time is bad. I'm just trying to prove that too much is bad for you. That with too much computer time, people can become more aggresive, have health issues, and become even less caring of the environment. Therefore I urge you @CAPS1 to write an article in the newspaper about the effects of too much computer time, to make it known to everyone in the city. It might help us make a better future.

========================
OUTPUT FORMAT
========================

Essay ID: 523
Final Score: <number from 2–12>
Category: <Low / Medium / High>
Reasoning: <brief explanation>

In [ ]:
tracking_df["prompt"] = tracking_df.apply(
    lambda row: build_test_prompt(row["essay_id"], row["essay"]),
    axis=1
)
print(tracking_df.loc[5, "prompt"])

You are an expert essay grader evaluating Grade 8 student essays.

========================
REMINDER OF SCORING SYSTEM
========================
- Final score range: 2 to 12
- Based on TWO human raters (1–6 each)

========================
IMPORTANT
========================
- Do NOT over-penalize grammar or spelling errors
- Focus on:
  • idea development
  • organization
  • support
  • clarity

========================
CALIBRATION EXAMPLES (REFERENCE)
========================

Low (Score ~2–4):
- Very short or unclear essays
- Weak or missing argument
- Little to no organization
- Mostly general or repetitive ideas

Medium (Score ~6–8):
- Clear opinion is present
- Some organization and structure
- Some supporting details but not deeply developed
- Ideas are understandable but not very strong or detailed

High (Score ~9–12):
- Clear and well-developed argument
- Strong organization and logical flow
- Specific and relevant supporting details
- Persuasive and coherent writing
========================
NOW GRADE THIS ESSAY
========================

Essay ID: 1467

Essay:
Almost everyone in the @LOCATION1 uses a computers at one point in their life. Computers are a way to teach hand eye coordination through programs, games and typing. The internet can be used for researching different far away cultures, as well as someone's own lifestyle. This compact well made piece of technology has been belaming more and more intricate. Realizing how much help computers have in everyday life, people will be the down fall or support for computer technology moving forward. One very basic but evident result from using a computer is hand-eye coordination. Since the time children are in grade school, they learn typing on a keyboard. Special programs help kids learn the necesary skill while enjoying the practice. When I was small, a mere fight years old, I remember typing. I was always excited when my mom and I went to barnes and noble to pick up a new typing program. I especially enjoyed "type to learn" and @CAPS1 typing lessons as well as teaching children to type is general, teaches hand-eye coordination in high school, college, and the job world. Young adults and adults are expected to type papers, resemes, and applications. In this day in age the technology era has begin and typing is a necessity. Another way to teach hand-eye coordination is through computer games. A simple challenge like solitaire, bejewled or car racing teach the skill and much more advanced games for example, world of war craft need perfect coordination can be through typing and games, both on the computer. Though some experts are conserned "people are spending too much time on the computer and less time..enjoying nature," you are able to learn about geography, travel, and nature. One amazing on a computer is the world wide web. This consists of millions of websites, pages, search engines, and information arte you in an upcoming geography uses? Are you planning a trip the for you do you need to find a definition for the word "cognitive"? of @CAPS1 pertain to you, a legitamite website house your and all you need to do is search. Instead of having to travel to learn about special wonders, for travel prices are expensive and you can simply, click and type to and amazing at your searching on a computer, you can learn about long ago cultures and rituals. Information you would find at museum @NUM1 years ago. @CAPS1 complex simple to use technological a world of pictures simple, art and history right at your fingertips.

========================
OUTPUT FORMAT
========================

Essay ID: 1467
Final Score: <number from 2–12>
Category: <Low / Medium / High>
Reasoning: <brief explanation>

In [ ]:
tracking_df["prompt"] = tracking_df.apply(
    lambda row: build_test_prompt(row["essay_id"], row["essay"]),
    axis=1
)
print(tracking_df.loc[6, "prompt"])

You are an expert essay grader evaluating Grade 8 student essays.

========================
REMINDER OF SCORING SYSTEM
========================
- Final score range: 2 to 12
- Based on TWO human raters (1–6 each)

========================
IMPORTANT
========================
- Do NOT over-penalize grammar or spelling errors
- Focus on:
  • idea development
  • organization
  • support
  • clarity

========================
CALIBRATION EXAMPLES (REFERENCE)
========================

Low (Score ~2–4):
- Very short or unclear essays
- Weak or missing argument
- Little to no organization
- Mostly general or repetitive ideas

Medium (Score ~6–8):
- Clear opinion is present
- Some organization and structure
- Some supporting details but not deeply developed
- Ideas are understandable but not very strong or detailed

High (Score ~9–12):
- Clear and well-developed argument
- Strong organization and logical flow
- Specific and relevant supporting details
- Persuasive and coherent writing
========================
NOW GRADE THIS ESSAY
========================

Essay ID: 1094

Essay:
Dear Newspaper, @CAPS1 you know, the majority of people now posses computers. Computers have greatly advanced society and technology. Some people say that computers have negative effects, but that is not true. Computers have influenced people in many benificial ways. Although some experts want people to use computers less, that technology is required in schools. Kids are fold to type their papers, which lets them finish faster. This faster finish can lead to kids not staying up too late. Then doing homework. That is better for their health. Computers also develop hand-eye coordination which is an essential skill for later in life. In my opinion computers have greatly contributed to technology. They are letting explore place human has ever/could ever go. We can make and distribute item much faster. In addition, computers also let people learn about faraway places about different cultures and different people. Computers can expand everyone's horizons and let them know about places and things that they never knew existed. With are of the largest number of members. Facebook is a website that people use to communicate. More than @PERCENT1 of most students in an average school have one. They communicate there more than they could without computers. Computers aren't making people "anti social" or making them interact with friends less, they're actually talking more. Computers are letting people communicate daily with people from all around, without having to wory about running out of cellphone minutes. Overall, computers are letting people broaden their horizons are lock of new things. They are more of a benefit than a burden. Computers are the next best thing since sliced bread.

========================
OUTPUT FORMAT
========================

Essay ID: 1094
Final Score: <number from 2–12>
Category: <Low / Medium / High>
Reasoning: <brief explanation>

In [ ]:
tracking_df["prompt"] = tracking_df.apply(
    lambda row: build_test_prompt(row["essay_id"], row["essay"]),
    axis=1
)
print(tracking_df.loc[7, "prompt"])

You are an expert essay grader evaluating Grade 8 student essays.

========================
REMINDER OF SCORING SYSTEM
========================
- Final score range: 2 to 12
- Based on TWO human raters (1–6 each)

========================
IMPORTANT
========================
- Do NOT over-penalize grammar or spelling errors
- Focus on:
  • idea development
  • organization
  • support
  • clarity

========================
CALIBRATION EXAMPLES (REFERENCE)
========================

Low (Score ~2–4):
- Very short or unclear essays
- Weak or missing argument
- Little to no organization
- Mostly general or repetitive ideas

Medium (Score ~6–8):
- Clear opinion is present
- Some organization and structure
- Some supporting details but not deeply developed
- Ideas are understandable but not very strong or detailed

High (Score ~9–12):
- Clear and well-developed argument
- Strong organization and logical flow
- Specific and relevant supporting details
- Persuasive and coherent writing
========================
NOW GRADE THIS ESSAY
========================

Essay ID: 348

Essay:
Dear newspaper, @CAPS1 people think that computers are a waste of time and that they are dangerous. Yes computers can be dangerous but they can also help you in @CAPS1 diffrent ways. Such as paying bills on line or planin vacation and even attending collage classes. For @CAPS1 people bills are a strugle. They are an incovenienc and there are way to @CAPS1 of them. If you think about it @CAPS1 people work all day on some time all night, wouldn't it be nice to come home and have all your bills payed? Well one way you can do that is from a computers, computers have @CAPS1 programs that can help you pay your bills faster so that when you come home you can relax and enjy you free time. Computers are also good for planing vactions. @CAPS1 people each year use on line programs to plan there vacations and trips, for example my family and I planed a trip to @LOCATION1 in the @DATE1 of @NUM1. When we get to the airport we had first class tikets and a ride wateing when we got of the plain that @DATE1 was the best so far. Going into a new generation @CAPS1 people are starting to take on line colleg classes do to the fact that they work or have a kid at home these @CAPS2 are good for people with jobs because they are short and you learn alot. A computer is very helpful for taking these classes because if you did not have one it would incible you from taking the class. A computer is a great thing to have for all these things. So if your a mother of a worker and you would like to go back to school you should consider taking on line colleg classes. And if your family wants a vacation you should try out one of the @CAPS1 programs the enternet has for travling.

========================
OUTPUT FORMAT
========================

Essay ID: 348
Final Score: <number from 2–12>
Category: <Low / Medium / High>
Reasoning: <brief explanation>

In [ ]:
tracking_df["prompt"] = tracking_df.apply(
    lambda row: build_test_prompt(row["essay_id"], row["essay"]),
    axis=1
)
print(tracking_df.loc[8, "prompt"])

You are an expert essay grader evaluating Grade 8 student essays.

========================
REMINDER OF SCORING SYSTEM
========================
- Final score range: 2 to 12
- Based on TWO human raters (1–6 each)

========================
IMPORTANT
========================
- Do NOT over-penalize grammar or spelling errors
- Focus on:
  • idea development
  • organization
  • support
  • clarity

========================
CALIBRATION EXAMPLES (REFERENCE)
========================

Low (Score ~2–4):
- Very short or unclear essays
- Weak or missing argument
- Little to no organization
- Mostly general or repetitive ideas

Medium (Score ~6–8):
- Clear opinion is present
- Some organization and structure
- Some supporting details but not deeply developed
- Ideas are understandable but not very strong or detailed

High (Score ~9–12):
- Clear and well-developed argument
- Strong organization and logical flow
- Specific and relevant supporting details
- Persuasive and coherent writing
========================
NOW GRADE THIS ESSAY
========================

Essay ID: 1059

Essay:
I think that computers do have a positive effect on people because they teach hand-eye codination, also give people the ability to and lastly they allow people to talk online. First, they teach hand eye codination and I think thats good because when people get a job they can probably more focused and can probably work faster. So if people can do that when they get a job and their jobs involve working on a computer it can be easier for them and their job can be more enjoyable. Second they give people the ability to learn more because we have all these sites that involve information an everything so people can be more knowledge so if they're more knowledged they can probably get a really good job that pays alot. And they can look up whatever they like. So if they reasearch alot and go to school they can get the job they always wanted because they know so much knowledged people are better people. Lastly they can talk to online people when people can contact each other its better because if they have no phone to reach someone they need to reach they got a computer that they can either email or use a webcam were they can see the person. I think that having a computer is good for all these reasons having hand eye cordination give people the ability to learn more and allow people to talk online with other people.

========================
OUTPUT FORMAT
========================

Essay ID: 1059
Final Score: <number from 2–12>
Category: <Low / Medium / High>
Reasoning: <brief explanation>

In [ ]:
tracking_df["prompt"] = tracking_df.apply(
    lambda row: build_test_prompt(row["essay_id"], row["essay"]),
    axis=1
)
print(tracking_df.loc[9, "prompt"])

You are an expert essay grader evaluating Grade 8 student essays.

========================
REMINDER OF SCORING SYSTEM
========================
- Final score range: 2 to 12
- Based on TWO human raters (1–6 each)

========================
IMPORTANT
========================
- Do NOT over-penalize grammar or spelling errors
- Focus on:
  • idea development
  • organization
  • support
  • clarity

========================
CALIBRATION EXAMPLES (REFERENCE)
========================

Low (Score ~2–4):
- Very short or unclear essays
- Weak or missing argument
- Little to no organization
- Mostly general or repetitive ideas

Medium (Score ~6–8):
- Clear opinion is present
- Some organization and structure
- Some supporting details but not deeply developed
- Ideas are understandable but not very strong or detailed

High (Score ~9–12):
- Clear and well-developed argument
- Strong organization and logical flow
- Specific and relevant supporting details
- Persuasive and coherent writing
========================
NOW GRADE THIS ESSAY
========================

Essay ID: 1197

Essay:
Dear, Local Newspaper I think that it would be better if people get outside to get so exercise and enjoy nature to interacte with there family and friends. If you get out with your family and friends maybe more teens and adults would be in better shape and more healthly. Say we jump out of bed, gets some breakfast and head to the park to gets an excrize with your family and friends. Alot of family and friends i think spend way to much time on the computers or there labtops because if they are on the computer to long then they will not want to go outside and get excrise with there friends. More and more people use the computer. But not everybody agrees on this statement. What I think it would be better to solve the problem and have everybody get outside and get some freshair with family and friends. But some people don't think that is the right thing to go. People that think those who support advances in technology believe that computers have a positive effect on people. Well I don't think that is the way to go because you need to get outside to get some. Freshair with people. But if you want to go on the computer you can but I think it should be only for a little bit then because some people have a bissness that they have to work on when they are at work. Sometimes people have to work on there computer every day so if that is the case they I think they should be alouded to use the labtop or computer. But if you are a teen you should only go on if you have to f you needing the internent or writeing a paper. But if you going to go on to just go on to just talk to friend then that is a waste of time in somebody life. Well at least my life it is. I think as a teen you shold be to work on studying on doing your homework instead of being on the computer because I think it would be better to make sure your grade are not making you fail in your school carvee in life. So that is why it is best to make sure you aren't on the computer all the time talking to your friends on the computer all day because it could make you fail in life. I would only go on for a little bit to talk to your friends. That is why I think it is not right to spend all your time on the computer. Jump outside and in goal the outside weather with friends and family meabers. I hope teen and adult get outside from now on because it would be better for allof us and everybody would be heathly. If they tri this program. If you tri this program it will really work to all of you tri proise it will work and you will be heathly and not feel bad about yourself.

========================
OUTPUT FORMAT
========================

Essay ID: 1197
Final Score: <number from 2–12>
Category: <Low / Medium / High>
Reasoning: <brief explanation>

In [ ]:
tracking_df["prompt"] = tracking_df.apply(
    lambda row: build_test_prompt(row["essay_id"], row["essay"]),
    axis=1
)
print(tracking_df.loc[10, "prompt"])