<a href="https://colab.research.google.com/github/MalakSalehh/Thesis-datasets/blob/main/ASAP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
from google.colab import files
uploaded = files.upload()

Saving training_set_rel3.tsv.zip to training_set_rel3.tsv.zip

In [4]:
!unzip training_set_rel3.tsv.zip

Archive:  training_set_rel3.tsv.zip
  inflating: training_set_rel3.tsv

# Dataset Metadata Description
The dataset used in this study is the **Hewlett Foundation Automated Essay Scoring (AES) dataset**, originally released for the Kaggle Automated Student Assessment Prize (ASAP) competition. The dataset contains **12,976 student essays** written by students in grades **7 to 10**.

The dataset includes **28 variables** describing essay identifiers, essay prompts, essay text, and scores assigned by multiple human raters.

---

## Dataset Structure

Each row in the dataset represents **one student essay**, while each column represents an attribute associated with the essay.

The dataset dimensions are:

- **Number of essays:** 12,976  
- **Number of variables:** 28  

---

## Identification Variables

These columns uniquely identify each essay and its associated prompt.

- **essay_id**: A unique identifier for each essay.
- **essay_set**: Identifies which prompt the essay belongs to. The dataset contains **eight essay sets**, each corresponding to a different writing prompt.

---

## Essay Text

- **essay**: Contains the full textual response written by the student.

This column represents the **primary input data** used for automated essay scoring.

---

## Human Rater Scores

Each essay was evaluated by multiple human raters. The dataset includes the individual scores assigned by these raters.

- **rater1_domain1**
- **rater2_domain1**
- **rater3_domain1**

These columns represent scores assigned independently by different graders.

---

## Final Resolved Score

- **domain1_score**

This column represents the **final resolved score** determined after combining the individual rater scores. This value serves as the **ground truth label** used for training and evaluating automated essay scoring systems.

---

## Secondary Scoring Domain

Some essays include an additional scoring dimension.

- **rater1_domain2**
- **rater2_domain2**
- **domain2_score**

These scores are primarily associated with **essay set 2**, which evaluates essays across two scoring domains.

---

## Trait-Level Scores

Some essay sets include detailed trait-level scoring that evaluates specific aspects of writing quality.

Examples include:

- **rater1_trait1 – rater1_trait6**
- **rater2_trait1 – rater2_trait6**
- **rater3_trait1 – rater3_trait6**

These traits evaluate writing characteristics such as organization, grammar, coherence, and language usage.

---

## Missing Values in the Dataset

Certain columns contain **NaN (Not a Number)** values. This occurs because not all essay sets use the same scoring criteria.

For example:

- Some essay sets only contain **domain1 scores**.
- Essay set 2 includes **two scoring domains**.
- Essay sets 7–8 include **trait-level scoring**.

As a result, variables that are not applicable to certain essay sets appear as missing values.

---

## Key Variables Used in the Study

For the initial analysis and experimentation, the following variables are primarily used:

- **essay** → input text
- **domain1_score** → target score
- **essay_set** → prompt identifier

These variables provide the essential information required for automated essay scoring experiments.

In [5]:
import pandas as pd

df = pd.read_csv('training_set_rel3.tsv', sep='\t', encoding='latin1')

In [6]:
print("Shape:", df.shape)
print("\nColumns:")
print(df.columns.tolist())

Shape: (12976, 28)

Columns:
['essay_id', 'essay_set', 'essay', 'rater1_domain1', 'rater2_domain1', 'rater3_domain1', 'domain1_score', 'rater1_domain2', 'rater2_domain2', 'domain2_score', 'rater1_trait1', 'rater1_trait2', 'rater1_trait3', 'rater1_trait4', 'rater1_trait5', 'rater1_trait6', 'rater2_trait1', 'rater2_trait2', 'rater2_trait3', 'rater2_trait4', 'rater2_trait5', 'rater2_trait6', 'rater3_trait1', 'rater3_trait2', 'rater3_trait3', 'rater3_trait4', 'rater3_trait5', 'rater3_trait6']

The dataset contains 12,976 student essays and 28 associated variables describing essay identifiers, prompt identifiers, essay text, and scores assigned by human raters.
* Each essay is uniquely identified by an essay identifier and is associated with an essay set that corresponds to a specific writing prompt.
* Each essay was evaluated by multiple human raters. The dataset includes the individual scores assigned by these raters.
* The **domain1_score** column represents the resolved score derived from the individual rater evaluations and serves as the ground truth label for automated essay scoring experiments.
* Some essay sets include a secondary scoring dimension represented by domain2_score.

In [7]:
import pandas as pd

df = pd.read_csv('training_set_rel3.tsv', sep='\t', encoding='latin1')
df.head()

,essay_id,essay_set,essay,rater1_domain1,rater2_domain1,rater3_domain1,domain1_score,rater1_domain2,rater2_domain2,domain2_score,...,rater2_trait3,rater2_trait4,rater2_trait5,rater2_trait6,rater3_trait1,rater3_trait2,rater3_trait3,rater3_trait4,rater3_trait5,rater3_trait6
0,1,1,"Dear local newspaper, I think effects computer...",4,4,NaN,8,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,1,"Dear @CAPS1 @CAPS2, I believe that using compu...",5,4,NaN,9,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,1,"Dear, @CAPS1 @CAPS2 @CAPS3 More and more peopl...",4,3,NaN,7,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,1,"Dear Local Newspaper, @CAPS1 I have found that...",5,5,NaN,10,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,1,"Dear @LOCATION1, I know having computers has a...",4,4,NaN,8,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
df['essay_set'].value_counts().sort_index() #Number of Essays in each essay set

essay_set
1    1783
2    1800
3    1726
4    1770
5    1805
6    1800
7    1569
8     723
Name: count, dtype: int64

In [9]:
df.groupby('essay_set')['domain1_score'].agg(['min','max']) #score range for each essay set.

           min  max
essay_set
1            2   12
2            1    6
3            0    3
4            0    3
5            0    4
6            0    4
7            2   24
8           10   60

In [10]:
df['essay_word_count'] = df['essay'].apply(lambda x: len(str(x).split()))
df['essay_word_count'].describe() #shortest essay, longest essay, average essay length in WORDS

count    12976.000000
mean       222.708154
std        175.919826
min          2.000000
25%         98.000000
50%        163.000000
75%        307.000000
max       1064.000000
Name: essay_word_count, dtype: float64

**ESSAY SET**

In [11]:
# Filter only essay set 1
set1 = df[df['essay_set'] == 1]

# check shape
set1.shape

(1783, 29)

In [13]:
set1 = set1[['essay_id','essay','domain1_score']]

set1.head()

   essay_id                                              essay  domain1_score
0         1  Dear local newspaper, I think effects computer...              8
1         2  Dear @CAPS1 @CAPS2, I believe that using compu...              9
2         3  Dear, @CAPS1 @CAPS2 @CAPS3 More and more peopl...              7
3         4  Dear Local Newspaper, @CAPS1 I have found that...             10
4         5  Dear @LOCATION1, I know having computers has a...              8

In [15]:
set1['essay'] = set1['essay'].str.replace('\n',' ')
set1['essay'] = set1['essay'].str.strip()
set1.head()

   essay_id                                              essay  domain1_score
0         1  Dear local newspaper, I think effects computer...              8
1         2  Dear @CAPS1 @CAPS2, I believe that using compu...              9
2         3  Dear, @CAPS1 @CAPS2 @CAPS3 More and more peopl...              7
3         4  Dear Local Newspaper, @CAPS1 I have found that...             10
4         5  Dear @LOCATION1, I know having computers has a...              8

In [16]:
set1['domain1_score'].value_counts().sort_index()

domain1_score
2      10
3       1
4      17
5      17
6     110
7     135
8     687
9     334
10    316
11    109
12     47
Name: count, dtype: int64

In [18]:
def categorize(score):
    if score <= 5:
        return "Low"
    elif score <= 8:
        return "Medium"
    else:
        return "High"

set1['score_category'] = set1['domain1_score'].apply(categorize)
set1[['domain1_score','score_category']].head()

   domain1_score score_category
0              8         Medium
1              9           High
2              7         Medium
3             10           High
4              8         Medium

In [19]:
cal_low = set1[set1['score_category'] == 'Low'].sample(2, random_state=42)
cal_med = set1[set1['score_category'] == 'Medium'].sample(2, random_state=42)
cal_high = set1[set1['score_category'] == 'High'].sample(2, random_state=42)

calibration = pd.concat([cal_low, cal_med, cal_high]).sample(frac=1, random_state=42).reset_index(drop=True)
calibration

,essay_id,essay,domain1_score,score_category
0,1592,The computers are cool. Do you now I werpsite ...,2,Low
1,995,"I think computers are good, because some peopl...",4,Low
2,686,"Dear local newspaper, I would like to speak up...",9,High
3,1572,"Dear to @CAPS1 this @MONTH1 concern, Computers...",8,Medium
4,1567,"Dear @ORGANIZATION1, @DATE1, everywhere you lo...",11,High
5,146,Dear local newspaper I think that usieng compu...,6,Medium

In [20]:
demo = set1.drop(calibration.index, errors='ignore').sample(5, random_state=42).reset_index(drop=True)

demo

,essay_id,essay,domain1_score,score_category
0,72,"Hello, I decided to write in to the paper on t...",10,High
1,950,Each year the world becomes more and more adva...,10,High
2,841,"Dear local Newspaper, Computers don't take exe...",7,Medium
3,1710,Wouldn't you agree that computers have a great...,9,High
4,808,"Hello @CAPS1 @CAPS2, @CAPS3 you think computer...",7,Medium

In [21]:
def format_calibration_examples(calibration_df):
    examples = ""
    for i, row in calibration_df.iterrows():
        examples += f"""
Calibration Example {i+1}

Essay:
{row['essay']}

Human Score: {row['domain1_score']}
Category: {row['score_category']}
"""
    return examples

calibration_text = format_calibration_examples(calibration)
print(calibration_text)

Calibration Example 1

Essay:
The computers are cool. Do you now I werpsite is @NUM1.com. We nede to time the lemt lo-menteno it. I love the compueters. We nede @NUM2 make a computers are grene compurers.

Human Score: 2
Category: Low

Calibration Example 2

Essay:
I think computers are good, because some people dont have phones so @CAPS1 a good way to conect with people you know, also meet new people. Second some people are going to collage when there done with high school so you could just look on the computers and find one you like and pricess, also find ways there. Third reason is ahopping if a holiday is coming up you could check online and find stuff for cheap and nice to you. You could also order it to your house online if you dont got alot of time to go shopping. @CAPS1 some reasons why I think online is good you could chat, find places and pricess, collages and also shop online @CAPS1 why online is good.

Human Score: 4
Category: Low

Calibration Example 3

Essay:
Dear local newspaper, I would like to speak upon the topic of the effects that computers have on people. My opion on this topic is that computers do have an effect on people. Most people while surfing the internet don't keep track of time. What I mean when I say most people lose track of time is that, they try to keep track of the time but while on the web something @MONTH1 pop that catches their intrest and at that same time there focus is on something else. Some of the other effects computers can have on people is keeping them in the house. When many people are on the web they tend not to excersise as much. When in the house on the web most people that excersise stop excersising. The reason why this occurs is because while people are on the computer chair you feel so relaxed and calm that you don't want to get up. This leads into eating unhealthy foods. Some such as chips, donuts, twinkies and etc. Some @CAPS1 do not believe that is an opinion. The reason I say this is because while watching television the other day I saw a commercial that said quote "@CAPS2 that are more active are healthier than @CAPS2 that stay on the computer all day. Most @CAPS1 do gain weight on the computer because they are not physically active. Not being physically active can lead to A) obesity @CAPS4) cloged arteries or @CAPS5) lazyness. It can lead to all three because those are the effects of being on a computer every of the day. Most @CAPS1 should be enjoying nature instead of staying on the computer. There is a lot more to life than being on the web. Some such as playing sports. Not only is playing sports fun but at the same tim it is also healthy. Would you rather live to @NUM1 or live to @NUM2. And so local newspaper that is why I am writing you this letter today. I mean would you rather have friends @CAPS2 or be lonely. There are weight surgerys but those can rack up to thousands of dollars. And yes weight loss surgery does have effects such as death. So come on @LOCATION1 its your decison and remember the most important part of this letter which is between liveing healthy and young or dieing unhealthy and suffer. Its your choice @LOCATION1 decide.

Human Score: 9
Category: High

Calibration Example 4

Essay:
Dear to @CAPS1 this @MONTH1 concern, Computers do a whole lot now of days. You can play games, do homework, socialize but don't you think there are better things than that. Such as exercising, enjoying the beauty of nature, and most importantly interacting with family and friends. These are all the things that computers take away from people. Once you get onto a computer you never want to get off. If you look at it, it doesn't take much work and energy to use a computer. So if you eat and use the computer all day your not really burning any calories therefore you will gain weight. Computers make people feel lazy sometimes therefore they spend less time exercising. That is not good for your health at all. Exercising gives you energy and is good for you. Have you ever looked out the window and saw how beautiful nature is? When your on the computer chit-chatting with people and playing online friends do you think about what your missing. Everytime I use the computer I wish I could be outside playing and enjoying nature. Trees, flowers, plants, grass and lots of other things are what make up the earth, but some people don't apreciate those things. So next time your on the computer think about that. While your on the computer wasting time there is another homeless child wandering maybe looking for their family. Would you like to be that child who doesnt have a family or any type of friends? Lots of people think of their life without a family but it can happen anyday. So I believe instead of wasting time on the computer we should go and interact with family and friends. Even if its just having a conversation do it, maybe it can show them that you really care. In conclusion, I think that computers are a waste of time. I understand how people say it is used to comunicate with people but back then they didnt have computers and they communicated so we can to. Computes make you spend less time exercising, keeps you from enjoying nature and lastly interacting with family and friends. You won't go wrong if you listen to someone who uses a computer everyday.

Human Score: 8
Category: Medium

Calibration Example 5

Essay:
Dear @ORGANIZATION1, @DATE1, everywhere you look technology is being exercised and it is beneficial to many aspects in our lives @DATE1. Many engineers strive to improve on technologic devices popularity, while others use it in communicate or relax. study conducted by @ORGANIZATION2 university, the computer is the most largely operated machine. The computer positively contributes to our education, economy, and entertainment. As i mentioned before the computer is beneficial to our education. An example of this is the school i attend, middle school. Here at we have over @NUM1 computers in use throughout the school day. These computers help the students complete research papers, typed assignments and other teacher requirement papers. By using the computer to complete research papers students save hours of scanning through books in the library and money on reading books. In addition, computers teachers in organizing files and entering grades online so students can check their. This is beneficial considering the amount of and assignments graded each week. Moreover, a computer called the "parent portal" allows the students to stay connected with school events that would not be mentioned otherwise in all, computer are way of. Besides education computers touch upon our economy as well. Now, due to the wide variety of computer selection, a computer is affordable, starting at prices as low as sixty dollars! This is a positive aspect of the computer because currently the has been enduring the economy since the depression in the. Consequently, the reason has made families start to cut many useful technologe devices out of the. However, since the price of computers decreased purchase have stimulating. Also, the computer has mainly improved methods of. Instead of listening to a cd player you can download listen to while chatting online with friends. This is very helpful for last-minute plan changes, because for those who do not own a telephone, communication @MONTH1 be, negatively affecting your time of entertainment. In addition, children can use internet in order to play games to take that mind off of a hard day at school, or an adult's rough work computersin producing the you watch at home on the couch and the videogame you ordered off of ebay. From facebook and myspace, to and "gone with the wind." Computers create a relaxing entertainment opportunity.

Human Score: 11
Category: High

Calibration Example 6

Essay:
Dear local newspaper I think that usieng computers help people becuse if we did not have computers we would not now ehey thing about eneyone or eneything like all of the @CAPS1 I would not now eneything about them but with computers I know alot about them and there lives like @CAPS2 @CAPS3 @CAPS4 got shot in the back of the head and. @CAPS4 got shot to and I know alot about the @ORGANIZATION1 there white people that to fear in to black people and the same with the wars like world @NUM1 and world @NUM2 and the @CAPS5 and @PERSON1 and the @CAPS6 war there was like plain spy palin flying across @LOCATION1 and they shot him down becuse we were trying to see if thay had eney nuculer bombs offer there. And the same with google and yahoo with google you can type in eneything and you will get a answer and most liked a corect answer yahoo and google is great for some worke and products end studying becuse you then you do to and that I think that computer are good.

Human Score: 6
Category: Medium

In [22]:
demo_essay = demo.iloc[0]['essay']
print(demo_essay)

Hello, I decided to write in to the paper on the topic of computers, and how they benefit society. Comuters are powerful machines, and can be used completing otherwise menial and boring tasks. They benefit people in many ways, like they are very useful in buissness, helpful in education, and connect friends and family together. Computers are uselful in buissness and are an extremely important tool in a common workplace today, and make work get done much more efficiently than if they didn't have computers. One reason Computers are so useful in the workplace is because computers can storee far more data that can be put on paper. Also, they can do jobs and processes very quickly, which is important in the workplace. They can also be used for sending important information quickly and without much trouble. These are all valid reasons comuters are beneficial in buissness, and help things get done. Computers are important today's schools and educational programs becasue they can help students work in a more efficient fashion. "@PERCENT1 of all surveyed students said they would rather type a paper for school than write on by hand, and shows that they value them in their education." said @PERSON2, a professor at @ORGANIZATION1. This shows that Computers are important to students, and are used their benefit. In addition to students writing papers, computers are being used by teachers and school systems for grading, attendance records, and more. The teachers at my school are using @CAPS1 @CAPS2, pieces of hardware that are directly connected to computers, and can be used instead of white @CAPS2, and I see that students are getting more involved in class, and focused, because this computer technology is being used. All of these @CAPS3 are reasons computers are helpful in educational proceeses, and should continue to be used. Many people want to be able talk to there friends and family when they are bored, and because of computers and social networking websites, and instant messaging programs, this is made much easier. "@PERCENT2 of teens have at least one sacial networking site they visit on a regular basis." said @PERSON1, a phycologist, who speciaizes in teens, This shows that people use these sites, and that they like them. Families that are separated because one @MONTH1 have moved out of the house recently might want to communicate with one another, and because of computers, they can. There are multiple ways that they could use their computers to keep in touch, like instant messaging systems mentioned before. Being able to communicate with one another makes theses people happy, and benefits society. Overall, being able to communicate through computers is an enjoyable thing for many people, and is important to society today. To conclude, computers contribute to society in ways that make it much better for everyone. Whether it's through helping buissnesses being more efficient, giving students the ability to work faster, and in a way they prefer, or if it's helping people stay in touch, computers are always benefiting society. These machines hardly ever slow people more thant manually doing the work would, and the positive influence they have far outweighs the bad they do.

In [23]:
rubric_text = """
Essay Prompt:
Write a letter to your local newspaper stating your opinion on the effects computers have on people and persuade readers to agree with your position.

Rubric:
1 – Undeveloped response with minimal support.
2 – Underdeveloped response with weak reasoning.
3 – Minimally developed argument with limited support.
4 – Adequate argument with some supporting details.
5 – Developed argument with clear reasoning and organization.
6 – Strong persuasive response with well-developed ideas.

Scoring rule:
Two raters assign scores from 1–6.
Final score = sum of both scores.
Final score range: 2–12.
"""

In [24]:
full_prompt = f"""
You are an expert essay grader evaluating student essays.

{rubric_text}

Calibration Examples:
{calibration_text}

Now evaluate the following essay.

Essay:
{demo_essay}

Instructions:
1. Predict the final score between 2 and 12.
2. Predict the category: Low, Medium, or High.
3. Explain your reasoning.

Return your answer in this format:

Final Score:
Category:
Reasoning:
"""

print(full_prompt)

You are an expert essay grader evaluating student essays.


Essay Prompt:
Write a letter to your local newspaper stating your opinion on the effects computers have on people and persuade readers to agree with your position.

Rubric:
1 – Undeveloped response with minimal support.
2 – Underdeveloped response with weak reasoning.
3 – Minimally developed argument with limited support.
4 – Adequate argument with some supporting details.
5 – Developed argument with clear reasoning and organization.
6 – Strong persuasive response with well-developed ideas.

Scoring rule:
Two raters assign scores from 1–6.
Final score = sum of both scores.
Final score range: 2–12.


Calibration Examples:

Calibration Example 1

Essay:
The computers are cool. Do you now I werpsite is @NUM1.com. We nede to time the lemt lo-menteno it. I love the compueters. We nede @NUM2 make a computers are grene compurers.

Human Score: 2
Category: Low

Calibration Example 2

Essay:
I think computers are good, because some people dont have phones so @CAPS1 a good way to conect with people you know, also meet new people. Second some people are going to collage when there done with high school so you could just look on the computers and find one you like and pricess, also find ways there. Third reason is ahopping if a holiday is coming up you could check online and find stuff for cheap and nice to you. You could also order it to your house online if you dont got alot of time to go shopping. @CAPS1 some reasons why I think online is good you could chat, find places and pricess, collages and also shop online @CAPS1 why online is good.

Human Score: 4
Category: Low

Calibration Example 3

Essay:
Dear local newspaper, I would like to speak upon the topic of the effects that computers have on people. My opion on this topic is that computers do have an effect on people. Most people while surfing the internet don't keep track of time. What I mean when I say most people lose track of time is that, they try to keep track of the time but while on the web something @MONTH1 pop that catches their intrest and at that same time there focus is on something else. Some of the other effects computers can have on people is keeping them in the house. When many people are on the web they tend not to excersise as much. When in the house on the web most people that excersise stop excersising. The reason why this occurs is because while people are on the computer chair you feel so relaxed and calm that you don't want to get up. This leads into eating unhealthy foods. Some such as chips, donuts, twinkies and etc. Some @CAPS1 do not believe that is an opinion. The reason I say this is because while watching television the other day I saw a commercial that said quote "@CAPS2 that are more active are healthier than @CAPS2 that stay on the computer all day. Most @CAPS1 do gain weight on the computer because they are not physically active. Not being physically active can lead to A) obesity @CAPS4) cloged arteries or @CAPS5) lazyness. It can lead to all three because those are the effects of being on a computer every of the day. Most @CAPS1 should be enjoying nature instead of staying on the computer. There is a lot more to life than being on the web. Some such as playing sports. Not only is playing sports fun but at the same tim it is also healthy. Would you rather live to @NUM1 or live to @NUM2. And so local newspaper that is why I am writing you this letter today. I mean would you rather have friends @CAPS2 or be lonely. There are weight surgerys but those can rack up to thousands of dollars. And yes weight loss surgery does have effects such as death. So come on @LOCATION1 its your decison and remember the most important part of this letter which is between liveing healthy and young or dieing unhealthy and suffer. Its your choice @LOCATION1 decide.

Human Score: 9
Category: High

Calibration Example 4

Essay:
Dear to @CAPS1 this @MONTH1 concern, Computers do a whole lot now of days. You can play games, do homework, socialize but don't you think there are better things than that. Such as exercising, enjoying the beauty of nature, and most importantly interacting with family and friends. These are all the things that computers take away from people. Once you get onto a computer you never want to get off. If you look at it, it doesn't take much work and energy to use a computer. So if you eat and use the computer all day your not really burning any calories therefore you will gain weight. Computers make people feel lazy sometimes therefore they spend less time exercising. That is not good for your health at all. Exercising gives you energy and is good for you. Have you ever looked out the window and saw how beautiful nature is? When your on the computer chit-chatting with people and playing online friends do you think about what your missing. Everytime I use the computer I wish I could be outside playing and enjoying nature. Trees, flowers, plants, grass and lots of other things are what make up the earth, but some people don't apreciate those things. So next time your on the computer think about that. While your on the computer wasting time there is another homeless child wandering maybe looking for their family. Would you like to be that child who doesnt have a family or any type of friends? Lots of people think of their life without a family but it can happen anyday. So I believe instead of wasting time on the computer we should go and interact with family and friends. Even if its just having a conversation do it, maybe it can show them that you really care. In conclusion, I think that computers are a waste of time. I understand how people say it is used to comunicate with people but back then they didnt have computers and they communicated so we can to. Computes make you spend less time exercising, keeps you from enjoying nature and lastly interacting with family and friends. You won't go wrong if you listen to someone who uses a computer everyday.

Human Score: 8
Category: Medium

Calibration Example 5

Essay:
Dear @ORGANIZATION1, @DATE1, everywhere you look technology is being exercised and it is beneficial to many aspects in our lives @DATE1. Many engineers strive to improve on technologic devices popularity, while others use it in communicate or relax. study conducted by @ORGANIZATION2 university, the computer is the most largely operated machine. The computer positively contributes to our education, economy, and entertainment. As i mentioned before the computer is beneficial to our education. An example of this is the school i attend, middle school. Here at we have over @NUM1 computers in use throughout the school day. These computers help the students complete research papers, typed assignments and other teacher requirement papers. By using the computer to complete research papers students save hours of scanning through books in the library and money on reading books. In addition, computers teachers in organizing files and entering grades online so students can check their. This is beneficial considering the amount of and assignments graded each week. Moreover, a computer called the "parent portal" allows the students to stay connected with school events that would not be mentioned otherwise in all, computer are way of. Besides education computers touch upon our economy as well. Now, due to the wide variety of computer selection, a computer is affordable, starting at prices as low as sixty dollars! This is a positive aspect of the computer because currently the has been enduring the economy since the depression in the. Consequently, the reason has made families start to cut many useful technologe devices out of the. However, since the price of computers decreased purchase have stimulating. Also, the computer has mainly improved methods of. Instead of listening to a cd player you can download listen to while chatting online with friends. This is very helpful for last-minute plan changes, because for those who do not own a telephone, communication @MONTH1 be, negatively affecting your time of entertainment. In addition, children can use internet in order to play games to take that mind off of a hard day at school, or an adult's rough work computersin producing the you watch at home on the couch and the videogame you ordered off of ebay. From facebook and myspace, to and "gone with the wind." Computers create a relaxing entertainment opportunity.

Human Score: 11
Category: High

Calibration Example 6

Essay:
Dear local newspaper I think that usieng computers help people becuse if we did not have computers we would not now ehey thing about eneyone or eneything like all of the @CAPS1 I would not now eneything about them but with computers I know alot about them and there lives like @CAPS2 @CAPS3 @CAPS4 got shot in the back of the head and. @CAPS4 got shot to and I know alot about the @ORGANIZATION1 there white people that to fear in to black people and the same with the wars like world @NUM1 and world @NUM2 and the @CAPS5 and @PERSON1 and the @CAPS6 war there was like plain spy palin flying across @LOCATION1 and they shot him down becuse we were trying to see if thay had eney nuculer bombs offer there. And the same with google and yahoo with google you can type in eneything and you will get a answer and most liked a corect answer yahoo and google is great for some worke and products end studying becuse you then you do to and that I think that computer are good.

Human Score: 6
Category: Medium


Now evaluate the following essay.

Essay:
Hello, I decided to write in to the paper on the topic of computers, and how they benefit society. Comuters are powerful machines, and can be used completing otherwise menial and boring tasks. They benefit people in many ways, like they are very useful in buissness, helpful in education, and connect friends and family together. Computers are uselful in buissness and are an extremely important tool in a common workplace today, and make work get done much more efficiently than if they didn't have computers. One reason Computers are so useful in the workplace is because computers can storee far more data that can be put on paper. Also, they can do jobs and processes very quickly, which is important in the workplace. They can also be used for sending important information quickly and without much trouble. These are all valid reasons comuters are beneficial in buissness, and help things get done. Computers are important today's schools and educational programs becasue they can help students work in a more efficient fashion. "@PERCENT1 of all surveyed students said they would rather type a paper for school than write on by hand, and shows that they value them in their education." said @PERSON2, a professor at @ORGANIZATION1. This shows that Computers are important to students, and are used their benefit. In addition to students writing papers, computers are being used by teachers and school systems for grading, attendance records, and more. The teachers at my school are using @CAPS1 @CAPS2, pieces of hardware that are directly connected to computers, and can be used instead of white @CAPS2, and I see that students are getting more involved in class, and focused, because this computer technology is being used. All of these @CAPS3 are reasons computers are helpful in educational proceeses, and should continue to be used. Many people want to be able talk to there friends and family when they are bored, and because of computers and social networking websites, and instant messaging programs, this is made much easier. "@PERCENT2 of teens have at least one sacial networking site they visit on a regular basis." said @PERSON1, a phycologist, who speciaizes in teens, This shows that people use these sites, and that they like them. Families that are separated because one @MONTH1 have moved out of the house recently might want to communicate with one another, and because of computers, they can. There are multiple ways that they could use their computers to keep in touch, like instant messaging systems mentioned before. Being able to communicate with one another makes theses people happy, and benefits society. Overall, being able to communicate through computers is an enjoyable thing for many people, and is important to society today. To conclude, computers contribute to society in ways that make it much better for everyone. Whether it's through helping buissnesses being more efficient, giving students the ability to work faster, and in a way they prefer, or if it's helping people stay in touch, computers are always benefiting society. These machines hardly ever slow people more thant manually doing the work would, and the positive influence they have far outweighs the bad they do.

Instructions:
1. Predict the final score between 2 and 12.
2. Predict the category: Low, Medium, or High.
3. Explain your reasoning.

Return your answer in this format:

Final Score:
Category:
Reasoning:

In [25]:
def build_prompt(essay_text):
    return f"""
You are an expert essay grader evaluating student essays.

{rubric_text}

Calibration Examples:
{calibration_text}

Now evaluate the following essay.

Essay:
{essay_text}

Instructions:
1. Predict the final score between 2 and 12.
2. Predict the category: Low, Medium, or High.
3. Explain your reasoning.
4. Base your explanation only on details actually present in the essay.

Return your answer in this format:

Final Score:
Category:
Reasoning:
"""

In [26]:
def build_prompt(essay_text):
    return f"""
You are an expert essay grader evaluating student essays.

{rubric_text}

Calibration Examples:
{calibration_text}

Now evaluate the following essay.

Essay:
{essay_text}

Instructions:
1. Predict the final score between 2 and 12.
2. Predict the category: Low, Medium, or High.
3. Explain your reasoning.
4. Base your explanation only on details actually present in the essay.

Return your answer in this format:

Final Score:
Category:
Reasoning:
"""

In [27]:
demo['full_prompt'] = demo['essay'].apply(build_prompt)

In [28]:
print(demo.loc[0, 'full_prompt'])

You are an expert essay grader evaluating student essays.


Essay Prompt:
Write a letter to your local newspaper stating your opinion on the effects computers have on people and persuade readers to agree with your position.

Rubric:
1 – Undeveloped response with minimal support.
2 – Underdeveloped response with weak reasoning.
3 – Minimally developed argument with limited support.
4 – Adequate argument with some supporting details.
5 – Developed argument with clear reasoning and organization.
6 – Strong persuasive response with well-developed ideas.

Scoring rule:
Two raters assign scores from 1–6.
Final score = sum of both scores.
Final score range: 2–12.


Calibration Examples:

Calibration Example 1

Essay:
The computers are cool. Do you now I werpsite is @NUM1.com. We nede to time the lemt lo-menteno it. I love the compueters. We nede @NUM2 make a computers are grene compurers.

Human Score: 2
Category: Low

Calibration Example 2

Essay:
I think computers are good, because some people dont have phones so @CAPS1 a good way to conect with people you know, also meet new people. Second some people are going to collage when there done with high school so you could just look on the computers and find one you like and pricess, also find ways there. Third reason is ahopping if a holiday is coming up you could check online and find stuff for cheap and nice to you. You could also order it to your house online if you dont got alot of time to go shopping. @CAPS1 some reasons why I think online is good you could chat, find places and pricess, collages and also shop online @CAPS1 why online is good.

Human Score: 4
Category: Low

Calibration Example 3

Essay:
Dear local newspaper, I would like to speak upon the topic of the effects that computers have on people. My opion on this topic is that computers do have an effect on people. Most people while surfing the internet don't keep track of time. What I mean when I say most people lose track of time is that, they try to keep track of the time but while on the web something @MONTH1 pop that catches their intrest and at that same time there focus is on something else. Some of the other effects computers can have on people is keeping them in the house. When many people are on the web they tend not to excersise as much. When in the house on the web most people that excersise stop excersising. The reason why this occurs is because while people are on the computer chair you feel so relaxed and calm that you don't want to get up. This leads into eating unhealthy foods. Some such as chips, donuts, twinkies and etc. Some @CAPS1 do not believe that is an opinion. The reason I say this is because while watching television the other day I saw a commercial that said quote "@CAPS2 that are more active are healthier than @CAPS2 that stay on the computer all day. Most @CAPS1 do gain weight on the computer because they are not physically active. Not being physically active can lead to A) obesity @CAPS4) cloged arteries or @CAPS5) lazyness. It can lead to all three because those are the effects of being on a computer every of the day. Most @CAPS1 should be enjoying nature instead of staying on the computer. There is a lot more to life than being on the web. Some such as playing sports. Not only is playing sports fun but at the same tim it is also healthy. Would you rather live to @NUM1 or live to @NUM2. And so local newspaper that is why I am writing you this letter today. I mean would you rather have friends @CAPS2 or be lonely. There are weight surgerys but those can rack up to thousands of dollars. And yes weight loss surgery does have effects such as death. So come on @LOCATION1 its your decison and remember the most important part of this letter which is between liveing healthy and young or dieing unhealthy and suffer. Its your choice @LOCATION1 decide.

Human Score: 9
Category: High

Calibration Example 4

Essay:
Dear to @CAPS1 this @MONTH1 concern, Computers do a whole lot now of days. You can play games, do homework, socialize but don't you think there are better things than that. Such as exercising, enjoying the beauty of nature, and most importantly interacting with family and friends. These are all the things that computers take away from people. Once you get onto a computer you never want to get off. If you look at it, it doesn't take much work and energy to use a computer. So if you eat and use the computer all day your not really burning any calories therefore you will gain weight. Computers make people feel lazy sometimes therefore they spend less time exercising. That is not good for your health at all. Exercising gives you energy and is good for you. Have you ever looked out the window and saw how beautiful nature is? When your on the computer chit-chatting with people and playing online friends do you think about what your missing. Everytime I use the computer I wish I could be outside playing and enjoying nature. Trees, flowers, plants, grass and lots of other things are what make up the earth, but some people don't apreciate those things. So next time your on the computer think about that. While your on the computer wasting time there is another homeless child wandering maybe looking for their family. Would you like to be that child who doesnt have a family or any type of friends? Lots of people think of their life without a family but it can happen anyday. So I believe instead of wasting time on the computer we should go and interact with family and friends. Even if its just having a conversation do it, maybe it can show them that you really care. In conclusion, I think that computers are a waste of time. I understand how people say it is used to comunicate with people but back then they didnt have computers and they communicated so we can to. Computes make you spend less time exercising, keeps you from enjoying nature and lastly interacting with family and friends. You won't go wrong if you listen to someone who uses a computer everyday.

Human Score: 8
Category: Medium

Calibration Example 5

Essay:
Dear @ORGANIZATION1, @DATE1, everywhere you look technology is being exercised and it is beneficial to many aspects in our lives @DATE1. Many engineers strive to improve on technologic devices popularity, while others use it in communicate or relax. study conducted by @ORGANIZATION2 university, the computer is the most largely operated machine. The computer positively contributes to our education, economy, and entertainment. As i mentioned before the computer is beneficial to our education. An example of this is the school i attend, middle school. Here at we have over @NUM1 computers in use throughout the school day. These computers help the students complete research papers, typed assignments and other teacher requirement papers. By using the computer to complete research papers students save hours of scanning through books in the library and money on reading books. In addition, computers teachers in organizing files and entering grades online so students can check their. This is beneficial considering the amount of and assignments graded each week. Moreover, a computer called the "parent portal" allows the students to stay connected with school events that would not be mentioned otherwise in all, computer are way of. Besides education computers touch upon our economy as well. Now, due to the wide variety of computer selection, a computer is affordable, starting at prices as low as sixty dollars! This is a positive aspect of the computer because currently the has been enduring the economy since the depression in the. Consequently, the reason has made families start to cut many useful technologe devices out of the. However, since the price of computers decreased purchase have stimulating. Also, the computer has mainly improved methods of. Instead of listening to a cd player you can download listen to while chatting online with friends. This is very helpful for last-minute plan changes, because for those who do not own a telephone, communication @MONTH1 be, negatively affecting your time of entertainment. In addition, children can use internet in order to play games to take that mind off of a hard day at school, or an adult's rough work computersin producing the you watch at home on the couch and the videogame you ordered off of ebay. From facebook and myspace, to and "gone with the wind." Computers create a relaxing entertainment opportunity.

Human Score: 11
Category: High

Calibration Example 6

Essay:
Dear local newspaper I think that usieng computers help people becuse if we did not have computers we would not now ehey thing about eneyone or eneything like all of the @CAPS1 I would not now eneything about them but with computers I know alot about them and there lives like @CAPS2 @CAPS3 @CAPS4 got shot in the back of the head and. @CAPS4 got shot to and I know alot about the @ORGANIZATION1 there white people that to fear in to black people and the same with the wars like world @NUM1 and world @NUM2 and the @CAPS5 and @PERSON1 and the @CAPS6 war there was like plain spy palin flying across @LOCATION1 and they shot him down becuse we were trying to see if thay had eney nuculer bombs offer there. And the same with google and yahoo with google you can type in eneything and you will get a answer and most liked a corect answer yahoo and google is great for some worke and products end studying becuse you then you do to and that I think that computer are good.

Human Score: 6
Category: Medium


Now evaluate the following essay.

Essay:
Hello, I decided to write in to the paper on the topic of computers, and how they benefit society. Comuters are powerful machines, and can be used completing otherwise menial and boring tasks. They benefit people in many ways, like they are very useful in buissness, helpful in education, and connect friends and family together. Computers are uselful in buissness and are an extremely important tool in a common workplace today, and make work get done much more efficiently than if they didn't have computers. One reason Computers are so useful in the workplace is because computers can storee far more data that can be put on paper. Also, they can do jobs and processes very quickly, which is important in the workplace. They can also be used for sending important information quickly and without much trouble. These are all valid reasons comuters are beneficial in buissness, and help things get done. Computers are important today's schools and educational programs becasue they can help students work in a more efficient fashion. "@PERCENT1 of all surveyed students said they would rather type a paper for school than write on by hand, and shows that they value them in their education." said @PERSON2, a professor at @ORGANIZATION1. This shows that Computers are important to students, and are used their benefit. In addition to students writing papers, computers are being used by teachers and school systems for grading, attendance records, and more. The teachers at my school are using @CAPS1 @CAPS2, pieces of hardware that are directly connected to computers, and can be used instead of white @CAPS2, and I see that students are getting more involved in class, and focused, because this computer technology is being used. All of these @CAPS3 are reasons computers are helpful in educational proceeses, and should continue to be used. Many people want to be able talk to there friends and family when they are bored, and because of computers and social networking websites, and instant messaging programs, this is made much easier. "@PERCENT2 of teens have at least one sacial networking site they visit on a regular basis." said @PERSON1, a phycologist, who speciaizes in teens, This shows that people use these sites, and that they like them. Families that are separated because one @MONTH1 have moved out of the house recently might want to communicate with one another, and because of computers, they can. There are multiple ways that they could use their computers to keep in touch, like instant messaging systems mentioned before. Being able to communicate with one another makes theses people happy, and benefits society. Overall, being able to communicate through computers is an enjoyable thing for many people, and is important to society today. To conclude, computers contribute to society in ways that make it much better for everyone. Whether it's through helping buissnesses being more efficient, giving students the ability to work faster, and in a way they prefer, or if it's helping people stay in touch, computers are always benefiting society. These machines hardly ever slow people more thant manually doing the work would, and the positive influence they have far outweighs the bad they do.

Instructions:
1. Predict the final score between 2 and 12.
2. Predict the category: Low, Medium, or High.
3. Explain your reasoning.
4. Base your explanation only on details actually present in the essay.

Return your answer in this format:

Final Score:
Category:
Reasoning:

In [29]:
print(demo.loc[1, 'full_prompt'])

You are an expert essay grader evaluating student essays.


Essay Prompt:
Write a letter to your local newspaper stating your opinion on the effects computers have on people and persuade readers to agree with your position.

Rubric:
1 – Undeveloped response with minimal support.
2 – Underdeveloped response with weak reasoning.
3 – Minimally developed argument with limited support.
4 – Adequate argument with some supporting details.
5 – Developed argument with clear reasoning and organization.
6 – Strong persuasive response with well-developed ideas.

Scoring rule:
Two raters assign scores from 1–6.
Final score = sum of both scores.
Final score range: 2–12.


Calibration Examples:

Calibration Example 1

Essay:
The computers are cool. Do you now I werpsite is @NUM1.com. We nede to time the lemt lo-menteno it. I love the compueters. We nede @NUM2 make a computers are grene compurers.

Human Score: 2
Category: Low

Calibration Example 2

Essay:
I think computers are good, because some people dont have phones so @CAPS1 a good way to conect with people you know, also meet new people. Second some people are going to collage when there done with high school so you could just look on the computers and find one you like and pricess, also find ways there. Third reason is ahopping if a holiday is coming up you could check online and find stuff for cheap and nice to you. You could also order it to your house online if you dont got alot of time to go shopping. @CAPS1 some reasons why I think online is good you could chat, find places and pricess, collages and also shop online @CAPS1 why online is good.

Human Score: 4
Category: Low

Calibration Example 3

Essay:
Dear local newspaper, I would like to speak upon the topic of the effects that computers have on people. My opion on this topic is that computers do have an effect on people. Most people while surfing the internet don't keep track of time. What I mean when I say most people lose track of time is that, they try to keep track of the time but while on the web something @MONTH1 pop that catches their intrest and at that same time there focus is on something else. Some of the other effects computers can have on people is keeping them in the house. When many people are on the web they tend not to excersise as much. When in the house on the web most people that excersise stop excersising. The reason why this occurs is because while people are on the computer chair you feel so relaxed and calm that you don't want to get up. This leads into eating unhealthy foods. Some such as chips, donuts, twinkies and etc. Some @CAPS1 do not believe that is an opinion. The reason I say this is because while watching television the other day I saw a commercial that said quote "@CAPS2 that are more active are healthier than @CAPS2 that stay on the computer all day. Most @CAPS1 do gain weight on the computer because they are not physically active. Not being physically active can lead to A) obesity @CAPS4) cloged arteries or @CAPS5) lazyness. It can lead to all three because those are the effects of being on a computer every of the day. Most @CAPS1 should be enjoying nature instead of staying on the computer. There is a lot more to life than being on the web. Some such as playing sports. Not only is playing sports fun but at the same tim it is also healthy. Would you rather live to @NUM1 or live to @NUM2. And so local newspaper that is why I am writing you this letter today. I mean would you rather have friends @CAPS2 or be lonely. There are weight surgerys but those can rack up to thousands of dollars. And yes weight loss surgery does have effects such as death. So come on @LOCATION1 its your decison and remember the most important part of this letter which is between liveing healthy and young or dieing unhealthy and suffer. Its your choice @LOCATION1 decide.

Human Score: 9
Category: High

Calibration Example 4

Essay:
Dear to @CAPS1 this @MONTH1 concern, Computers do a whole lot now of days. You can play games, do homework, socialize but don't you think there are better things than that. Such as exercising, enjoying the beauty of nature, and most importantly interacting with family and friends. These are all the things that computers take away from people. Once you get onto a computer you never want to get off. If you look at it, it doesn't take much work and energy to use a computer. So if you eat and use the computer all day your not really burning any calories therefore you will gain weight. Computers make people feel lazy sometimes therefore they spend less time exercising. That is not good for your health at all. Exercising gives you energy and is good for you. Have you ever looked out the window and saw how beautiful nature is? When your on the computer chit-chatting with people and playing online friends do you think about what your missing. Everytime I use the computer I wish I could be outside playing and enjoying nature. Trees, flowers, plants, grass and lots of other things are what make up the earth, but some people don't apreciate those things. So next time your on the computer think about that. While your on the computer wasting time there is another homeless child wandering maybe looking for their family. Would you like to be that child who doesnt have a family or any type of friends? Lots of people think of their life without a family but it can happen anyday. So I believe instead of wasting time on the computer we should go and interact with family and friends. Even if its just having a conversation do it, maybe it can show them that you really care. In conclusion, I think that computers are a waste of time. I understand how people say it is used to comunicate with people but back then they didnt have computers and they communicated so we can to. Computes make you spend less time exercising, keeps you from enjoying nature and lastly interacting with family and friends. You won't go wrong if you listen to someone who uses a computer everyday.

Human Score: 8
Category: Medium

Calibration Example 5

Essay:
Dear @ORGANIZATION1, @DATE1, everywhere you look technology is being exercised and it is beneficial to many aspects in our lives @DATE1. Many engineers strive to improve on technologic devices popularity, while others use it in communicate or relax. study conducted by @ORGANIZATION2 university, the computer is the most largely operated machine. The computer positively contributes to our education, economy, and entertainment. As i mentioned before the computer is beneficial to our education. An example of this is the school i attend, middle school. Here at we have over @NUM1 computers in use throughout the school day. These computers help the students complete research papers, typed assignments and other teacher requirement papers. By using the computer to complete research papers students save hours of scanning through books in the library and money on reading books. In addition, computers teachers in organizing files and entering grades online so students can check their. This is beneficial considering the amount of and assignments graded each week. Moreover, a computer called the "parent portal" allows the students to stay connected with school events that would not be mentioned otherwise in all, computer are way of. Besides education computers touch upon our economy as well. Now, due to the wide variety of computer selection, a computer is affordable, starting at prices as low as sixty dollars! This is a positive aspect of the computer because currently the has been enduring the economy since the depression in the. Consequently, the reason has made families start to cut many useful technologe devices out of the. However, since the price of computers decreased purchase have stimulating. Also, the computer has mainly improved methods of. Instead of listening to a cd player you can download listen to while chatting online with friends. This is very helpful for last-minute plan changes, because for those who do not own a telephone, communication @MONTH1 be, negatively affecting your time of entertainment. In addition, children can use internet in order to play games to take that mind off of a hard day at school, or an adult's rough work computersin producing the you watch at home on the couch and the videogame you ordered off of ebay. From facebook and myspace, to and "gone with the wind." Computers create a relaxing entertainment opportunity.

Human Score: 11
Category: High

Calibration Example 6

Essay:
Dear local newspaper I think that usieng computers help people becuse if we did not have computers we would not now ehey thing about eneyone or eneything like all of the @CAPS1 I would not now eneything about them but with computers I know alot about them and there lives like @CAPS2 @CAPS3 @CAPS4 got shot in the back of the head and. @CAPS4 got shot to and I know alot about the @ORGANIZATION1 there white people that to fear in to black people and the same with the wars like world @NUM1 and world @NUM2 and the @CAPS5 and @PERSON1 and the @CAPS6 war there was like plain spy palin flying across @LOCATION1 and they shot him down becuse we were trying to see if thay had eney nuculer bombs offer there. And the same with google and yahoo with google you can type in eneything and you will get a answer and most liked a corect answer yahoo and google is great for some worke and products end studying becuse you then you do to and that I think that computer are good.

Human Score: 6
Category: Medium


Now evaluate the following essay.

Essay:
Each year the world becomes more and more advance in technology. Technology helps and benefits us all in a good positive way. Computers are apart of this positive technology and definetely benefits society. Computers help us look up places and things we never seen before and teaches us about them, too. In addition, computers have a positive impact on families and benefits them greatly. Also, they help people from adults years out of college to teenagers in high school communicate with their friends. Therefore, computers help us all in some little way and makes life easier and more fun. To begin with computers helps us expand our knowledge. It us helps us look up facts or recent news quickly. For example, just recently the @DATE1 @CAPS1 occured and they usualy go late into the night so I didn't get to see the whole competition. I could just easily go look it up on the computer to see who won which medals. computers helped me by looking up the medals quick so I woudn't have to wonder who won a medals not. Computers help us expand our knowledge all the time. They help us look up facts for report, places we want to travel to, learn about the benefits of a certain pet and the posibilities can be endless. to continue with, computers help families by bringing them closer in a way. A family member could be watching a funny on youtube or @ORGANIZATION1 and could think its so funny that they want their whole family to see it you. In addition, stores sell clothes online now so mother and daugther can sit down together and shop without leaving the house. Computers bring my family together by we rent movies from @LOCATION1 on the computer. It brings us together when choose and pick which movie to rent. Also, it brings us together to have a family movie night. As a result, these things the computer gives brings out discussion in the family and gives a good topic that everyone can relate to and talk about. Another way computers are beneficial is they bring everyone together. There are many ways communicate on the computer these days. There is facebook, twitter, email, aim, and many more. They are all different, but they have one thing in common is to bring old friends and new friends together. For instance my mom just sign on to be in facebook so she can talk to all her old friends from highschool and she found one really good friends who she hasn't seen in ages it made her really happy. Therefore, it shows that computers aren't just for bringing new people together, old ones, too.

Instructions:
1. Predict the final score between 2 and 12.
2. Predict the category: Low, Medium, or High.
3. Explain your reasoning.
4. Base your explanation only on details actually present in the essay.

Return your answer in this format:

Final Score:
Category:
Reasoning:

In [30]:
print(demo.loc[2, 'full_prompt'])

You are an expert essay grader evaluating student essays.


Essay Prompt:
Write a letter to your local newspaper stating your opinion on the effects computers have on people and persuade readers to agree with your position.

Rubric:
1 – Undeveloped response with minimal support.
2 – Underdeveloped response with weak reasoning.
3 – Minimally developed argument with limited support.
4 – Adequate argument with some supporting details.
5 – Developed argument with clear reasoning and organization.
6 – Strong persuasive response with well-developed ideas.

Scoring rule:
Two raters assign scores from 1–6.
Final score = sum of both scores.
Final score range: 2–12.


Calibration Examples:

Calibration Example 1

Essay:
The computers are cool. Do you now I werpsite is @NUM1.com. We nede to time the lemt lo-menteno it. I love the compueters. We nede @NUM2 make a computers are grene compurers.

Human Score: 2
Category: Low

Calibration Example 2

Essay:
I think computers are good, because some people dont have phones so @CAPS1 a good way to conect with people you know, also meet new people. Second some people are going to collage when there done with high school so you could just look on the computers and find one you like and pricess, also find ways there. Third reason is ahopping if a holiday is coming up you could check online and find stuff for cheap and nice to you. You could also order it to your house online if you dont got alot of time to go shopping. @CAPS1 some reasons why I think online is good you could chat, find places and pricess, collages and also shop online @CAPS1 why online is good.

Human Score: 4
Category: Low

Calibration Example 3

Essay:
Dear local newspaper, I would like to speak upon the topic of the effects that computers have on people. My opion on this topic is that computers do have an effect on people. Most people while surfing the internet don't keep track of time. What I mean when I say most people lose track of time is that, they try to keep track of the time but while on the web something @MONTH1 pop that catches their intrest and at that same time there focus is on something else. Some of the other effects computers can have on people is keeping them in the house. When many people are on the web they tend not to excersise as much. When in the house on the web most people that excersise stop excersising. The reason why this occurs is because while people are on the computer chair you feel so relaxed and calm that you don't want to get up. This leads into eating unhealthy foods. Some such as chips, donuts, twinkies and etc. Some @CAPS1 do not believe that is an opinion. The reason I say this is because while watching television the other day I saw a commercial that said quote "@CAPS2 that are more active are healthier than @CAPS2 that stay on the computer all day. Most @CAPS1 do gain weight on the computer because they are not physically active. Not being physically active can lead to A) obesity @CAPS4) cloged arteries or @CAPS5) lazyness. It can lead to all three because those are the effects of being on a computer every of the day. Most @CAPS1 should be enjoying nature instead of staying on the computer. There is a lot more to life than being on the web. Some such as playing sports. Not only is playing sports fun but at the same tim it is also healthy. Would you rather live to @NUM1 or live to @NUM2. And so local newspaper that is why I am writing you this letter today. I mean would you rather have friends @CAPS2 or be lonely. There are weight surgerys but those can rack up to thousands of dollars. And yes weight loss surgery does have effects such as death. So come on @LOCATION1 its your decison and remember the most important part of this letter which is between liveing healthy and young or dieing unhealthy and suffer. Its your choice @LOCATION1 decide.

Human Score: 9
Category: High

Calibration Example 4

Essay:
Dear to @CAPS1 this @MONTH1 concern, Computers do a whole lot now of days. You can play games, do homework, socialize but don't you think there are better things than that. Such as exercising, enjoying the beauty of nature, and most importantly interacting with family and friends. These are all the things that computers take away from people. Once you get onto a computer you never want to get off. If you look at it, it doesn't take much work and energy to use a computer. So if you eat and use the computer all day your not really burning any calories therefore you will gain weight. Computers make people feel lazy sometimes therefore they spend less time exercising. That is not good for your health at all. Exercising gives you energy and is good for you. Have you ever looked out the window and saw how beautiful nature is? When your on the computer chit-chatting with people and playing online friends do you think about what your missing. Everytime I use the computer I wish I could be outside playing and enjoying nature. Trees, flowers, plants, grass and lots of other things are what make up the earth, but some people don't apreciate those things. So next time your on the computer think about that. While your on the computer wasting time there is another homeless child wandering maybe looking for their family. Would you like to be that child who doesnt have a family or any type of friends? Lots of people think of their life without a family but it can happen anyday. So I believe instead of wasting time on the computer we should go and interact with family and friends. Even if its just having a conversation do it, maybe it can show them that you really care. In conclusion, I think that computers are a waste of time. I understand how people say it is used to comunicate with people but back then they didnt have computers and they communicated so we can to. Computes make you spend less time exercising, keeps you from enjoying nature and lastly interacting with family and friends. You won't go wrong if you listen to someone who uses a computer everyday.

Human Score: 8
Category: Medium

Calibration Example 5

Essay:
Dear @ORGANIZATION1, @DATE1, everywhere you look technology is being exercised and it is beneficial to many aspects in our lives @DATE1. Many engineers strive to improve on technologic devices popularity, while others use it in communicate or relax. study conducted by @ORGANIZATION2 university, the computer is the most largely operated machine. The computer positively contributes to our education, economy, and entertainment. As i mentioned before the computer is beneficial to our education. An example of this is the school i attend, middle school. Here at we have over @NUM1 computers in use throughout the school day. These computers help the students complete research papers, typed assignments and other teacher requirement papers. By using the computer to complete research papers students save hours of scanning through books in the library and money on reading books. In addition, computers teachers in organizing files and entering grades online so students can check their. This is beneficial considering the amount of and assignments graded each week. Moreover, a computer called the "parent portal" allows the students to stay connected with school events that would not be mentioned otherwise in all, computer are way of. Besides education computers touch upon our economy as well. Now, due to the wide variety of computer selection, a computer is affordable, starting at prices as low as sixty dollars! This is a positive aspect of the computer because currently the has been enduring the economy since the depression in the. Consequently, the reason has made families start to cut many useful technologe devices out of the. However, since the price of computers decreased purchase have stimulating. Also, the computer has mainly improved methods of. Instead of listening to a cd player you can download listen to while chatting online with friends. This is very helpful for last-minute plan changes, because for those who do not own a telephone, communication @MONTH1 be, negatively affecting your time of entertainment. In addition, children can use internet in order to play games to take that mind off of a hard day at school, or an adult's rough work computersin producing the you watch at home on the couch and the videogame you ordered off of ebay. From facebook and myspace, to and "gone with the wind." Computers create a relaxing entertainment opportunity.

Human Score: 11
Category: High

Calibration Example 6

Essay:
Dear local newspaper I think that usieng computers help people becuse if we did not have computers we would not now ehey thing about eneyone or eneything like all of the @CAPS1 I would not now eneything about them but with computers I know alot about them and there lives like @CAPS2 @CAPS3 @CAPS4 got shot in the back of the head and. @CAPS4 got shot to and I know alot about the @ORGANIZATION1 there white people that to fear in to black people and the same with the wars like world @NUM1 and world @NUM2 and the @CAPS5 and @PERSON1 and the @CAPS6 war there was like plain spy palin flying across @LOCATION1 and they shot him down becuse we were trying to see if thay had eney nuculer bombs offer there. And the same with google and yahoo with google you can type in eneything and you will get a answer and most liked a corect answer yahoo and google is great for some worke and products end studying becuse you then you do to and that I think that computer are good.

Human Score: 6
Category: Medium


Now evaluate the following essay.

Essay:
Dear local Newspaper, Computers don't take exercising, enjoying nature, and no interacting with friends and family away from you. Your family can sey time limits on the computer if they think your. Spending to much time on it. If you have time limits then people will have a certin time they go on and off of the computer. For example a child is on the computer @NUM1 and you can't get them off, time limits will stop that. The child is on a game and if the time limits are on, when your time is done the computer logs off automaticaly. That way your child can't get back on till thier next time. The computer can do many things you can play online games and chat with friends. Chating will let you talk to friends over the computer and you won't need to call them. Online games will still let you talk to your friends but you can have an avatar you can dress up and be creative with. For example an online game can let you chat make friends,

Instructions:
1. Predict the final score between 2 and 12.
2. Predict the category: Low, Medium, or High.
3. Explain your reasoning.
4. Base your explanation only on details actually present in the essay.

Return your answer in this format:

Final Score:
Category:
Reasoning:

In [ ]:
print(demo.loc[3, 'full_prompt'])

You are an expert essay grader evaluating student essays.


Essay Prompt:
Write a letter to your local newspaper stating your opinion on the effects computers have on people and persuade readers to agree with your position.

Rubric:
1 – Undeveloped response with minimal support.
2 – Underdeveloped response with weak reasoning.
3 – Minimally developed argument with limited support.
4 – Adequate argument with some supporting details.
5 – Developed argument with clear reasoning and organization.
6 – Strong persuasive response with well-developed ideas.

Scoring rule:
Two raters assign scores from 1–6.
Final score = sum of both scores.
Final score range: 2–12.


Calibration Examples:

Calibration Example 1

Essay:
The computers are cool. Do you now I werpsite is @NUM1.com. We nede to time the lemt lo-menteno it. I love the compueters. We nede @NUM2 make a computers are grene compurers.

Human Score: 2
Category: Low

Calibration Example 2

Essay:
I think computers are good, because some people dont have phones so @CAPS1 a good way to conect with people you know, also meet new people. Second some people are going to collage when there done with high school so you could just look on the computers and find one you like and pricess, also find ways there. Third reason is ahopping if a holiday is coming up you could check online and find stuff for cheap and nice to you. You could also order it to your house online if you dont got alot of time to go shopping. @CAPS1 some reasons why I think online is good you could chat, find places and pricess, collages and also shop online @CAPS1 why online is good.

Human Score: 4
Category: Low

Calibration Example 3

Essay:
Dear local newspaper, I would like to speak upon the topic of the effects that computers have on people. My opion on this topic is that computers do have an effect on people. Most people while surfing the internet don't keep track of time. What I mean when I say most people lose track of time is that, they try to keep track of the time but while on the web something @MONTH1 pop that catches their intrest and at that same time there focus is on something else. Some of the other effects computers can have on people is keeping them in the house. When many people are on the web they tend not to excersise as much. When in the house on the web most people that excersise stop excersising. The reason why this occurs is because while people are on the computer chair you feel so relaxed and calm that you don't want to get up. This leads into eating unhealthy foods. Some such as chips, donuts, twinkies and etc. Some @CAPS1 do not believe that is an opinion. The reason I say this is because while watching television the other day I saw a commercial that said quote "@CAPS2 that are more active are healthier than @CAPS2 that stay on the computer all day. Most @CAPS1 do gain weight on the computer because they are not physically active. Not being physically active can lead to A) obesity @CAPS4) cloged arteries or @CAPS5) lazyness. It can lead to all three because those are the effects of being on a computer every of the day. Most @CAPS1 should be enjoying nature instead of staying on the computer. There is a lot more to life than being on the web. Some such as playing sports. Not only is playing sports fun but at the same tim it is also healthy. Would you rather live to @NUM1 or live to @NUM2. And so local newspaper that is why I am writing you this letter today. I mean would you rather have friends @CAPS2 or be lonely. There are weight surgerys but those can rack up to thousands of dollars. And yes weight loss surgery does have effects such as death. So come on @LOCATION1 its your decison and remember the most important part of this letter which is between liveing healthy and young or dieing unhealthy and suffer. Its your choice @LOCATION1 decide.

Human Score: 9
Category: High

Calibration Example 4

Essay:
Dear to @CAPS1 this @MONTH1 concern, Computers do a whole lot now of days. You can play games, do homework, socialize but don't you think there are better things than that. Such as exercising, enjoying the beauty of nature, and most importantly interacting with family and friends. These are all the things that computers take away from people. Once you get onto a computer you never want to get off. If you look at it, it doesn't take much work and energy to use a computer. So if you eat and use the computer all day your not really burning any calories therefore you will gain weight. Computers make people feel lazy sometimes therefore they spend less time exercising. That is not good for your health at all. Exercising gives you energy and is good for you. Have you ever looked out the window and saw how beautiful nature is? When your on the computer chit-chatting with people and playing online friends do you think about what your missing. Everytime I use the computer I wish I could be outside playing and enjoying nature. Trees, flowers, plants, grass and lots of other things are what make up the earth, but some people don't apreciate those things. So next time your on the computer think about that. While your on the computer wasting time there is another homeless child wandering maybe looking for their family. Would you like to be that child who doesnt have a family or any type of friends? Lots of people think of their life without a family but it can happen anyday. So I believe instead of wasting time on the computer we should go and interact with family and friends. Even if its just having a conversation do it, maybe it can show them that you really care. In conclusion, I think that computers are a waste of time. I understand how people say it is used to comunicate with people but back then they didnt have computers and they communicated so we can to. Computes make you spend less time exercising, keeps you from enjoying nature and lastly interacting with family and friends. You won't go wrong if you listen to someone who uses a computer everyday.

Human Score: 8
Category: Medium

Calibration Example 5

Essay:
Dear @ORGANIZATION1, @DATE1, everywhere you look technology is being exercised and it is beneficial to many aspects in our lives @DATE1. Many engineers strive to improve on technologic devices popularity, while others use it in communicate or relax. study conducted by @ORGANIZATION2 university, the computer is the most largely operated machine. The computer positively contributes to our education, economy, and entertainment. As i mentioned before the computer is beneficial to our education. An example of this is the school i attend, middle school. Here at we have over @NUM1 computers in use throughout the school day. These computers help the students complete research papers, typed assignments and other teacher requirement papers. By using the computer to complete research papers students save hours of scanning through books in the library and money on reading books. In addition, computers teachers in organizing files and entering grades online so students can check their. This is beneficial considering the amount of and assignments graded each week. Moreover, a computer called the "parent portal" allows the students to stay connected with school events that would not be mentioned otherwise in all, computer are way of. Besides education computers touch upon our economy as well. Now, due to the wide variety of computer selection, a computer is affordable, starting at prices as low as sixty dollars! This is a positive aspect of the computer because currently the has been enduring the economy since the depression in the. Consequently, the reason has made families start to cut many useful technologe devices out of the. However, since the price of computers decreased purchase have stimulating. Also, the computer has mainly improved methods of. Instead of listening to a cd player you can download listen to while chatting online with friends. This is very helpful for last-minute plan changes, because for those who do not own a telephone, communication @MONTH1 be, negatively affecting your time of entertainment. In addition, children can use internet in order to play games to take that mind off of a hard day at school, or an adult's rough work computersin producing the you watch at home on the couch and the videogame you ordered off of ebay. From facebook and myspace, to and "gone with the wind." Computers create a relaxing entertainment opportunity.

Human Score: 11
Category: High

Calibration Example 6

Essay:
Dear local newspaper I think that usieng computers help people becuse if we did not have computers we would not now ehey thing about eneyone or eneything like all of the @CAPS1 I would not now eneything about them but with computers I know alot about them and there lives like @CAPS2 @CAPS3 @CAPS4 got shot in the back of the head and. @CAPS4 got shot to and I know alot about the @ORGANIZATION1 there white people that to fear in to black people and the same with the wars like world @NUM1 and world @NUM2 and the @CAPS5 and @PERSON1 and the @CAPS6 war there was like plain spy palin flying across @LOCATION1 and they shot him down becuse we were trying to see if thay had eney nuculer bombs offer there. And the same with google and yahoo with google you can type in eneything and you will get a answer and most liked a corect answer yahoo and google is great for some worke and products end studying becuse you then you do to and that I think that computer are good.

Human Score: 6
Category: Medium


Now evaluate the following essay.

Essay:
Wouldn't you agree that computers have a great affect on people. The three reason why they have a good affect on people is because, it gives you good typing skills, its educational, and it helps you out with alot of things. The first reason why computers have a good affect on people is because computers help your typing skills. If you have a computer you will soon learn that your typing skills get very good. Each time you use the computer your hands ajust to the keys on the computer. Say if there is someone that wants to work with computers when they get older, well if they practice their typing on their computers at home they will be eligible for the job working with computers. Also computers could be good for the hearing impared. If the hearing impared use to the computers then they can get a @CAPS1 or @CAPS2 and chat with people online. This would be useful to them because since they could not hear what people say they can read what people say through the internet. Another reason why computers have a good affect on people is because they are very educational. In my opinion, computers are very educational because there are alot of websites that teach you facts about different places. For example, what food people eat in different countrys, or where that country is. A website that is the best for finding out accurate facts is www.Ask.com. Ask.com is the best website because it tells you what ever you want to know in a matter of seconds. Computers are also educational when it comes to school projects because of these amazing websites. The last reason why computers have a affect on people is because they help you with alot of things. They help you with alot of things because if you want to know how far @LOCATION2 is from @LOCATION1 then you can go on your pc and find out, or say that you lost the directions to your friends house and your on your way to their house if you brought your labtop you can go on the labtap and find where her house is from your labtop. I know your probably thinking there is such thing as a gps, well if you think about it gps's can be confusing, but your computer reads it out to you. Know your probably saying in your heads why don't you text/call @CAPS3/@CAPS4 if you think about it what if your friend does not talk clearly. In conclusion, wouldn't you agree that computers do have good effects on people. My three arguments are, they help your typing skill educational. They help you with things. please take my ideas into consideration.

Instructions:
1. Predict the final score between 2 and 12.
2. Predict the category: Low, Medium, or High.
3. Explain your reasoning.
4. Base your explanation only on details actually present in the essay.

Return your answer in this format:

Final Score:
Category:
Reasoning:

In [ ]:
print(demo.loc[4, 'full_prompt'])

You are an expert essay grader evaluating student essays.


Essay Prompt:
Write a letter to your local newspaper stating your opinion on the effects computers have on people and persuade readers to agree with your position.

Rubric:
1 – Undeveloped response with minimal support.
2 – Underdeveloped response with weak reasoning.
3 – Minimally developed argument with limited support.
4 – Adequate argument with some supporting details.
5 – Developed argument with clear reasoning and organization.
6 – Strong persuasive response with well-developed ideas.

Scoring rule:
Two raters assign scores from 1–6.
Final score = sum of both scores.
Final score range: 2–12.


Calibration Examples:

Calibration Example 1

Essay:
The computers are cool. Do you now I werpsite is @NUM1.com. We nede to time the lemt lo-menteno it. I love the compueters. We nede @NUM2 make a computers are grene compurers.

Human Score: 2
Category: Low

Calibration Example 2

Essay:
I think computers are good, because some people dont have phones so @CAPS1 a good way to conect with people you know, also meet new people. Second some people are going to collage when there done with high school so you could just look on the computers and find one you like and pricess, also find ways there. Third reason is ahopping if a holiday is coming up you could check online and find stuff for cheap and nice to you. You could also order it to your house online if you dont got alot of time to go shopping. @CAPS1 some reasons why I think online is good you could chat, find places and pricess, collages and also shop online @CAPS1 why online is good.

Human Score: 4
Category: Low

Calibration Example 3

Essay:
Dear local newspaper, I would like to speak upon the topic of the effects that computers have on people. My opion on this topic is that computers do have an effect on people. Most people while surfing the internet don't keep track of time. What I mean when I say most people lose track of time is that, they try to keep track of the time but while on the web something @MONTH1 pop that catches their intrest and at that same time there focus is on something else. Some of the other effects computers can have on people is keeping them in the house. When many people are on the web they tend not to excersise as much. When in the house on the web most people that excersise stop excersising. The reason why this occurs is because while people are on the computer chair you feel so relaxed and calm that you don't want to get up. This leads into eating unhealthy foods. Some such as chips, donuts, twinkies and etc. Some @CAPS1 do not believe that is an opinion. The reason I say this is because while watching television the other day I saw a commercial that said quote "@CAPS2 that are more active are healthier than @CAPS2 that stay on the computer all day. Most @CAPS1 do gain weight on the computer because they are not physically active. Not being physically active can lead to A) obesity @CAPS4) cloged arteries or @CAPS5) lazyness. It can lead to all three because those are the effects of being on a computer every of the day. Most @CAPS1 should be enjoying nature instead of staying on the computer. There is a lot more to life than being on the web. Some such as playing sports. Not only is playing sports fun but at the same tim it is also healthy. Would you rather live to @NUM1 or live to @NUM2. And so local newspaper that is why I am writing you this letter today. I mean would you rather have friends @CAPS2 or be lonely. There are weight surgerys but those can rack up to thousands of dollars. And yes weight loss surgery does have effects such as death. So come on @LOCATION1 its your decison and remember the most important part of this letter which is between liveing healthy and young or dieing unhealthy and suffer. Its your choice @LOCATION1 decide.

Human Score: 9
Category: High

Calibration Example 4

Essay:
Dear to @CAPS1 this @MONTH1 concern, Computers do a whole lot now of days. You can play games, do homework, socialize but don't you think there are better things than that. Such as exercising, enjoying the beauty of nature, and most importantly interacting with family and friends. These are all the things that computers take away from people. Once you get onto a computer you never want to get off. If you look at it, it doesn't take much work and energy to use a computer. So if you eat and use the computer all day your not really burning any calories therefore you will gain weight. Computers make people feel lazy sometimes therefore they spend less time exercising. That is not good for your health at all. Exercising gives you energy and is good for you. Have you ever looked out the window and saw how beautiful nature is? When your on the computer chit-chatting with people and playing online friends do you think about what your missing. Everytime I use the computer I wish I could be outside playing and enjoying nature. Trees, flowers, plants, grass and lots of other things are what make up the earth, but some people don't apreciate those things. So next time your on the computer think about that. While your on the computer wasting time there is another homeless child wandering maybe looking for their family. Would you like to be that child who doesnt have a family or any type of friends? Lots of people think of their life without a family but it can happen anyday. So I believe instead of wasting time on the computer we should go and interact with family and friends. Even if its just having a conversation do it, maybe it can show them that you really care. In conclusion, I think that computers are a waste of time. I understand how people say it is used to comunicate with people but back then they didnt have computers and they communicated so we can to. Computes make you spend less time exercising, keeps you from enjoying nature and lastly interacting with family and friends. You won't go wrong if you listen to someone who uses a computer everyday.

Human Score: 8
Category: Medium

Calibration Example 5

Essay:
Dear @ORGANIZATION1, @DATE1, everywhere you look technology is being exercised and it is beneficial to many aspects in our lives @DATE1. Many engineers strive to improve on technologic devices popularity, while others use it in communicate or relax. study conducted by @ORGANIZATION2 university, the computer is the most largely operated machine. The computer positively contributes to our education, economy, and entertainment. As i mentioned before the computer is beneficial to our education. An example of this is the school i attend, middle school. Here at we have over @NUM1 computers in use throughout the school day. These computers help the students complete research papers, typed assignments and other teacher requirement papers. By using the computer to complete research papers students save hours of scanning through books in the library and money on reading books. In addition, computers teachers in organizing files and entering grades online so students can check their. This is beneficial considering the amount of and assignments graded each week. Moreover, a computer called the "parent portal" allows the students to stay connected with school events that would not be mentioned otherwise in all, computer are way of. Besides education computers touch upon our economy as well. Now, due to the wide variety of computer selection, a computer is affordable, starting at prices as low as sixty dollars! This is a positive aspect of the computer because currently the has been enduring the economy since the depression in the. Consequently, the reason has made families start to cut many useful technologe devices out of the. However, since the price of computers decreased purchase have stimulating. Also, the computer has mainly improved methods of. Instead of listening to a cd player you can download listen to while chatting online with friends. This is very helpful for last-minute plan changes, because for those who do not own a telephone, communication @MONTH1 be, negatively affecting your time of entertainment. In addition, children can use internet in order to play games to take that mind off of a hard day at school, or an adult's rough work computersin producing the you watch at home on the couch and the videogame you ordered off of ebay. From facebook and myspace, to and "gone with the wind." Computers create a relaxing entertainment opportunity.

Human Score: 11
Category: High

Calibration Example 6

Essay:
Dear local newspaper I think that usieng computers help people becuse if we did not have computers we would not now ehey thing about eneyone or eneything like all of the @CAPS1 I would not now eneything about them but with computers I know alot about them and there lives like @CAPS2 @CAPS3 @CAPS4 got shot in the back of the head and. @CAPS4 got shot to and I know alot about the @ORGANIZATION1 there white people that to fear in to black people and the same with the wars like world @NUM1 and world @NUM2 and the @CAPS5 and @PERSON1 and the @CAPS6 war there was like plain spy palin flying across @LOCATION1 and they shot him down becuse we were trying to see if thay had eney nuculer bombs offer there. And the same with google and yahoo with google you can type in eneything and you will get a answer and most liked a corect answer yahoo and google is great for some worke and products end studying becuse you then you do to and that I think that computer are good.

Human Score: 6
Category: Medium


Now evaluate the following essay.

Essay:
Hello @CAPS1 @CAPS2, @CAPS3 you think computers are having a great effect on people? Well, I sure @CAPS3 think using a computer has a great effect on people. I say this because, people are probably waisting a full day on those facebook, myspace gol websites, looking up diffenitions for words, directions to places etc. If you think about it, this effect on people can ruin their eye-site, and social skills. These people are spending like @NUM1 hours tops on the computer. Staring at that @NUM2 inch little screen can damage your eye-site. This can lead you to getting glasses or possibly going blind. How would your life be without not talking to a girl/guy or even your own family? If you waist your time on those websites for example: facebook all you @CAPS3 is instant message the person. Maybe you should go out and @CAPS3 something fun with that person. What's this I hear about map it.com? Don't be lazy and waist @NUM3 minutes at your day just getting directions. Use a a real map! Also, free @LOCATION1? Come on! Use a real dictionary. So, I come to my conclusion by saying that these computers @CAPS3 have a "great effect"on people. It gives them short cuts through life.

Instructions:
1. Predict the final score between 2 and 12.
2. Predict the category: Low, Medium, or High.
3. Explain your reasoning.
4. Base your explanation only on details actually present in the essay.

Return your answer in this format:

Final Score:
Category:
Reasoning:

## CALIBRATION AND RUBRIC ONCE

In [1]:
base_prompt = f"""
You are an expert essay grader evaluating student essays.

{rubric_text}

Calibration Examples:
{calibration_text}

From now on, I will send one essay at a time.

For each essay:
1. Predict the final score between 2 and 12.
2. Predict the category: Low, Medium, or High.
3. Explain your reasoning.

Return your answer in this format:

Final Score:
Category:
Reasoning:
"""

NameError: name 'rubric_text' is not defined