<a href="https://colab.research.google.com/github/MalakSalehh/Thesis-datasets/blob/main/CLEAN_TRIALtitled1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install -q openai pandas numpy scipy scikit-learn

In [1]:
import re
import time
import json
import numpy as np
import pandas as pd

from openai import OpenAI
from sklearn.metrics import cohen_kappa_score, mean_absolute_error
from scipy.stats import pearsonr

In [21]:
!pip install groq

Collecting groq
  Downloading groq-1.1.2-py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: anyio<5,>=3.5.0 in /usr/local/lib/python3.12/dist-packages (from groq) (4.13.0)
Requirement already satisfied: distro<2,>=1.7.0 in /usr/local/lib/python3.12/dist-packages (from groq) (1.9.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from groq) (0.28.1)
Requirement already satisfied: pydantic<3,>=1.9.0 in /usr/local/lib/python3.12/dist-packages (from groq) (2.12.3)
Requirement already satisfied: sniffio in /usr/local/lib/python3.12/dist-packages (from groq) (1.3.1)
Requirement already satisfied: typing-extensions<5,>=4.14 in /usr/local/lib/python3.12/dist-packages (from groq) (4.15.0)
Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.12/dist-packages (from anyio<5,>=3.5.0->groq) (3.11)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->groq) (2026.2.25)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->groq) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->groq) (0.16.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=1.9.0->groq) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=1.9.0->groq) (2.41.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=1.9.0->groq) (0.4.2)
Downloading groq-1.1.2-py3-none-any.whl (141 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 141.7/141.7 kB 4.2 MB/s eta 0:00:00
Installing collected packages: groq
Successfully installed groq-1.1.2

In [2]:
RANDOM_STATE = 42

In [3]:
pip install -U google-genai

Requirement already satisfied: google-genai in /usr/local/lib/python3.12/dist-packages (1.72.0)
Requirement already satisfied: anyio<5.0.0,>=4.8.0 in /usr/local/lib/python3.12/dist-packages (from google-genai) (4.13.0)
Requirement already satisfied: google-auth<3.0.0,>=2.48.1 in /usr/local/lib/python3.12/dist-packages (from google-auth[requests]<3.0.0,>=2.48.1->google-genai) (2.49.2)
Requirement already satisfied: httpx<1.0.0,>=0.28.1 in /usr/local/lib/python3.12/dist-packages (from google-genai) (0.28.1)
Requirement already satisfied: pydantic<3.0.0,>=2.9.0 in /usr/local/lib/python3.12/dist-packages (from google-genai) (2.12.3)
Requirement already satisfied: requests<3.0.0,>=2.28.1 in /usr/local/lib/python3.12/dist-packages (from google-genai) (2.32.4)
Requirement already satisfied: tenacity<9.2.0,>=8.2.3 in /usr/local/lib/python3.12/dist-packages (from google-genai) (9.1.4)
Requirement already satisfied: websockets<17.0,>=13.0.0 in /usr/local/lib/python3.12/dist-packages (from google-genai) (15.0.1)
Requirement already satisfied: typing-extensions<5.0.0,>=4.14.0 in /usr/local/lib/python3.12/dist-packages (from google-genai) (4.15.0)
Requirement already satisfied: distro<2,>=1.7.0 in /usr/local/lib/python3.12/dist-packages (from google-genai) (1.9.0)
Requirement already satisfied: sniffio in /usr/local/lib/python3.12/dist-packages (from google-genai) (1.3.1)
Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.12/dist-packages (from anyio<5.0.0,>=4.8.0->google-genai) (3.11)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.12/dist-packages (from google-auth<3.0.0,>=2.48.1->google-auth[requests]<3.0.0,>=2.48.1->google-genai) (0.4.2)
Requirement already satisfied: cryptography>=38.0.3 in /usr/local/lib/python3.12/dist-packages (from google-auth<3.0.0,>=2.48.1->google-auth[requests]<3.0.0,>=2.48.1->google-genai) (43.0.3)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0,>=0.28.1->google-genai) (2026.2.25)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0,>=0.28.1->google-genai) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1.0.0,>=0.28.1->google-genai) (0.16.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.9.0->google-genai) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.9.0->google-genai) (2.41.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.9.0->google-genai) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.28.1->google-genai) (3.4.6)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.28.1->google-genai) (2.5.0)
Requirement already satisfied: cffi>=1.12 in /usr/local/lib/python3.12/dist-packages (from cryptography>=38.0.3->google-auth<3.0.0,>=2.48.1->google-auth[requests]<3.0.0,>=2.48.1->google-genai) (2.0.0)
Requirement already satisfied: pyasn1<0.7.0,>=0.6.1 in /usr/local/lib/python3.12/dist-packages (from pyasn1-modules>=0.2.1->google-auth<3.0.0,>=2.48.1->google-auth[requests]<3.0.0,>=2.48.1->google-genai) (0.6.3)
Requirement already satisfied: pycparser in /usr/local/lib/python3.12/dist-packages (from cffi>=1.12->cryptography>=38.0.3->google-auth<3.0.0,>=2.48.1->google-auth[requests]<3.0.0,>=2.48.1->google-genai) (3.0)

In [4]:
from google import genai

client = genai.Client(api_key="AIzaSyD1yFzcdq6PDD0gTTQj8S-WI_p1tfzokVg")

In [6]:
def get_response(prompt, model="gemini-3.1-pro-preview"):
    response = client.models.generate_content(
        model=model,
        contents=prompt
    )
    return response.text

In [5]:

url = "https://raw.githubusercontent.com/MalakSalehh/Thesis-datasets/main/training_set_rel3.tsv"
df = pd.read_csv(url, sep="\t", encoding="latin1")

print(df.shape)
df.head()

(12976, 28)

,essay_id,essay_set,essay,rater1_domain1,rater2_domain1,rater3_domain1,domain1_score,rater1_domain2,rater2_domain2,domain2_score,...,rater2_trait3,rater2_trait4,rater2_trait5,rater2_trait6,rater3_trait1,rater3_trait2,rater3_trait3,rater3_trait4,rater3_trait5,rater3_trait6
0,1,1,"Dear local newspaper, I think effects computer...",4,4,NaN,8,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,1,"Dear @CAPS1 @CAPS2, I believe that using compu...",5,4,NaN,9,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,1,"Dear, @CAPS1 @CAPS2 @CAPS3 More and more peopl...",4,3,NaN,7,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,1,"Dear Local Newspaper, @CAPS1 I have found that...",5,5,NaN,10,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,1,"Dear @LOCATION1, I know having computers has a...",4,4,NaN,8,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
set1 = df[df["essay_set"] == 1].copy()
set1 = set1[["essay_id", "essay", "domain1_score"]]

set1["essay"] = set1["essay"].astype(str).str.replace("\n", " ", regex=False).str.strip()

print(set1.shape)
set1.head()

(1783, 3)

   essay_id                                              essay  domain1_score
0         1  Dear local newspaper, I think effects computer...              8
1         2  Dear @CAPS1 @CAPS2, I believe that using compu...              9
2         3  Dear, @CAPS1 @CAPS2 @CAPS3 More and more peopl...              7
3         4  Dear Local Newspaper, @CAPS1 I have found that...             10
4         5  Dear @LOCATION1, I know having computers has a...              8

In [8]:

def categorize(score):
    if score <= 5:
        return "Low"
    elif score <= 8:
        return "Medium"
    else:
        return "High"

set1["score_category"] = set1["domain1_score"].apply(categorize)

set1["domain1_score"].value_counts().sort_index()

domain1_score
2      10
3       1
4      17
5      17
6     110
7     135
8     687
9     334
10    316
11    109
12     47
Name: count, dtype: int64

In [9]:

cal_low = set1[set1["score_category"] == "Low"].sample(2, random_state=RANDOM_STATE)
cal_med = set1[set1["score_category"] == "Medium"].sample(2, random_state=RANDOM_STATE)
cal_high = set1[set1["score_category"] == "High"].sample(2, random_state=RANDOM_STATE)

calibration = pd.concat([cal_low, cal_med, cal_high]).sample(frac=1, random_state=RANDOM_STATE).reset_index(drop=True)
calibration

,essay_id,essay,domain1_score,score_category
0,1592,The computers are cool. Do you now I werpsite ...,2,Low
1,995,"I think computers are good, because some peopl...",4,Low
2,686,"Dear local newspaper, I would like to speak up...",9,High
3,1572,"Dear to @CAPS1 this @MONTH1 concern, Computers...",8,Medium
4,1567,"Dear @ORGANIZATION1, @DATE1, everywhere you lo...",11,High
5,146,Dear local newspaper I think that usieng compu...,6,Medium

In [32]:
calibration_ids = calibration["essay_id"].tolist()

pool = set1[~set1["essay_id"].isin(calibration_ids)].copy().reset_index(drop=True)

# sample 30 essays directly
demo_30 = pool.sample(30, random_state=RANDOM_STATE).reset_index(drop=True)

print("Calibration:", calibration.shape)
print("Demo 30:", demo_30.shape)

Calibration: (6, 4)
Demo 30: (30, 4)

In [11]:
# =========================
# RUBRIC
# =========================

rubric_text = """
Essay Prompt:
Write a letter to your local newspaper stating your opinion on the effects computers have on people and persuade readers to agree with your position.

Rubric:
1 – Undeveloped response with minimal support.
2 – Underdeveloped response with weak reasoning.
3 – Minimally developed argument with limited support.
4 – Adequate argument with some supporting details.
5 – Developed argument with clear reasoning and organization.
6 – Strong persuasive response with well-developed ideas.

Scoring rule:
Two raters assign scores from 1–6.
Final score = sum of both scores.
Final score range: 2–12.
"""

In [12]:
# =========================
# CALIBRATION FORMATTERS
# =========================

def format_calibration_examples(calibration_df):
    examples = ""
    for i, row in calibration_df.iterrows():
        examples += f"""
Calibration Example {i+1}

Essay:
{row['essay']}

Human Score: {row['domain1_score']}
Category: {row['score_category']}
"""
    return examples


def format_calibration_examples_with_id(calibration_df):
    examples = []
    for i, row in enumerate(calibration_df.itertuples(index=False), start=1):
        examples.append(f"""
Calibration Example {i}

Essay ID: {row.essay_id}

Essay:
{row.essay}

Human Score: {row.domain1_score}
Category: {row.score_category}
""")
    return "\n".join(examples)

In [13]:
# create both calibration text versions exactly like the notebook styles
calibration_text = format_calibration_examples(calibration)
calibration_text_with_id = format_calibration_examples_with_id(calibration)

In [14]:
def build_full_prompt(essay_text, rubric_text, calibration_text):
    return f"""
You are an expert essay grader evaluating student essays.

{rubric_text}

Calibration Examples:
{calibration_text}

Now evaluate the following essay.

Essay:
{essay_text}

Instructions:
1. Predict the final score between 2 and 12.
2. Predict the category: Low, Medium, or High.
3. Explain your reasoning.

Return your answer in this format:

Final Score:
Category:
Reasoning:
"""

In [16]:
import re

def extract_final_score(text):
    if not isinstance(text, str):
        return None

    match = re.search(r"Final Score:\s*(\d+)", text, re.IGNORECASE)
    if match:
        score = int(match.group(1))
        score = max(2, min(12, score))   # clip to valid range
        return score
    return None

def extract_category(text):
    if not isinstance(text, str):
        return None

    match = re.search(r"Category:\s*(Low|Medium|High)", text, re.IGNORECASE)
    if match:
        return match.group(1).capitalize()
    return None

In [33]:
results = []

for _, row in demo_30.iterrows():
    essay_id = row["essay_id"]
    essay_text = row["essay"]
    human_score = row["domain1_score"]
    human_category = row["score_category"]

    prompt = build_full_prompt(essay_text, rubric_text, calibration_text)
    output = get_response(prompt)

    predicted_score = extract_final_score(output)
    predicted_category = extract_category(output)

    results.append({
        "essay_id": essay_id,
        "human_score": human_score,
        "human_category": human_category,
        "model_output": output,
        "predicted_score": predicted_score,
        "predicted_category": predicted_category
    })

    print(f"Done essay {essay_id}")
    time.sleep(1)   # optional, just to avoid rate issues

Done essay 66
Done essay 946
Done essay 837
Done essay 1710
Done essay 804
Done essay 1539
Done essay 1042
Done essay 241
Done essay 1211
Done essay 1485
Done essay 941
Done essay 1126
Done essay 1564
Done essay 1730
Done essay 1073
Done essay 922
Done essay 110
Done essay 1588
Done essay 558
Done essay 886
Done essay 355
Done essay 402
Done essay 1519
Done essay 1402
Done essay 325
Done essay 536
Done essay 1351
Done essay 699
Done essay 1691
Done essay 738

In [34]:
results_df = pd.DataFrame(results)
results_df

,essay_id,human_score,human_category,model_output,predicted_score,predicted_category
0,66,9,High,Final Score: 8\nCategory: Medium\nReasoning:\n...,8,Medium
1,946,8,Medium,Final Score: 8\nCategory: Medium\nReasoning:\n...,8,Medium
2,837,8,Medium,Final Score: 5\nCategory: Low\nReasoning:\n\nT...,5,Low
3,1710,9,High,Final Score: 8\nCategory: Medium\nReasoning:\n...,8,Medium
4,804,8,Medium,Final Score: 8\nCategory: Medium\nReasoning:\n...,8,Medium
5,1539,9,High,Final Score: 8\nCategory: Medium\nReasoning:\n...,8,Medium
6,1042,8,Medium,Final Score: 7\nCategory: Medium\nReasoning:\n...,7,Medium
7,241,9,High,Final Score: 8\nCategory: Medium\nReasoning:\n...,8,Medium
8,1211,9,High,Final Score: 8\nCategory: Medium\nReasoning:\n...,8,Medium
9,1485,9,High,Final Score: 8\nCategory: Medium\nReasoning:\n...,8,Medium
10,941,12,High,Final Score: 10\nCategory: High\nReasoning:\n\...,10,High
11,1126,10,High,Final Score: 8\nCategory: Medium\nReasoning:\n...,8,Medium
12,1564,8,Medium,Final Score: 7\nCategory: Medium\nReasoning:\n...,7,Medium
13,1730,10,High,Final Score: 8\nCategory: Medium\nReasoning:\n...,8,Medium
14,1073,8,Medium,Final Score: 8\nCategory: Medium\nReasoning:\n...,8,Medium
15,922,8,Medium,Final Score: 8\nCategory: Medium\nReasoning:\n...,8,Medium
16,110,6,Medium,Final Score: 8\nCategory: Medium\nReasoning:\n...,8,Medium
17,1588,10,High,Final Score: 9\nCategory: High\nReasoning:\n\n...,9,High
18,558,10,High,Final Score: 10\nCategory: High\nReasoning:\n\...,10,High
19,886,11,High,Final Score: 9\nCategory: High\nReasoning:\n\n...,9,High
20,355,6,Medium,Final Score: 8\nCategory: Medium\nReasoning:\n...,8,Medium
21,402,8,Medium,Final Score: 8\nCategory: Medium\nReasoning:\n...,8,Medium
22,1519,8,Medium,Final Score: 6\nCategory: Medium\nReasoning:\n...,6,Medium
23,1402,9,High,Final Score: 8\nCategory: Medium\nReasoning:\n...,8,Medium
24,325,9,High,Final Score: 8\nCategory: Medium\nReasoning:\n...,8,Medium
25,536,8,Medium,Final Score: 8\nCategory: Medium\nReasoning:\n...,8,Medium
26,1351,9,High,Final Score: 8\nCategory: Medium\nReasoning:\n...,8,Medium
27,699,12,High,Final Score: 10\nCategory: High\nReasoning:\n\...,10,High
28,1691,11,High,Final Score: 8\nCategory: Medium\nReasoning:\n...,8,Medium
29,738,6,Medium,Final Score: 8\nCategory: Medium\nReasoning:\n...,8,Medium

In [35]:
print(results_df[[
    "essay_id",
    "human_score",
    "predicted_score",
    "human_category",
    "predicted_category"
]])

print("\nMissing predicted scores:", results_df["predicted_score"].isna().sum())

    essay_id  human_score  predicted_score human_category predicted_category
0         66            9                8           High             Medium
1        946            8                8         Medium             Medium
2        837            8                5         Medium                Low
3       1710            9                8           High             Medium
4        804            8                8         Medium             Medium
5       1539            9                8           High             Medium
6       1042            8                7         Medium             Medium
7        241            9                8           High             Medium
8       1211            9                8           High             Medium
9       1485            9                8           High             Medium
10       941           12               10           High               High
11      1126           10                8           High             Medium
12      1564            8                7         Medium             Medium
13      1730           10                8           High             Medium
14      1073            8                8         Medium             Medium
15       922            8                8         Medium             Medium
16       110            6                8         Medium             Medium
17      1588           10                9           High               High
18       558           10               10           High               High
19       886           11                9           High               High
20       355            6                8         Medium             Medium
21       402            8                8         Medium             Medium
22      1519            8                6         Medium             Medium
23      1402            9                8           High             Medium
24       325            9                8           High             Medium
25       536            8                8         Medium             Medium
26      1351            9                8           High             Medium
27       699           12               10           High               High
28      1691           11                8           High             Medium
29       738            6                8         Medium             Medium

Missing predicted scores: 0

In [36]:
clean_df = results_df.dropna(subset=["predicted_score"]).copy()

qwk = cohen_kappa_score(
    clean_df['human_score'],
    clean_df['predicted_score'],
    weights='quadratic',
     labels=list(range(2, 13))
)

pcc, _ = pearsonr(
    clean_df["human_score"],
    clean_df["predicted_score"]
)

mae = mean_absolute_error(
    clean_df["human_score"],
    clean_df["predicted_score"]
)

print("QWK:", qwk)
print("PCC:", pcc)
print("MAE:", mae)

QWK: 0.42274052478134116
PCC: 0.5520111661711754
MAE: 1.2

**MTS**

In [22]:
def build_mts_test_prompt(essay_id, essay_text, rubric_text, calibration_text_with_id):
    return f"""
You are an expert essay grader evaluating student essays.

{rubric_text}

Calibration Examples:
{calibration_text_with_id}

Now evaluate the following essay step by step.

Essay ID: {essay_id}

Essay:
{essay_text}

Follow these steps internally:
1. Judge Content Quality from 1 to 6.
2. Judge Organization from 1 to 6.
3. Judge Language Score from 1 to 6.
4. Calculate the average of the three trait scores.
5. Multiply the average by 2.
6. Round to the nearest integer to get the Final Score.
7. Assign category:
   - Low = 2–5
   - Medium = 6–8
   - High = 9–12

IMPORTANT:
- Do NOT show step-by-step explanations.
- Do NOT add headings like "Step 1".
- Do NOT add any extra text before or after the final template.
- Use this exact format only.

Return exactly this:

Essay ID: {essay_id}
Content Score: <1-6>
Organization Score: <1-6>
Language Score: <1-6>
Average: <number>
Final Score: <2-12>
Category: <Low/Medium/High>
Reasoning: <2-3 short sentences>
"""

In [23]:
def extract_mts_trait_score(text, trait_name):
    if not isinstance(text, str):
        return None

    pattern = rf"{trait_name}:\s*(\d+)"
    match = re.search(pattern, text, re.IGNORECASE)
    if match:
        score = int(match.group(1))
        return max(1, min(6, score))
    return None

def extract_mts_average(text):
    if not isinstance(text, str):
        return None

    match = re.search(r"Average:\s*([0-9]+(?:\.[0-9]+)?)", text, re.IGNORECASE)
    if match:
        return float(match.group(1))
    return None

def extract_mts_final_score(text):
    if not isinstance(text, str):
        return None

    match = re.search(r"Final Score:\s*(\d+)", text, re.IGNORECASE)
    if match:
        score = int(match.group(1))
        return max(2, min(12, score))
    return None

def extract_mts_category(text):
    if not isinstance(text, str):
        return None

    match = re.search(r"Category:\s*(Low|Medium|High)", text, re.IGNORECASE)
    if match:
        return match.group(1).capitalize()
    return None

In [37]:
mts_results = []

for _, row in demo_30.iterrows():
    essay_id = row["essay_id"]
    essay_text = row["essay"]
    human_score = row["domain1_score"]
    human_category = row["score_category"]

    prompt = build_mts_test_prompt(
        essay_id=essay_id,
        essay_text=essay_text,
        rubric_text=rubric_text,
        calibration_text_with_id=calibration_text_with_id
    )

    output = get_response(prompt)

    content_score = extract_mts_trait_score(output, "Content Score")
    organization_score = extract_mts_trait_score(output, "Organization Score")
    language_score = extract_mts_trait_score(output, "Language Score")
    average_score = extract_mts_average(output)
    predicted_score = extract_mts_final_score(output)
    predicted_category = extract_mts_category(output)

    mts_results.append({
        "essay_id": essay_id,
        "human_score": human_score,
        "human_category": human_category,
        "raw_output": output,
        "content_score": content_score,
        "organization_score": organization_score,
        "language_score": language_score,
        "average_score": average_score,
        "predicted_score": predicted_score,
        "predicted_category": predicted_category
    })

    print(f"MTS done essay {essay_id}")
    time.sleep(1)

MTS done essay 66
MTS done essay 946
MTS done essay 837
MTS done essay 1710
MTS done essay 804
MTS done essay 1539
MTS done essay 1042
MTS done essay 241
MTS done essay 1211
MTS done essay 1485
MTS done essay 941
MTS done essay 1126
MTS done essay 1564
MTS done essay 1730
MTS done essay 1073
MTS done essay 922
MTS done essay 110
MTS done essay 1588
MTS done essay 558
MTS done essay 886
MTS done essay 355
MTS done essay 402
MTS done essay 1519
MTS done essay 1402
MTS done essay 325
MTS done essay 536
MTS done essay 1351
MTS done essay 699
MTS done essay 1691
MTS done essay 738

In [38]:
mts_results_df = pd.DataFrame(mts_results)
mts_results_df

,essay_id,human_score,human_category,raw_output,content_score,organization_score,language_score,average_score,predicted_score,predicted_category
0,66,9,High,Essay ID: 66\nContent Score: 5\nOrganization S...,5,5,4,4.67,9,Medium
1,946,8,Medium,Essay ID: 946\nContent Score: 5\nOrganization ...,5,5,4,4.67,9,High
2,837,8,Medium,Essay ID: 837\nContent Score: 4\nOrganization ...,4,3,2,3.00,6,Low
3,1710,9,High,Essay ID: 1710\nContent Score: 4\nOrganization...,4,4,3,3.67,7,Low
4,804,8,Medium,Essay ID: 804\nContent Score: 5\nOrganization ...,5,4,5,4.67,9,High
5,1539,9,High,Essay ID: 1539\nContent Score: 5\nOrganization...,5,4,5,4.67,9,Medium
6,1042,8,Medium,Essay ID: 1042\nContent Score: 4\nOrganization...,4,4,3,3.67,7,Low
7,241,9,High,Essay ID: 241\nContent Score: 4\nOrganization ...,4,3,2,3.00,6,Low
8,1211,9,High,Essay ID: 1211\nContent Score: 5\nOrganization...,5,5,4,4.67,9,Medium
9,1485,9,High,Essay ID: 1485\nContent Score: 5\nOrganization...,5,4,4,4.33,8,Medium
10,941,12,High,Essay ID: 941\nContent Score: 5\nOrganization ...,5,5,4,4.67,9,High
11,1126,10,High,Essay ID: 1126\nContent Score: 4\nOrganization...,4,4,3,3.67,7,Medium
12,1564,8,Medium,Essay ID: 1564\nContent Score: 4\nOrganization...,4,3,2,3.00,6,Low
13,1730,10,High,Essay ID: 1730\nContent Score: 5\nOrganization...,5,4,4,4.33,8,Medium
14,1073,8,Medium,Essay ID: 1073\nContent Score: 5\nOrganization...,5,4,4,4.33,8,Medium
15,922,8,Medium,Essay ID: 922\nContent Score: 5\nOrganization ...,5,5,5,5.00,10,Medium
16,110,6,Medium,Essay ID: 110\nContent Score: 5\nOrganization ...,5,5,4,4.67,9,High
17,1588,10,High,Essay ID: 1588\nContent Score: 5\nOrganization...,5,5,4,4.67,9,High
18,558,10,High,Essay ID: 558\nContent Score: 5\nOrganization ...,5,5,4,4.67,9,High
19,886,11,High,Essay ID: 886\nContent Score: 5\nOrganization ...,5,5,4,4.67,9,Medium
20,355,6,Medium,Essay ID: 355\nContent Score: 4\nOrganization ...,4,3,4,3.67,7,Low
21,402,8,Medium,Essay ID: 402\nContent Score: 4\nOrganization ...,4,4,3,3.67,7,Low
22,1519,8,Medium,Essay ID: 1519\nContent Score: 4\nOrganization...,4,3,2,3.00,6,Low
23,1402,9,High,Essay ID: 1402\nContent Score: 5\nOrganization...,5,5,5,5.00,10,Medium
24,325,9,High,Essay ID: 325\nContent Score: 5\nOrganization ...,5,4,4,4.33,8,Medium
25,536,8,Medium,Essay ID: 536\nContent Score: 5\nOrganization ...,5,5,4,4.67,9,Medium
26,1351,9,High,Essay ID: 1351\nContent Score: 5\nOrganization...,5,5,4,4.67,9,Medium
27,699,12,High,Essay ID: 699\nContent Score: 5\nOrganization ...,5,5,4,4.67,9,Medium
28,1691,11,High,Essay ID: 1691\nContent Score: 5\nOrganization...,5,4,3,4.00,8,Medium
29,738,6,Medium,Essay ID: 738\nContent Score: 4\nOrganization ...,4,4,3,3.67,7,Medium

In [41]:
mts_clean_df = mts_results_df.dropna(subset=["predicted_score"]).copy()

mts_qwk = cohen_kappa_score(
    mts_clean_df["human_score"],
    mts_clean_df["predicted_score"],
    weights="quadratic",
)

mts_pcc, _ = pearsonr(
    mts_clean_df["human_score"],
    mts_clean_df["predicted_score"]
)

mts_mae = mean_absolute_error(
    mts_clean_df["human_score"],
    mts_clean_df["predicted_score"]
)

print("MTS QWK:", mts_qwk)
print("MTS PCC:", mts_pcc)
print("MTS MAE:", mts_mae)

MTS QWK: 0.248
MTS PCC: 0.2916071258946822
MTS MAE: 1.4666666666666666